Repository scireum/sirius-biz, pull requests merged in 2020-12, with the labels that each got.

#933 Changea ExtractedZipFile inputstream to supplier
  src/main/java/sirius/biz/util/ArchiveExtractor.java
  src/main/java/sirius/biz/util/ExtractedZipFile.java
Labels: 🐛 Bugfix

#937 $$ for parameters
  src/main/java/sirius/biz/jobs/batch/file/LineBasedImportJob.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#939 SIRI-286 Sanitize paths in the storage engine
  src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
  src/main/java/sirius/biz/storage/layer3/VirtualFileSystem.java
  src/main/java/sirius/biz/storage/util/StorageUtils.java
Labels:  💣 BREAKING CHANGE, 🧬 Enhancement

#941 Adds getter for addressable name in a specific language
  src/main/java/sirius/biz/model/PersonData.java
Labels: 👶🏻 Trivial

#942 Dependency Upgrade
  pom.xml
Labels: 👶🏻 Trivial

#900 BREAKING: Valid languages for Translations are now customizable
  src/main/java/sirius/biz/codelists/jdbc/SQLCodeListEntry.java
  src/main/java/sirius/biz/codelists/mongo/MongoCodeListEntry.java
  src/main/java/sirius/biz/translations/BasicTranslations.java
  src/main/java/sirius/biz/translations/jdbc/SQLTranslations.java
  src/main/java/sirius/biz/translations/mongo/MongoTranslations.java
  src/main/resources/biz_cs.properties
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
  src/main/resources/biz_fr.properties
  src/main/resources/biz_it.properties
  src/main/resources/biz_nl.properties
  src/main/resources/biz_pl.properties
  src/test/java/sirius/biz/translations/MongoTranslatable.java
  src/test/java/sirius/biz/translations/MongoTranslatableTestEntity.java
  src/test/java/sirius/biz/translations/MongoTranslationsSpec.groovy
  src/test/java/sirius/biz/translations/SQLTranslatable.java
  src/test/java/sirius/biz/translations/SQLTranslatableTestEntity.java
  src/test/java/sirius/biz/translations/SQLTranslationsSpec.groovy
Labels:  💣 BREAKING CHANGE

#946 Add /system/tags to the menu links
  src/main/resources/default/extensions/biz-menu/menu-documentation.html.pasta
Labels: 👶🏻 Trivial

#947 Records even more metrics for the blob conversion of the storage framework.
  src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLVariant.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoVariant.java
  src/main/java/sirius/biz/storage/layer2/variants/ConversionEngine.java
  src/main/java/sirius/biz/storage/layer2/variants/ConversionProcess.java
  src/main/java/sirius/biz/storage/layer2/variants/Converter.java
  src/main/java/sirius/biz/storage/layer2/variants/IdentityConverter.java
Labels:  💣 BREAKING CHANGE, 🧬 Enhancement

#944 Import Handler: smartGet over languages
  src/main/java/sirius/biz/importer/BaseImportHandler.java
  src/main/java/sirius/biz/importer/format/FieldDefinition.java
Labels:  💣 BREAKING CHANGE, 🧬 Enhancement

#945 Update to the new Tagliatelle engine.
  docker-compose.yml
  src/main/java/sirius/biz/cluster/work/DistributedQueueLoadInfo.java
  src/main/java/sirius/biz/storage/util/StorageMetrics.java
  src/main/java/sirius/biz/web/BizClassAliasProvider.java
  src/main/java/sirius/biz/web/BizLegacyGlobalsHandler.java
  src/main/java/sirius/biz/web/ComputeAuthSignatureMacro.java
  src/main/java/sirius/biz/web/SignLinkMacro.java
  src/main/resources/default/extensions/wondergem-page-menu/menu.html.pasta
  src/main/resources/default/taglib/w/blobHardRefField.html.pasta
  src/main/resources/default/taglib/w/blobSoftRefField.html.pasta
  src/main/resources/default/taglib/w/directoryfield.html.pasta
  src/main/resources/default/taglib/w/filefield.html.pasta
  src/main/resources/default/taglib/w/jobs.html.pasta
  src/main/resources/default/taglib/w/selectObject.html.pasta
  src/main/resources/default/taglib/w/storedObjectUploader.html.pasta
  src/main/resources/default/templates/biz/login-form.html.pasta
  src/main/resources/default/templates/biz/process/process-output-chart.html.pasta
  src/main/resources/default/templates/biz/tenants/saml.html.pasta
  src/test/resources/docker-compose.yml
Labels:  💣 BREAKING CHANGE, 🕔 Wait on sirius

#949 Uses the new Mongo API which prevents error prone calls.
  src/main/java/sirius/biz/analytics/metrics/mongo/MongoMetrics.java
  src/main/java/sirius/biz/sequences/mongo/MongoSequenceStrategy.java
  src/main/java/sirius/biz/storage/layer1/replication/mongo/MongoReplicationTaskStorage.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoProcessBlobChangesLoop.java
  src/main/java/sirius/biz/tenants/mongo/MongoTenantAutoSetup.java
  src/test/java/sirius/biz/importer/SQLTenantImportHandler.java
Labels: 🕔 Wait on sirius
