Repository scireum/sirius-biz, pull requests merged in 2020-11, with the labels that each got.

#898 Adds errorneous facet to processes page
  src/main/java/sirius/biz/process/ProcessController.java
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
Labels: 👶🏻 Trivial

#901 Only handle upload as job file if it is not empty
  src/main/java/sirius/biz/jobs/JobsRoot.java
Labels: 🐛 Bugfix

#905 Provides a streamlined API to access 7-ZIP
  src/main/java/sirius/biz/jobs/params/DateRangeParameter.java
  src/main/java/sirius/biz/process/ProcessController.java
  src/main/java/sirius/biz/process/output/LogsProcessOutputType.java
  src/main/java/sirius/biz/process/output/TableProcessOutputType.java
  src/main/java/sirius/biz/protocol/AuditLogController.java
  src/main/java/sirius/biz/protocol/IncidentController.java
  src/main/java/sirius/biz/protocol/JournalController.java
  src/main/java/sirius/biz/protocol/LogController.java
  src/main/java/sirius/biz/protocol/MailController.java
  src/main/java/sirius/biz/protocol/TraceData.java
  src/main/java/sirius/biz/util/ArchiveExtractor.java
  src/main/java/sirius/biz/util/Extracted7ZFile.java
  src/main/java/sirius/biz/util/ExtractedFile.java
  src/main/java/sirius/biz/util/ExtractedZipFile.java
  src/main/java/sirius/biz/util/SevenZipAdapter.java
  src/main/resources/biz_de.properties
  src/main/resources/component-biz.conf
  src/main/resources/default/templates/biz/jobs/params/virtual-object-autocomplete.html.pasta
Labels: 🧬 Enhancement

#910 Lazily initializes a parameter.
  src/main/java/sirius/biz/storage/layer3/ExtractArchiveJob.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#911 Dependency Upgrade
  pom.xml
Labels: 👶🏻 Trivial

#913 Fixes for Jobs and Parameters
  src/main/java/sirius/biz/jobs/batch/file/FileImportJobFactory.java
  src/main/java/sirius/biz/jobs/batch/file/XMLExportJob.java
  src/main/java/sirius/biz/jobs/batch/file/XMLExportJobFactory.java
  src/main/java/sirius/biz/jobs/batch/file/XMLImportJob.java
  src/main/java/sirius/biz/jobs/batch/file/XMLImportJobFactory.java
  src/main/java/sirius/biz/jobs/params/SelectStringParameter.java
Labels: 🐛 Bugfix, 🧬 Enhancement

#914 Prevents an NPE when unpacking ZIP archives with subdirectories.
  src/main/java/sirius/biz/util/ArchiveExtractor.java
Labels: 🐛 Bugfix

#916 Fix the retry mechanism of variants
  src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java
Labels: 🐛 Bugfix

#919 Adds new parameter to ExtractArchiveJob to flatten dirs
  src/main/java/sirius/biz/storage/layer3/ExtractArchiveJob.java
  src/main/resources/biz_de.properties
Labels: 🧬 Enhancement

#917 Adds the default Mapping for a journaled entity to the interface
  src/main/java/sirius/biz/importer/txn/ImportTransactionalEntity.java
  src/main/java/sirius/biz/protocol/Journaled.java
  src/main/java/sirius/biz/tenants/TenantData.java
  src/main/java/sirius/biz/tenants/jdbc/SQLUserAccount.java
  src/main/java/sirius/biz/tenants/mongo/MongoUserAccount.java
Labels: 👶🏻 Trivial

#923 Properly returns the item count in a query when paginating
  src/main/java/sirius/biz/web/BasePageHelper.java
Labels: 🐛 Bugfix

#925 Fixes the blob_sort_by_last_modified index
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#920 Provides a minimal Redis management / query UI
  src/main/java/sirius/biz/jdbc/DatabaseController.java
  src/main/java/sirius/biz/util/RedisController.java
  src/main/resources/biz_de.properties
  src/main/resources/default/extensions/biz-menu/menu-system-tenant.html.pasta
  src/main/resources/default/templates/biz/model/redis.html.pasta
  src/main/resources/default/templates/biz/model/sql.html.pasta
Labels: 🧬 Enhancement

#928 Fix invalid formatting syntax
  src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
Labels: 👶🏻 Trivial

#929 Correctly orders by last modified date in descending order
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#926 Handles creation, change and deletion of BlobSoftRef references
  src/main/java/sirius/biz/storage/layer2/BlobCreatedRenamedHandler.java
  src/main/java/sirius/biz/storage/layer2/BlobSoftRef.java
  src/main/java/sirius/biz/storage/layer2/BlobSoftRefProperty.java
  src/main/java/sirius/biz/storage/layer2/ProcessBlobChangesLoop.java
  src/main/java/sirius/biz/storage/layer2/jdbc/RemoveDeletedEntitiesLoop.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLProcessBlobChangesLoop.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoProcessBlobChangesLoop.java
  src/main/java/sirius/biz/storage/layer2/mongo/RemoveDeletedEntitiesLoop.java
  src/main/resources/component-biz.conf
  src/test/java/sirius/biz/storage/layer2/BlobRefEntity.java
Labels:  💣 BREAKING CHANGE
