Repository scireum/sirius-biz, pull requests merged in 2020-04, with the labels that each got.

#708 Updates required by changes in sirius-db.
  pom.xml
  src/main/java/sirius/biz/elastic/reindex/MoveIndexAliasJobFactory.java
  src/main/java/sirius/biz/elastic/reindex/ReindexJobFactory.java
  src/main/java/sirius/biz/jobs/batch/DefaultBatchProcessFactory.java
Labels:  💣 BREAKING CHANGE

#715 Adds a utility method for the SaveHelper.
  src/main/java/sirius/biz/web/SaveHelper.java
Labels: 👶🏻 Trivial, 🧬 Enhancement

#717 re-add necessary cast
  src/main/java/sirius/biz/tenants/jdbc/SQLUserAccount.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#718 Monitoring Job for Elasticsearch (index size + cluster health)
  pom.xml
  src/main/java/sirius/biz/analytics/reports/Cells.java
  src/main/java/sirius/biz/elastic/ElasticIndexSizeReportJobFactory.java
  src/main/java/sirius/biz/elastic/MoveIndexAliasJobFactory.java
  src/main/java/sirius/biz/elastic/ReindexJobFactory.java
  src/main/java/sirius/biz/storage/layer2/variants/ConversionEngine.java
Labels: 🧬 Enhancement

#721 Updates to the latest sirius dependencies
  pom.xml
Labels: 👶🏻 Trivial, 🧬 Enhancement

#723 Fixes to Indicators
  src/main/java/sirius/biz/analytics/indicators/IndicatorData.java
  src/main/java/sirius/biz/analytics/scheduler/MongoAnalyticalTaskScheduler.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#730 Updates to the latest sirius dependencies
  pom.xml
Labels: 👶🏻 Trivial, 🧬 Enhancement

#737 Displays the maintenance message as a warning in the backend
  src/main/java/sirius/biz/web/DisasterModeInfo.java
Labels: 👶🏻 Trivial
