Repository scireum/sirius-biz, pull requests merged in 2020-03, with the labels that each got.

#700 SIRI-188 Updates to the latest sirius dependencies
  pom.xml
Labels: 👶🏻 Trivial, 🧬 Enhancement

#699 Properly persists indicators
  src/main/java/sirius/biz/analytics/indicators/IndicatorData.java
  src/test/java/sirius/biz/analytics/indicators/CheckValueIndicator.java
  src/test/java/sirius/biz/analytics/indicators/IndicatorSpec.groovy
  src/test/java/sirius/biz/analytics/indicators/IndicatorTestEntity.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#701 Provides a job which exports the results of a SQL query as Excel / CSV
  pom.xml
  src/main/java/sirius/biz/analytics/events/UserData.java
  src/main/java/sirius/biz/jdbc/DatabaseParameter.java
  src/main/java/sirius/biz/jdbc/ExportQueryResultJobFactory.java
  src/main/java/sirius/biz/jobs/batch/file/EntityExportJob.java
  src/main/java/sirius/biz/jobs/batch/file/LineBasedExportJob.java
  src/main/java/sirius/biz/jobs/params/SelectParameter.java
  src/main/java/sirius/biz/jobs/params/SelectStringParameter.java
  src/main/java/sirius/biz/jobs/params/TextParameter.java
  src/main/java/sirius/biz/jobs/params/TextareaParameter.java
  src/main/java/sirius/biz/mongo/PrefixSearchableEntity.java
  src/main/java/sirius/biz/storage/UpdatingOutputStream.java
  src/main/java/sirius/biz/storage/layer3/uplink/sftp/SFTPUplink.java
  src/main/resources/default/templates/biz/jobs/params/selectString.html.pasta
  src/main/resources/default/templates/biz/jobs/params/textarea.html.pasta
Labels: 🧬 Enhancement

#697 Adds VirtualFile.download and uses it in the FileImportJob
  src/main/java/sirius/biz/jobs/batch/BatchJob.java
  src/main/java/sirius/biz/jobs/batch/file/EntityImportJob.java
  src/main/java/sirius/biz/jobs/batch/file/FileImportJob.java
  src/main/java/sirius/biz/storage/layer2/L3Uplink.java
  src/main/java/sirius/biz/storage/layer3/MutableVirtualFile.java
  src/main/java/sirius/biz/storage/layer3/TmpRoot.java
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
  src/main/java/sirius/biz/storage/layer3/uplink/fs/LocalDirectoryUplink.java
  src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplink.java
  src/main/java/sirius/biz/storage/layer3/uplink/sftp/SFTPUplink.java
Labels:  💣 BREAKING CHANGE, 🧬 Enhancement

#706 SE-9475 Adds the country translations from OXOMI
  src/main/resources/biz_cs.properties
  src/main/resources/biz_da.properties
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
  src/main/resources/biz_es.properties
  src/main/resources/biz_fr.properties
  src/main/resources/biz_hu.properties
  src/main/resources/biz_it.properties
  src/main/resources/biz_nl.properties
  src/main/resources/biz_pl.properties
  src/main/resources/biz_se.properties
Labels: 👶🏻 Trivial, 🧬 Enhancement

#707 SE-9475 Adds a getter for the translated country to InternationalAddressData
  src/main/java/sirius/biz/model/InternationalAddressData.java
Labels: 🧬 Enhancement
