Repository scireum/sirius-biz, pull requests merged in 2020-01, with the labels that each got.

#635 Aha/codelist parameter fix
  src/main/java/sirius/biz/codelists/CodeListController.java
  src/main/java/sirius/biz/codelists/jdbc/SQLCodeListExportJobFactory.java
  src/main/java/sirius/biz/codelists/jdbc/SQLCodeListImportJobFactory.java
  src/main/java/sirius/biz/codelists/mongo/MongoCodeListExportJobFactory.java
  src/main/java/sirius/biz/codelists/mongo/MongoCodeListImportJobFactory.java
Labels: keep open

#671 Adds constructors to create fields without checks or formats
  src/main/java/sirius/biz/importer/format/FieldDefinition.java
Labels: enhancement

#670 Provides a helper to conveniently check permissions on an entity with…
  src/main/java/sirius/biz/model/PermissionData.java
Labels: enhancement

#673 Improves the detection of broken FTP connections
  src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplinkConnectorConfig.java
  src/main/java/sirius/biz/storage/layer3/uplink/util/ListUplinkConnectorsCommand.java
  src/main/java/sirius/biz/storage/layer3/uplink/util/UplinkConnector.java
  src/main/java/sirius/biz/storage/layer3/uplink/util/UplinkConnectorFactory.java
  src/main/java/sirius/biz/storage/layer3/uplink/util/UplinksCommand.java
Labels: Bug-Fix

#675 Makes the required check aware of the automatic trim performed by mos…
  pom.xml
  src/main/java/sirius/biz/importer/format/RequiredCheck.java
Labels: BREAKING CHANGE, enhancement

#669 Adds new creation methods for MutableVirtualFile to offer a safe variant
  src/main/java/sirius/biz/jobs/JobsRoot.java
  src/main/java/sirius/biz/storage/layer2/L3Uplink.java
  src/main/java/sirius/biz/storage/layer3/MutableVirtualFile.java
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
  src/main/java/sirius/biz/storage/layer3/uplink/ConfigBasedUplink.java
  src/main/java/sirius/biz/storage/layer3/uplink/cifs/CIFSUplink.java
  src/main/java/sirius/biz/storage/layer3/uplink/fs/LocalDirectoryUplink.java
  src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplink.java
  src/main/java/sirius/biz/storage/layer3/uplink/sftp/SFTPUplink.java
Labels: BREAKING CHANGE, Bug-Fix

#678 Two minor fixes
  src/main/java/sirius/biz/analytics/metrics/mongo/MongoMetrics.java
  src/main/java/sirius/biz/model/InternationalAddressData.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLVariant.java
Labels: Bug-Fix, trivial

#677 Auto-translate field definition labels using NLS.smartGet
  src/main/java/sirius/biz/importer/format/FieldDefinition.java
Labels: trivial

#672 Enhances the Importer to receive the job factory name used to initialize it
  src/main/java/sirius/biz/importer/Importer.java
  src/main/java/sirius/biz/jobs/batch/file/EntityExportJob.java
  src/main/java/sirius/biz/jobs/batch/file/EntityExportJobFactory.java
  src/main/java/sirius/biz/jobs/batch/file/EntityImportJob.java
  src/main/java/sirius/biz/jobs/batch/file/EntityImportJobFactory.java
Labels: 🧬 Enhancement
