Repository scireum/sirius-biz, pull requests merged in 2020-09, with the labels that each got.

#848 Fixes file name in FileImportJob
  src/main/java/sirius/biz/jobs/batch/file/FileImportJob.java
Labels: 🐛 Bugfix

#850 Allows job parameters to be logged only as system message or not at all
  src/main/java/sirius/biz/jobs/batch/BatchProcessJobFactory.java
  src/main/java/sirius/biz/jobs/params/Parameter.java
  src/main/resources/biz_de.properties
Labels: 🧬 Enhancement

#852 Removes support for legacy url support for blobs
  src/main/java/sirius/biz/storage/layer2/BlobDispatcher.java
Labels: 👶🏻 Trivial

#856 Exposes the CSVWriter in ExportCSV
  src/main/java/sirius/biz/jobs/batch/file/ExportCSV.java
Labels: 👶🏻 Trivial, 🧬 Enhancement

#862 SIRI-258: enhance password change
  src/main/resources/default/templates/biz/password/password.html.pasta
Labels: 🐛 Bugfix

#863 Fixes a NPE trying to close a never opened stream
  src/main/java/sirius/biz/jobs/batch/file/ArchiveExportJob.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#864 Improves the error message throws when loading columns of a CSV file
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
Labels: 👶🏻 Trivial

#865 Adds missing job description for the virtual file system archive extr…
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
Labels: 👶🏻 Trivial

#867 Fixes backend search for Mongo codelists + codelist entries
  src/main/java/sirius/biz/codelists/CodeListController.java
  src/main/java/sirius/biz/codelists/CodeListData.java
  src/main/java/sirius/biz/codelists/CodeListEntryData.java
  src/main/java/sirius/biz/codelists/jdbc/SQLCodeListController.java
  src/main/java/sirius/biz/codelists/mongo/MongoCodeListController.java
  src/main/java/sirius/biz/codelists/mongo/MongoCodeListEntry.java
Labels: 🐛 Bugfix
