Repository scireum/sirius-biz, pull requests merged in 2020-05, with the labels that each got.

#752 Fixes a typo displayed in the UI
  src/main/resources/biz_de.properties
Labels: 👶🏻 Trivial

#754 SIRI-217 Fixes S3 multipart uploads
  src/main/java/sirius/biz/storage/s3/ObjectStore.java
Labels: 🐛 Bugfix

#756 SIRI-218: Fixing a NPE if redis returns a null list
  src/main/java/sirius/biz/cluster/work/RedisNamedCounters.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#744 Optimizes journal entries in import jobs.
  src/main/java/sirius/biz/importer/BaseImportHandler.java
  src/main/java/sirius/biz/protocol/JournalData.java
Labels: 🖐 Keep open

#741 Improves alias handling and permits to suppress tenant checks.
  src/main/java/sirius/biz/importer/BaseImportHandler.java
  src/main/java/sirius/biz/importer/format/FieldDefinition.java
  src/main/java/sirius/biz/importer/format/ImportDictionary.java
  src/main/java/sirius/biz/tenants/jdbc/SQLTenantAware.java
  src/main/java/sirius/biz/tenants/jdbc/SQLUserAccountImportHandler.java
  src/main/java/sirius/biz/tenants/mongo/MongoTenantAware.java
  src/main/java/sirius/biz/web/TenantAware.java
Labels: 🧬 Enhancement

#761 Removes heaps of calls to Guava and moves the legacy Storage into its own package.
  pom.xml
  src/main/java/sirius/biz/analytics/scheduler/AnalyticalEngine.java
  src/main/java/sirius/biz/i5/I5Connection.java
  src/main/java/sirius/biz/i5/I5Connector.java
  src/main/java/sirius/biz/i5/Transformable.java
  src/main/java/sirius/biz/i5/Transformer.java
  src/main/java/sirius/biz/importer/format/FieldDefinition.java
  src/main/java/sirius/biz/jobs/BasicJobFactory.java
  src/main/java/sirius/biz/jobs/JobsRoot.java
  src/main/java/sirius/biz/jobs/batch/BatchJob.java
  src/main/java/sirius/biz/jobs/batch/file/FileImportJob.java
  src/main/java/sirius/biz/jobs/presets/JobPresetsController.java
  src/main/java/sirius/biz/model/LegacyMD5HashFunction.java
  src/main/java/sirius/biz/storage/layer1/FSObjectStorageSpace.java
  src/main/java/sirius/biz/storage/layer1/S3ObjectStorageSpace.java
  src/main/java/sirius/biz/storage/layer1/replication/ReplicationBackgroundLoop.java
  src/main/java/sirius/biz/storage/layer1/replication/ReplicationManager.java
  src/main/java/sirius/biz/storage/layer1/replication/ReplicationTaskExecutor.java
  src/main/java/sirius/biz/storage/layer2/BlobHardRefProperty.java
  src/main/java/sirius/biz/storage/layer2/BlobSoftRefProperty.java
  src/main/java/sirius/biz/storage/layer3/VFSController.java
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
  src/main/java/sirius/biz/storage/layer3/downlink/ftp/BridgeFile.java
  src/main/java/sirius/biz/storage/layer3/downlink/ftp/FTPServer.java
  src/main/java/sirius/biz/storage/layer3/downlink/ssh/SSHServer.java
  src/main/java/sirius/biz/storage/layer3/uplink/util/UplinkConnectorConfig.java
  src/main/java/sirius/biz/storage/legacy/BucketInfo.java
  src/main/java/sirius/biz/storage/legacy/DownloadBuilder.java
  src/main/java/sirius/biz/storage/legacy/FSStorageEngine.java
  src/main/java/sirius/biz/storage/legacy/PhysicalStorageEngine.java
  src/main/java/sirius/biz/storage/legacy/Storage.java
  src/main/java/sirius/biz/storage/legacy/StorageCleanupTask.java
  src/main/java/sirius/biz/storage/legacy/StorageController.java
  src/main/java/sirius/biz/storage/legacy/StoredObject.java
  src/main/java/sirius/biz/storage/legacy/StoredObjectRef.java
  src/main/java/sirius/biz/storage/legacy/StoredObjectRefProperty.java
  src/main/java/sirius/biz/storage/legacy/UpdatingOutputStream.java
  src/main/java/sirius/biz/storage/legacy/VersionManager.java
  src/main/java/sirius/biz/storage/legacy/VersionedFile.java
  src/main/java/sirius/biz/storage/legacy/VersionedFiles.java
  src/main/java/sirius/biz/storage/legacy/VirtualObject.java
  src/main/java/sirius/biz/storage/legacy/VirtualObjectParameter.java
  src/main/java/sirius/biz/storage/legacy/VirtualObjectVersion.java
  src/main/java/sirius/biz/storage/util/StorageUtils.java
  src/main/java/sirius/biz/tenants/TenantUserManager.java
  src/main/java/sirius/biz/web/BizController.java
  src/main/resources/default/taglib/w/selectObject.html.pasta
  src/main/resources/default/taglib/w/storedObjectUploader.html.pasta
  src/main/resources/default/templates/biz/jobs/params/virtual-object-autocomplete.html.pasta
  src/main/resources/default/templates/biz/storage/buckets.html.pasta
  src/main/resources/default/templates/biz/storage/object.html.pasta
  src/main/resources/default/templates/biz/storage/objects.html.pasta
  src/test/java/sirius/biz/analytics/indicators/CheckValueIndicator.java
  src/test/java/sirius/biz/storage/layer1/ObjectStorageSpec.groovy
  src/test/java/sirius/biz/storage/layer1/ReplicationSpec.groovy
  src/test/java/sirius/biz/storage/legacy/VersionedFilesSpec.groovy
  src/test/java/sirius/biz/storage/s3/ObjectStoresSpec.groovy
  src/test/resources/test.conf
Labels:  💣 BREAKING CHANGE

#764 Fixes translations
  src/main/resources/biz_cs.properties
  src/main/resources/biz_fr.properties
  src/main/resources/biz_pl.properties
Labels: 👶🏻 Trivial

#763 Adds new property appendContextInErrorMessage and fluent …
  src/main/java/sirius/biz/importer/format/FieldDefinition.java
Labels: 👶🏻 Trivial

#765 Correctly translates the label of date range parameters
  src/main/java/sirius/biz/jobs/params/DateRangeParameter.java
Labels: 👶🏻 Trivial
