Repository scireum/sirius-biz, pull requests merged in 2020-10, with the labels that each got.

#839 Makes CodeListEntries translatable
  src/main/java/sirius/biz/codelists/CodeListController.java
  src/main/java/sirius/biz/codelists/CodeListData.java
  src/main/java/sirius/biz/codelists/CodeListEntry.java
  src/main/java/sirius/biz/codelists/CodeLists.java
  src/main/java/sirius/biz/codelists/jdbc/SQLCodeListEntry.java
  src/main/java/sirius/biz/codelists/mongo/MongoCodeListController.java
  src/main/java/sirius/biz/codelists/mongo/MongoCodeListEntry.java
  src/main/java/sirius/biz/jobs/params/CodeListEntryParameter.java
  src/test/java/sirius/biz/codelists/CodeListsSpec.groovy
  src/test/java/sirius/biz/translations/MongoTranslationsSpec.groovy
  src/test/java/sirius/biz/translations/SQLTranslationsSpec.groovy
Labels: 🧬 Enhancement

#873 TenantUserManager getUserSettings NPE fix
  src/main/java/sirius/biz/tenants/TenantUserManager.java
Labels: 👶🏻 Trivial

#874 Prevent a NPE
  src/main/java/sirius/biz/storage/layer2/BlobSoftRefProperty.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#875 Fixes NPE in CodeLists#getTranslatedValue
  src/main/java/sirius/biz/codelists/CodeLists.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#876 Add support for elastic entities to BlobRef-properties
  src/main/java/sirius/biz/storage/layer2/BlobRefProperty.java
Labels: 🧬 Enhancement

#877 SE-10049: Adds a preview img tag to blobHardRefField
  src/main/resources/default/taglib/w/blobHardRefField.html.pasta
Labels: 👶🏻 Trivial

#879 Allows to provide multiple XSDs for validation in XML import jobs
  src/main/java/sirius/biz/jobs/batch/file/XMLImportJob.java
  src/main/java/sirius/biz/jobs/batch/file/XMLImportJobFactory.java
  src/main/java/sirius/biz/jobs/params/SelectStringParameter.java
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
Labels: 🧬 Enhancement

#880 Implement a taglib for selecting a file for a blobSoftRef
  src/main/java/sirius/biz/storage/layer2/BlobController.java
  src/main/java/sirius/biz/storage/layer2/BlobHardRef.java
  src/main/java/sirius/biz/storage/layer2/BlobSoftRef.java
  src/main/resources/default/assets/javascript/blobreffield.js
  src/main/resources/default/assets/stylesheets/biz.scss
  src/main/resources/default/extensions/wondergem-page/scripts.html.pasta
  src/main/resources/default/extensions/wondergem-page/storage-vfs-modals.html.pasta
  src/main/resources/default/taglib/w/blobSoftRefField.html.pasta
  src/main/resources/default/taglib/w/filefield.html.pasta
Labels: 🧬 Enhancement

#882 Prevent BlobSoftRef#getPath from clearing the URL
  src/main/java/sirius/biz/storage/layer2/BlobSoftRef.java
Labels: 🐛 Bugfix

#883 Use the the variant's file extension in the generated URLs
  src/main/java/sirius/biz/storage/layer2/URLBuilder.java
Labels: 🐛 Bugfix

#884 Sirius-Web dev-29.18
  pom.xml
Labels: 👶🏻 Trivial

#891 Updates sirius-dependecies
  pom.xml
Labels: dependencies

#894 Correctly return the path for BlobSoftRefs
  src/main/java/sirius/biz/storage/layer2/BlobSoftRef.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#895 Add an unique index to the blob key
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java
Labels: 🧬 Enhancement
