Repository scireum/sirius-biz, pull requests merged in 2020-07, with the labels that each got.

#802 Fixes minor bugs and startup warnings.
  src/main/java/sirius/biz/analytics/metrics/jdbc/SQLMonthlyLargeMetricsScheduler.java
  src/main/java/sirius/biz/analytics/metrics/mongo/MongoMonthlyLargeMetricsScheduler.java
  src/main/java/sirius/biz/tenants/UserAccountActivityMetricComputer.java
  src/main/java/sirius/biz/tenants/jdbc/SQLUserAccountActivityMetricComputer.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#804 BREAKING CHANGE: Improves extending ImportHandlers and refactors the Metrics API
  src/main/java/sirius/biz/analytics/flags/PerformanceDataImportExtender.java
  src/main/java/sirius/biz/analytics/flags/PerformanceFlagged.java
  src/main/java/sirius/biz/analytics/flags/jdbc/SQLPerformanceData.java
  src/main/java/sirius/biz/analytics/flags/mongo/MongoPerformanceData.java
  src/main/java/sirius/biz/analytics/metrics/BasicMetrics.java
  src/main/java/sirius/biz/analytics/metrics/MetricQuery.java
  src/main/java/sirius/biz/analytics/metrics/Metrics.java
  src/main/java/sirius/biz/analytics/metrics/jdbc/SQLMetrics.java
  src/main/java/sirius/biz/analytics/metrics/mongo/MongoMetrics.java
  src/main/java/sirius/biz/analytics/scheduler/AnalyticalEngine.java
  src/main/java/sirius/biz/analytics/scheduler/BaseAnalyticalTaskScheduler.java
  src/main/java/sirius/biz/analytics/scheduler/BaseEntityBatchEmitter.java
  src/main/java/sirius/biz/analytics/scheduler/README.md
  src/main/java/sirius/biz/importer/BaseImportHandler.java
  src/main/java/sirius/biz/importer/EntityImportHandlerExtender.java
  src/main/java/sirius/biz/importer/ImportHandler.java
  src/main/java/sirius/biz/importer/format/ImportDictionary.java
  src/main/java/sirius/biz/jobs/batch/file/EntityExportJob.java
  src/main/java/sirius/biz/tenants/Tenant.java
  src/main/java/sirius/biz/tenants/jdbc/SQLTenant.java
  src/main/java/sirius/biz/tenants/jdbc/SQLTenantController.java
  src/main/java/sirius/biz/tenants/jdbc/SQLUserAccountImportHandler.java
  src/main/java/sirius/biz/tenants/mongo/MongoTenant.java
  src/main/java/sirius/biz/tenants/mongo/MongoTenantController.java
  src/main/java/sirius/biz/tenants/mongo/MongoUserAccountController.java
  src/main/java/sirius/biz/tenants/mongo/MongoUserAccountImportHandler.java
  src/main/resources/biz_de.properties
  src/main/resources/component-biz.conf
Labels:  💣 BREAKING CHANGE, 🧬 Enhancement

#811 Fix the codelist import and export
  src/main/resources/biz_cs.properties
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
  src/main/resources/biz_fr.properties
  src/main/resources/biz_it.properties
  src/main/resources/biz_nl.properties
  src/main/resources/biz_pl.properties
  src/main/resources/biz_sk.properties
  src/main/resources/default/templates/biz/codelists/code-list-entries.html.pasta
Labels: 🐛 Bugfix

#813 Jumps to the package configuration screen after creating a tenant
  pom.xml
  src/main/java/sirius/biz/tenants/TenantController.java
Labels: 👶🏻 Trivial, 🧬 Enhancement

#817 Fix an issue creating files in the storage
  src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
Labels: 🐛 Bugfix

#818 Adds indexes to MongoBlob
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLDirectory.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoDirectory.java
Labels: 🧬 Enhancement

#819 Returns the raw object instead of cache contents
  src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
Labels: 🐛 Bugfix

#822 Fixes to Cache and Storage
  src/main/java/sirius/biz/cluster/InterconnectCacheCoherence.java
  src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
Labels: 🐛 Bugfix

#824 Uses the presence marker fields for checkboxes provided in sirius-web.
  pom.xml
  src/main/java/sirius/biz/web/BizController.java
Labels: 🕔 Wait on sirius

#825 Delivers downloads not cached
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
Labels: 🐛 Bugfix

#828 Fixed Value class not recognizing String values as LocalDate
  src/main/java/sirius/biz/analytics/scheduler/AnalyticsBatchExecutor.java
  src/main/java/sirius/biz/analytics/scheduler/AnalyticsSchedulerExecutor.java
Labels: 👶🏻 Trivial

#829 Adds a default set of DateRanges to TraceData for time facets
  src/main/java/sirius/biz/protocol/TraceData.java
Labels: 👶🏻 Trivial

#830 Misc mini fixes.
  src/main/java/sirius/biz/analytics/metrics/DailyGlobalMetricComputer.java
  src/main/java/sirius/biz/analytics/metrics/DailyMetricComputer.java
  src/main/java/sirius/biz/analytics/metrics/MonthlyGlobalMetricComputer.java
  src/main/java/sirius/biz/analytics/metrics/MonthlyLargeMetricComputer.java
  src/main/java/sirius/biz/analytics/metrics/MonthlyMetricComputer.java
  src/main/java/sirius/biz/analytics/metrics/jdbc/SQLGuaranteedDailyMetricScheduler.java
  src/main/java/sirius/biz/analytics/metrics/mongo/MongoGuaranteedDailyMetricScheduler.java
  src/main/java/sirius/biz/analytics/metrics/mongo/MongoMonthlyLargeMetricsScheduler.java
  src/main/java/sirius/biz/isenguard/Isenguard.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#808 Introduction of translation entities
  src/main/java/sirius/biz/codelists/CodeList.java
  src/main/java/sirius/biz/codelists/CodeListEntry.java
  src/main/java/sirius/biz/importer/ImportHandler.java
  src/main/java/sirius/biz/translations/BasicTranslations.java
  src/main/java/sirius/biz/translations/Translatable.java
  src/main/java/sirius/biz/translations/Translation.java
  src/main/java/sirius/biz/translations/TranslationData.java
  src/main/java/sirius/biz/translations/jdbc/SQLTranslation.java
  src/main/java/sirius/biz/translations/jdbc/SQLTranslations.java
  src/main/java/sirius/biz/translations/mongo/MongoTranslation.java
  src/main/java/sirius/biz/translations/mongo/MongoTranslations.java
  src/main/java/sirius/biz/web/TenantAware.java
  src/test/java/sirius/biz/translations/MongoTranslatableTestEntity.java
  src/test/java/sirius/biz/translations/MongoTranslationsSpec.groovy
  src/test/java/sirius/biz/translations/SQLTranslatableTestEntity.java
  src/test/java/sirius/biz/translations/SQLTranslationsSpec.groovy
  src/test/java/sirius/biz/translations/TranslationsSpec.groovy
Labels: 🧬 Enhancement

#833 Provides a baseline for simple processcommands with no arguments
  src/main/java/sirius/biz/process/SimpleProcessCommand.java
Labels: 🧬 Enhancement

#834 Adds a facet for system messages in the process log
  src/main/java/sirius/biz/process/ProcessController.java
  src/main/java/sirius/biz/process/output/LogsProcessOutputType.java
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
Labels: 👶🏻 Trivial

#835 Corrected biz_de.properties
  src/main/resources/biz_de.properties
Labels: 👶🏻 Trivial

#837 Adds Length and Lob annotations to TranslationData
  src/main/java/sirius/biz/translations/TranslationData.java
Labels: 🐛 Bugfix

#836 BREAKING: Only loads fields from requests when matching param is given
  src/main/java/sirius/biz/web/BizController.java
Labels:  💣 BREAKING CHANGE
