Repository scireum/sirius-biz, pull requests merged in 2020-06, with the labels that each got.

#766 SIRI-222: add logging on ftp upload
  src/main/java/sirius/biz/storage/layer3/downlink/ftp/BridgeFile.java
Labels: 👶🏻 Trivial

#770 SE-9718 Adds a cache for resolving blobs by path
  src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java
  src/main/resources/component-biz.conf
Labels: 🧬 Enhancement

#771 Prevents a NPE in the ConversionEngine
  src/main/java/sirius/biz/storage/layer2/variants/ConversionEngine.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#728 Updates the tokenizer settings for SearchableEntity and PrefixSearchableEntity
  pom.xml
  src/main/java/sirius/biz/analytics/reports/LinkCellFormat.java
  src/main/java/sirius/biz/analytics/scheduler/AnalyticalEngine.java
  src/main/java/sirius/biz/codelists/jdbc/SQLCodeListController.java
  src/main/java/sirius/biz/elastic/SearchableEntity.java
  src/main/java/sirius/biz/jdbc/DatabaseController.java
  src/main/java/sirius/biz/jobs/JobsController.java
  src/main/java/sirius/biz/jobs/JobsRoot.java
  src/main/java/sirius/biz/jobs/presets/jdbc/SQLJobPresetsController.java
  src/main/java/sirius/biz/jobs/scheduler/jdbc/SQLSchedulerController.java
  src/main/java/sirius/biz/model/QueryController.java
  src/main/java/sirius/biz/mongo/PrefixSearchableEntity.java
  src/main/java/sirius/biz/mongo/PrefixTokenizer.java
  src/main/java/sirius/biz/process/ProcessController.java
  src/main/java/sirius/biz/protocol/AuditLogController.java
  src/main/java/sirius/biz/protocol/IncidentController.java
  src/main/java/sirius/biz/protocol/JournalController.java
  src/main/java/sirius/biz/protocol/LogController.java
  src/main/java/sirius/biz/protocol/MailController.java
  src/main/java/sirius/biz/storage/layer1/FSObjectStorageSpace.java
  src/main/java/sirius/biz/storage/layer1/replication/ReplicationBackgroundLoop.java
  src/main/java/sirius/biz/storage/layer1/replication/ReplicationManager.java
  src/main/java/sirius/biz/storage/layer1/replication/ReplicationTaskExecutor.java
  src/main/java/sirius/biz/storage/layer2/BlobController.java
  src/main/java/sirius/biz/storage/layer2/BlobRefProperty.java
  src/main/java/sirius/biz/storage/layer3/VFSController.java
  src/main/java/sirius/biz/storage/legacy/BucketInfo.java
  src/main/java/sirius/biz/storage/legacy/DownloadBuilder.java
  src/main/java/sirius/biz/storage/legacy/FSStorageEngine.java
  src/main/java/sirius/biz/storage/legacy/PhysicalStorageEngine.java
  src/main/java/sirius/biz/storage/legacy/Storage.java
  src/main/java/sirius/biz/storage/legacy/StorageCleanupTask.java
  src/main/java/sirius/biz/storage/legacy/StorageController.java
  src/main/java/sirius/biz/storage/legacy/StoredObject.java
  src/main/java/sirius/biz/storage/legacy/StoredObjectRef.java
  src/main/java/sirius/biz/storage/legacy/StoredObjectRefProperty.java
  src/main/java/sirius/biz/storage/legacy/UpdatingOutputStream.java
  src/main/java/sirius/biz/storage/legacy/VersionManager.java
  src/main/java/sirius/biz/storage/legacy/VersionedFile.java
  src/main/java/sirius/biz/storage/legacy/VersionedFiles.java
  src/main/java/sirius/biz/storage/legacy/VirtualObject.java
  src/main/java/sirius/biz/storage/legacy/VirtualObjectParameter.java
  src/main/java/sirius/biz/storage/legacy/VirtualObjectVersion.java
  src/main/java/sirius/biz/storage/util/StorageUtils.java
  src/main/java/sirius/biz/tenants/ProfileController.java
  src/main/java/sirius/biz/tenants/SAMLController.java
  src/main/java/sirius/biz/tenants/mongo/MongoTenant.java
  src/main/java/sirius/biz/tenants/mongo/MongoUserAccount.java
  src/main/java/sirius/biz/web/DisasterController.java
  src/main/resources/component-biz.conf
  src/test/java/sirius/biz/elastic/SearchableEntitySpec.groovy
Labels: 🧬 Enhancement

#775 BREAKING: Improves the admin UI and permission management
  src/main/java/sirius/biz/packages/PackageData.java
  src/main/java/sirius/biz/packages/Packages.java
  src/main/java/sirius/biz/tenants/TenantController.java
  src/main/java/sirius/biz/tenants/TenantData.java
  src/main/java/sirius/biz/tenants/UserAccountController.java
  src/main/java/sirius/biz/tenants/jdbc/SQLTenantAutoSetup.java
  src/main/java/sirius/biz/tenants/jdbc/SQLUserAccountExportJobFactory.java
  src/main/java/sirius/biz/tenants/jdbc/SQLUserAccountImportJobFactory.java
  src/main/java/sirius/biz/tenants/mongo/MongoUserAccountExportJobFactory.java
  src/main/java/sirius/biz/tenants/mongo/MongoUserAccountImportJobFactory.java
  src/main/resources/biz_de.properties
  src/main/resources/component-biz.conf
  src/main/resources/default/extensions/biz-menu/menu-jobs.html.pasta
  src/main/resources/default/extensions/biz-menu/menu-tenants.html.pasta
  src/main/resources/default/extensions/biz-menu/menu-vfs.html.pasta
  src/main/resources/default/templates/biz/packages/additional-and-revoked-permissions.html.pasta
  src/main/resources/default/templates/biz/packages/packages-and-upgrades.html.pasta
  src/main/resources/default/templates/biz/tenants/tenant-details.html.pasta
  src/main/resources/default/templates/biz/tenants/tenant-extended.html.pasta
  src/main/resources/default/templates/biz/tenants/tenant-package.html.pasta
  src/main/resources/default/templates/biz/tenants/tenant-permissions.html.pasta
  src/main/resources/default/templates/biz/tenants/tenant.html.pasta
  src/test/java/sirius/biz/packages/PackageDataSpec.groovy
  src/test/java/sirius/biz/web/autoloading/AutoLoadController.java
Labels:  💣 BREAKING CHANGE

#781 Actually try to attach the blob to the owner instead the owner to itself
  src/main/java/sirius/biz/storage/layer2/BlobReferenceContainer.java
Labels: 🐛 Bugfix

#786 Permits to specify the actual selectable values for an enum.
  src/main/java/sirius/biz/jobs/params/EnumParameter.java
Labels: 👶🏻 Trivial, 🧬 Enhancement

#785 Cleanup of Directory Traversal + Transfer APIS in the VFS
  src/main/java/sirius/biz/analytics/events/ClickhousePartsReportJobFactory.java
  src/main/java/sirius/biz/analytics/events/ClickhouseSizeChartJobFactory.java
  src/main/java/sirius/biz/codelists/jdbc/SQLCodeListExportJobFactory.java
  src/main/java/sirius/biz/codelists/jdbc/SQLCodeListImportJobFactory.java
  src/main/java/sirius/biz/codelists/mongo/MongoCodeListExportJobFactory.java
  src/main/java/sirius/biz/codelists/mongo/MongoCodeListImportJobFactory.java
  src/main/java/sirius/biz/elastic/ElasticIndexSizeReportJobFactory.java
  src/main/java/sirius/biz/elastic/MoveIndexAliasJobFactory.java
  src/main/java/sirius/biz/elastic/ReindexJobFactory.java
  src/main/java/sirius/biz/isenguard/BlockedIPsReportJobFactory.java
  src/main/java/sirius/biz/isenguard/RateLimitEventsReportJobFactory.java
  src/main/java/sirius/biz/isenguard/RateLimitReportJobFactory.java
  src/main/java/sirius/biz/jdbc/ExportQueryResultJobFactory.java
  src/main/java/sirius/biz/jdbc/ExportSchemaChangesJobFactory.java
  src/main/java/sirius/biz/jobs/JobFactory.java
  src/main/java/sirius/biz/jobs/JobsRoot.java
  src/main/java/sirius/biz/model/ResaveEntitiesJobFactory.java
  src/main/java/sirius/biz/mongo/PrefixTokenizer.java
  src/main/java/sirius/biz/storage/layer3/BlockwiseIterator.java
  src/main/java/sirius/biz/storage/layer3/Transfer.java
  src/main/java/sirius/biz/storage/layer3/TransferFilesJob.java
  src/main/java/sirius/biz/storage/layer3/TreeVisitorBuilder.java
  src/main/java/sirius/biz/storage/layer3/VFSController.java
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
  src/main/java/sirius/biz/storage/layer3/VirtualFileWalker.java
  src/main/java/sirius/biz/tenants/deletion/DeleteTenantJobFactory.java
  src/main/java/sirius/biz/tenants/jdbc/SQLUserAccountExportJobFactory.java
  src/main/java/sirius/biz/tenants/jdbc/SQLUserAccountImportJobFactory.java
  src/main/java/sirius/biz/tenants/mongo/MongoUserAccountExportJobFactory.java
  src/main/java/sirius/biz/tenants/mongo/MongoUserAccountImportJobFactory.java
  src/main/resources/biz_cs.properties
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
  src/main/resources/biz_fr.properties
  src/main/resources/biz_it.properties
  src/main/resources/biz_nl.properties
  src/main/resources/biz_pl.properties
Labels:  💣 BREAKING CHANGE

#793 Fixes an incorrect editForm url
  pom.xml
  src/main/resources/default/templates/biz/tenants/tenant-extended.html.pasta
Labels: 🐛 Bugfix

#794 Force updating search prefixes on entity resave job
  src/main/java/sirius/biz/model/ResaveEntitiesJobFactory.java
Labels: 👶🏻 Trivial

#800 Flushes the coherent process cache on all nodes
  src/main/java/sirius/biz/process/Processes.java
Labels: 👶🏻 Trivial
