Repository scireum/sirius-biz, pull requests merged in 2021-09, with the labels that each got.

#1219 ProcessLog and ImportHandler improvements
  pom.xml
  src/main/java/sirius/biz/importer/BaseImportHandler.java
  src/main/java/sirius/biz/importer/MongoEntityImportHandler.java
  src/main/java/sirius/biz/importer/SQLEntityImportHandler.java
  src/main/java/sirius/biz/jobs/batch/file/XMLValidator.java
  src/main/java/sirius/biz/process/ProcessContext.java
  src/main/java/sirius/biz/process/logs/ProcessLog.java
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
Labels:  💣 BREAKING CHANGE

#1217 Improves how validLanguages for a MultiLanguageString are determined + helper methods for BizController
  pom.xml
  src/main/java/sirius/biz/translations/MultiLanguageString.java
  src/main/java/sirius/biz/translations/MultiLanguageStringProperty.java
  src/main/java/sirius/biz/web/BizController.java
  src/main/resources/default/taglib/t/multiLanguageTextArea.html.pasta
  src/main/resources/default/taglib/t/multiLanguageTextField.html.pasta
  src/main/resources/default/taglib/w/multiLanguageTextArea.html.pasta
  src/main/resources/default/taglib/w/multiLanguageTextField.html.pasta
  src/test/java/sirius/biz/translations/MongoMultiLanguageStringComposite.java
  src/test/java/sirius/biz/translations/MongoMultiLanguageStringEntity.java
  src/test/java/sirius/biz/translations/MongoMultiLanguageStringMixin.java
  src/test/java/sirius/biz/translations/MongoMultiLanguageStringRequiredNoFallbackEntity.java
Labels: 🧬 Enhancement,  💣 BREAKING CHANGE

#1222 fix a bunch of typos
  src/main/java/sirius/biz/analytics/events/Event.java
  src/main/java/sirius/biz/jobs/batch/file/XMLValidator.java
  src/main/java/sirius/biz/jobs/params/LocalDateParameter.java
  src/main/java/sirius/biz/jobs/scheduler/JobSchedulerLoop.java
  src/main/java/sirius/biz/protocol/CleanupProtocolsTask.java
  src/main/java/sirius/biz/protocol/JournalData.java
  src/main/java/sirius/biz/protocol/JournalEntry.java
  src/main/java/sirius/biz/protocol/StoredIncident.java
  src/main/java/sirius/biz/protocol/TraceData.java
  src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLDirectory.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLVariant.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoDirectory.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoVariant.java
  src/main/java/sirius/biz/storage/layer3/uplink/ConfigBasedUplinksRoot.java
  src/main/java/sirius/biz/storage/layer3/uplink/cifs/CIFSUplink.java
  src/main/java/sirius/biz/storage/legacy/Storage.java
  src/main/java/sirius/biz/storage/util/StorageUtils.java
  src/main/java/sirius/biz/util/SevenZipAdapter.java
  src/main/resources/biz_en.properties
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1221 Uses new tokenautocomplete function
  src/main/resources/default/taglib/t/lookupValues.html.pasta
Labels: 🕔 Wait on sirius

#1220 Enhances the ErrorContext
  pom.xml
  src/main/java/sirius/biz/importer/BaseImportHandler.java
  src/main/java/sirius/biz/importer/MongoEntityImportHandler.java
  src/main/java/sirius/biz/importer/SQLEntityImportHandler.java
  src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedImport.java
  src/main/java/sirius/biz/jobs/batch/file/EntityExportJob.java
  src/main/java/sirius/biz/process/ErrorContext.java
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
Labels: 🧬 Enhancement, 🖐 Keep open,  💣 BREAKING CHANGE

#1224 Provides a bunch of fixes and improvements for the storage system, its conversion and esp. file delivery.
  src/main/java/sirius/biz/elastic/AutoBatchLoop.java
  src/main/java/sirius/biz/jobs/scheduler/SchedulerController.java
  src/main/java/sirius/biz/process/ExportLogsAsFileTaskExecutor.java
  src/main/java/sirius/biz/process/ProcessContext.java
  src/main/java/sirius/biz/process/ProcessEnvironment.java
  src/main/java/sirius/biz/process/Processes.java
  src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/BlobDispatcher.java
  src/main/java/sirius/biz/storage/layer2/BlobHardRef.java
  src/main/java/sirius/biz/storage/layer2/BlobSoftRef.java
  src/main/java/sirius/biz/storage/layer2/L3Uplink.java
  src/main/java/sirius/biz/storage/layer2/URLBuilder.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLVariant.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoVariant.java
  src/main/java/sirius/biz/storage/layer2/variants/BlobConversionEvent.java
  src/main/java/sirius/biz/storage/layer2/variants/BlobVariant.java
  src/main/java/sirius/biz/storage/layer2/variants/ConversionEngine.java
  src/main/java/sirius/biz/storage/layer2/variants/ConversionEvent.java
  src/main/java/sirius/biz/storage/layer2/variants/ConversionProcess.java
  src/main/java/sirius/biz/storage/layer2/variants/Converter.java
  src/main/java/sirius/biz/storage/layer3/VFSController.java
  src/main/java/sirius/biz/tycho/academy/mongo/MongoOnboardingVideo.java
  src/main/java/sirius/biz/web/BizController.java
  src/main/resources/biz_de.properties
  src/main/resources/component-biz.conf
  src/main/resources/default/assets/images/blob_image_fallback.png
  src/main/resources/default/extensions/tycho-page-menu/footer.html.pasta
  src/main/resources/default/extensions/wondergem-page-menu/footer.html.pasta
  src/main/resources/default/taglib/t/lookupValue.html.pasta
Labels:  💣 BREAKING CHANGE

#1225 Minor fixes found in a testing session.
  src/main/java/sirius/biz/process/Processes.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLVariant.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoVariant.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1229 Allows a job to override the ImportMode parameter
  src/main/java/sirius/biz/jobs/batch/file/EntityImportJobFactory.java
Labels: 👶🏻 Trivial

#1230 Provides a job parameter for LookupTables and improves the processes UI a bit.
  src/main/java/sirius/biz/codelists/LookupTableParameter.java
  src/main/java/sirius/biz/jobs/params/Parameter.java
  src/main/java/sirius/biz/translations/MultiLanguageStringHelper.java
  src/main/resources/default/templates/biz/jobs/params/lookuptable.html.pasta
  src/main/resources/default/templates/biz/process/process-logs.html.pasta
Labels: 🧬 Enhancement

#1231 Remove unnecessary defaultRoles
  src/main/resources/component-biz.conf
Labels: 👶🏻 Trivial

#1232 Fixes the cross-reference list of a KnowledgeBaseArticle.
  pom.xml
  src/main/java/sirius/biz/jobs/batch/entity/EntityBatchJob.java
  src/main/java/sirius/biz/jobs/batch/file/EntityExportJob.java
  src/main/java/sirius/biz/jupiter/IDBTable.java
  src/main/java/sirius/biz/model/ResaveEntitiesJobFactory.java
  src/main/java/sirius/biz/tycho/kb/SynchronizeArticlesTask.java
Labels: 🐛 Bugfix

#1233 Add new permissions to wondergem templates
  src/main/resources/default/extensions/biz-menu/menu-jobs.html.pasta
  src/main/resources/default/extensions/biz-menu/menu-protcols.html.pasta
  src/main/resources/default/extensions/biz-menu/menu-vfs.html.pasta
  src/main/resources/default/extensions/wondergem-page-menu/menu.html.pasta
Labels: 👶🏻 Trivial

#1234 Correctly prepares unchecked checkboxes for transform
  src/main/java/sirius/biz/web/BizController.java
Labels: 🐛 Bugfix

#1236 Verifies file extension to detect if a "real" file is present or "just" a server-sided script.
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
  src/main/resources/component-biz.conf
Labels: 🧬 Enhancement

#1239 Improves optional file logging in archive imports
  src/main/java/sirius/biz/jobs/batch/file/ArchiveImportJob.java
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
Labels: 👶🏻 Trivial

#1238 Provides misc fixes for testing feedback.
  src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/URLBuilder.java
  src/main/java/sirius/biz/tycho/DashboardController.java
  src/main/resources/default/taglib/t/jobs.html.pasta
Labels: 🐛 Bugfix

#1241 Prevents duplicate logging of successful downloads
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1242 Allows to delete temporary files
  src/main/java/sirius/biz/storage/layer3/TmpRoot.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1243 Allows the browser to break long process log messages if necessary
  src/main/resources/default/templates/biz/process/process-logs.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1244 Fixes the alignment of process logs after the last fix
  src/main/resources/default/templates/biz/process/process-logs.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1245 Custom and filtered lookup tables now fall back to title and description of their base table
  src/main/java/sirius/biz/codelists/CustomLookupTable.java
  src/main/java/sirius/biz/codelists/IDBFilteredLookupTable.java
Labels: 👶🏻 Trivial

#1246 Adds titles for lookup tables
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
Labels: 👶🏻 Trivial

#1247 Keeps intentional line breaks in log messages intact
  pom.xml
  src/main/resources/default/templates/biz/process/process-logs.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial, 🕔 Wait on sirius

#1248 Ensures that uncompleted/failed variants are deleted
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1249 Also removes failed variants from cache after delete
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLVariant.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoVariant.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1250 Bugfix: Only applies empty checkbox marker for boolean properties
  src/main/java/sirius/biz/web/BizController.java
Labels: 🐛 Bugfix, 🔥 Hotfix
