Repository scireum/sirius-biz, pull requests merged in 2021-07, with the labels that each got.

#1130 Removes a obsolete method, and moves it replacement
  src/main/java/sirius/biz/codelists/LookupTableEntry.java
  src/main/java/sirius/biz/codelists/LookupValueSuggestionController.java
Labels: 👶🏻 Trivial

#1131 Uses java 9 Optional::stream method
  src/main/java/sirius/biz/tycho/kb/KnowledgeBase.java
Labels: 👶🏻 Trivial

#1132 Only enables the knowledge base search provider when framework is active
  src/main/java/sirius/biz/tycho/kb/KnowledgeBaseSearchProvider.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1133 Forwards readonly parameter to token lib
  src/main/resources/default/taglib/w/lookupValue.html.pasta
  src/main/resources/default/taglib/w/lookupValues.html.pasta
Labels: 🐛 Bugfix

#1135 Prevents an UnsupportedOperationException in the MultiLanguageStringExtender
  src/main/java/sirius/biz/translations/MultiLanguageStringExtender.java
  src/main/java/sirius/biz/translations/MultiLanguageStringHelper.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1138 Bugfix: Avoid false-positive SQL warning on a clickhouse evaluation
  src/main/java/sirius/biz/analytics/events/ClickhouseSizeChartJobFactory.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1139 add reported missing translation
  src/main/resources/biz_de.properties
Labels: 👶🏻 Trivial

#1140 Fixes calls to Blob.getFilename / Blob.getPath after updating the blob contents without providing a file name
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java
Labels: 🐛 Bugfix

#1142 Adds a way to retrieve all entries matching a lookup of idb tables
  src/main/java/sirius/biz/codelists/CodeListLookupTable.java
  src/main/java/sirius/biz/codelists/CustomLookupTable.java
  src/main/java/sirius/biz/codelists/IDBFilteredLookupTable.java
  src/main/java/sirius/biz/codelists/IDBLookupTable.java
  src/main/java/sirius/biz/codelists/LookupTable.java
Labels: 🧬 Enhancement

#1149 fix startup warning by adding a nullable annotation
  src/main/java/sirius/biz/tycho/academy/jdbc/SQLOnboardingVideo.java
  src/main/java/sirius/biz/tycho/academy/mongo/MongoOnboardingVideo.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1148 Enhances the ErrorContext
  src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedArchiveImportJob.java
  src/main/java/sirius/biz/jobs/batch/file/FileImportJob.java
  src/main/java/sirius/biz/process/ErrorContext.java
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
Labels: 🧬 Enhancement

#1151 Fixes non HandledException to log the context twice
  src/main/java/sirius/biz/process/ErrorContext.java
Labels: 👶🏻 Trivial

#1154 Adds a performAndGet which invokes a producer
  src/main/java/sirius/biz/process/ErrorContext.java
Labels: 🧬 Enhancement

#1161 Makes the currentUserName() macro non-constant (for obvious reasons).
  src/main/java/sirius/biz/web/CurrentUserNameMacro.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1162 Renames method to better reflect what it does
  src/main/java/sirius/biz/storage/layer2/ProcessBlobChangesLoop.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLProcessBlobChangesLoop.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoProcessBlobChangesLoop.java
Labels:  💣 BREAKING CHANGE, 👶🏻 Trivial

#1167 Correctly applies content disposition set by BlobDispatcher
  src/main/java/sirius/biz/storage/layer1/S3ObjectStorageSpace.java
Labels: 🐛 Bugfix

#1170 Includes line number in relational import errors and wont auto import transaction ID
  src/main/java/sirius/biz/importer/txn/ImportTransactionData.java
  src/main/java/sirius/biz/jobs/batch/file/RelationalEntityImportJob.java
Labels: 🐛 Bugfix, 👶🏻 Trivial, 🧬 Enhancement

#1171 Hides fields from the documentation without removing them from the im…
  src/main/java/sirius/biz/importer/BaseImportHandler.java
  src/main/java/sirius/biz/importer/format/BaseFieldDefinitionTransformer.java
  src/main/java/sirius/biz/importer/format/FieldDefinition.java
  src/main/java/sirius/biz/importer/format/ImportDictionary.java
Labels: 🐛 Bugfix, 🔥 Hotfix

#1165 Make BasicJobFactory#checkPermissions final
  src/main/java/sirius/biz/jobs/BasicJobFactory.java
  src/main/java/sirius/biz/tenants/jdbc/SQLUserAccountExportJobFactory.java
  src/main/java/sirius/biz/tenants/jdbc/SQLUserAccountImportJobFactory.java
  src/main/java/sirius/biz/tenants/mongo/MongoUserAccountExportJobFactory.java
  src/main/java/sirius/biz/tenants/mongo/MongoUserAccountImportJobFactory.java
Labels:  💣 BREAKING CHANGE

#1173 Properly clears the transaction id for failed replication tasks.
  src/main/java/sirius/biz/storage/layer1/replication/jdbc/SQLReplicationTaskStorage.java
  src/main/java/sirius/biz/storage/layer1/replication/mongo/MongoReplicationTaskStorage.java
Labels: 🐛 Bugfix

#1174 Aligns the language icon and name for t:lang and provides a tooltip.
  src/main/resources/default/taglib/t/lang.html.pasta
  src/main/resources/default/taglib/t/langFlag.html.pasta
Labels: 👶🏻 Trivial

#1175 No longer removes hidden AutoImport fields from the import.
  src/main/java/sirius/biz/importer/BaseImportHandler.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1157 Defaults to the base table's code case for filtered and custom lookup tables
  src/main/java/sirius/biz/codelists/CustomLookupTable.java
  src/main/java/sirius/biz/codelists/IDBFilteredLookupTable.java
  src/main/java/sirius/biz/codelists/LookupTable.java
  src/main/java/sirius/biz/codelists/LookupTables.java
  src/main/resources/component-biz.conf
Labels:  💣 BREAKING CHANGE

#1169 extend wondergem footer for support-links, always redirect to given link
  develop.conf
  pom.xml
  src/main/java/sirius/biz/tenants/TenantController.java
  src/main/resources/default/extensions/wondergem-page-menu/footer.html.pasta
Labels: 🧬 Enhancement

#1177 Ports /system/scripting to Tycho and removes the "hard" handling of "/".
  pom.xml
  src/main/java/sirius/biz/ide/ScriptingController.java
  src/main/java/sirius/biz/tycho/DashboardController.java
  src/main/resources/component-biz.conf
  src/main/resources/default/extensions/biz-menu/menu-system-tenant.html.pasta
  src/main/resources/default/extensions/biz-tycho-menu/menu-system-tenant.html.pasta
  src/main/resources/default/templates/biz/ide/scripting.html.pasta
  src/main/resources/default/templates/biz/tycho/dashboard.html.pasta
Labels: 🧬 Enhancement
