Repository scireum/sirius-biz, pull requests merged in 2021-05, with the labels that each got.

#1071 Move complexity out of FileImportJob into a designated class.
  src/main/java/sirius/biz/codelists/IDBLookupTable.java
  src/main/java/sirius/biz/jobs/batch/file/ArchiveImportJob.java
  src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedArchiveImportJob.java
  src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedImport.java
  src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedImportJob.java
  src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedImportJobFactory.java
  src/main/java/sirius/biz/jobs/batch/file/EntityExportJob.java
  src/main/java/sirius/biz/jobs/batch/file/FileImportJob.java
  src/main/java/sirius/biz/util/ExtractedZipFile.java
  src/main/resources/biz_de.properties
Labels:  💣 BREAKING CHANGE, 🧬 Enhancement

#1073 Adds a method for post processing purposes
  src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedArchiveImportJob.java
Labels: 👶🏻 Trivial

#1074 Fixes error messages for import jobs.
  src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedImport.java
  src/main/java/sirius/biz/jobs/batch/file/EntityExportJob.java
  src/main/java/sirius/biz/process/logs/ProcessLog.java
  src/main/resources/biz_de.properties
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1075 Passes missing context to error message
  src/main/java/sirius/biz/jobs/batch/file/FileImportJob.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1076 Permit an empty search in IDBTables.
  src/main/java/sirius/biz/jupiter/IDBTable.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1077 Initializes variables
  src/main/java/sirius/biz/jobs/batch/file/ArchiveImportJob.java
Labels: 🐛 Bugfix

#1078 Add a method to fetch a field as a boolean
  src/main/java/sirius/biz/codelists/LookupTable.java
Labels: 🧬 Enhancement

#1079 Fixes the fetching of boolean fields if the internal value is a long
  src/main/java/sirius/biz/codelists/LookupTable.java
Labels: 🐛 Bugfix

#1080 do not log a warning if ssh is started successfully
  src/main/java/sirius/biz/storage/layer3/downlink/ssh/SSHServer.java
Labels: 👶🏻 Trivial

#1082 Add NLS keys for Iceland
  src/main/resources/biz_bg.properties
  src/main/resources/biz_cs.properties
  src/main/resources/biz_da.properties
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
  src/main/resources/biz_es.properties
  src/main/resources/biz_fr.properties
  src/main/resources/biz_hu.properties
  src/main/resources/biz_it.properties
  src/main/resources/biz_nl.properties
  src/main/resources/biz_pl.properties
  src/main/resources/biz_ro.properties
  src/main/resources/biz_ru.properties
  src/main/resources/biz_se.properties
  src/main/resources/biz_sk.properties
  src/main/resources/biz_sv.properties
Labels: 👶🏻 Trivial

#1081 Prohibit a queue for process side tasks.
  src/main/resources/component-biz.conf
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1087 Automatically builds changed/deleted messages
  src/main/java/sirius/biz/protocol/DelegateJournalData.java
Labels: 🧬 Enhancement

#1090 Simplify the parsing of complex properties inside Import Handlers
  src/main/java/sirius/biz/importer/BaseImportHandler.java
Labels: Hotfix, 🐛 Bugfix

#1091 Update sirius
  pom.xml
Labels: Hotfix, dependencies, 👶🏻 Trivial

#1094 Dont create a journal entry when nothing changed
  src/main/java/sirius/biz/protocol/DelegateJournalData.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1096 Makes the process counters more readable
  src/main/java/sirius/biz/process/Process.java
Labels: 👶🏻 Trivial, 🧬 Enhancement

#1097 Exposes the default lookup table names for languages
  src/main/java/sirius/biz/util/Languages.java
Labels: 👶🏻 Trivial

#1099 Tenants.(run)AsAdmin gives all permissions and can specify a tenant now
  pom.xml
  src/main/java/sirius/biz/tenants/Tenants.java
Labels: 🧬 Enhancement
