Repository scireum/sirius-biz, pull requests merged in 2021-02, with the labels that each got.

#974 do not index the login page for search engines
  pom.xml
  src/main/resources/default/templates/biz/login.html.pasta
Labels: 👶🏻 Trivial, 🧬 Enhancement

#979 Minor Fixes for Jupiter and the ReportMissingNLSKeysJob.
  src/main/java/sirius/biz/cluster/InterconnectClusterManager.java
  src/main/java/sirius/biz/jupiter/Jupiter.java
  src/main/java/sirius/biz/util/ReportUnusedNLSKeysJob.java
  src/main/resources/component-biz.conf
Labels: 🐛 Bugfix

#984 Allows IE11 to display globe symbol correctly
  pom.xml
  src/main/resources/default/assets/images/flags/globe.png
  src/main/resources/default/assets/javascript/multiLanguageField.js
  src/main/resources/default/assets/stylesheets/biz.scss
Labels: 🐛 Bugfix, 👶🏻 Trivial

#985 Fix the vfs modal when querying big directories
  src/main/java/sirius/biz/storage/layer3/VFSController.java
Labels: 🐛 Bugfix

#987 SIRI-315 Prevent lookups in too many entities when a blob is deleted
  src/main/java/sirius/biz/storage/layer2/BlobSoftRefProperty.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java
Labels: 🐛 Bugfix

#989 Bump to the latest sirius-web
  pom.xml
Labels: dependencies

#994 Displays the node state infos sorted by node name
  src/main/java/sirius/biz/cluster/InterconnectClusterManager.java
Labels: 👶🏻 Trivial

#997 Update to the latest sirius dependencies
  pom.xml
Labels: dependencies,  💣 BREAKING CHANGE

#1000 Updates to the latest sirius dependencies
  pom.xml
Labels: dependencies, 🧬 Enhancement

#1002 Fixes handling of FieldDefinition aliases with non-latin alphabet
  src/main/java/sirius/biz/importer/format/FieldDefinition.java
  src/main/java/sirius/biz/importer/format/ImportDictionary.java
Labels: 🐛 Bugfix

#1004 Fixes broken field error markings and uses the right method to add an…
  src/main/java/sirius/biz/web/BizController.java
Labels: 🐛 Bugfix, 👶🏻 Trivial
