Repository scireum/sirius-biz, pull requests merged in 2021-03, with the labels that each got.

#1009 Passes database parameter correctly when executing query
  src/main/resources/default/templates/biz/model/sql.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1010 Corrects NLS property name to actually see the progress while the ext…
  src/main/java/sirius/biz/storage/layer3/ExtractArchiveJob.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1008 Adds a method to VirtualFile to resolve a path from a url and directly download the url into the path
  pom.xml
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
  src/main/resources/biz_de.properties
Labels: 🕔 Wait on sirius

#1012 Prevents startup warning by passing framework in register annot
  src/main/java/sirius/biz/storage/layer1/replication/ForceReplicationJob.java
Labels: 👶🏻 Trivial

#1016 S3 Ninja Upgrade (SIRI-299)
  docker-compose.yml
  src/test/resources/docker-compose.yml
Labels: 👶🏻 Trivial

#1015 Multilanguage field modal: Adjusts the height of the modal and the language options
  src/main/resources/default/assets/javascript/multiLanguageField.js
  src/main/resources/default/assets/stylesheets/multiLanguageField.scss
Labels: 👶🏻 Trivial

#1018 Fix broken executions of /system/sql
  src/main/resources/default/templates/biz/model/sql.html.pasta
Labels: 👶🏻 Trivial

#1019 fix missing NLS-keys
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
Labels: 👶🏻 Trivial

#1023 Prevents error when transforming force failed query to page
  src/main/java/sirius/biz/web/MongoPageHelper.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1022 VFS Modal Bugfixing
  src/main/resources/default/extensions/wondergem-page/storage-vfs-modals.html.pasta
Labels: 🐛 Bugfix

#1024 Refactors MultiLanguageString, CodeLists and removes a deprecated framework.
  src/main/java/sirius/biz/codelists/CodeListController.java
  src/main/java/sirius/biz/codelists/CodeListData.java
  src/main/java/sirius/biz/codelists/CodeListEntry.java
  src/main/java/sirius/biz/codelists/CodeListEntryData.java
  src/main/java/sirius/biz/codelists/CodeLists.java
  src/main/java/sirius/biz/codelists/jdbc/SQLCodeListController.java
  src/main/java/sirius/biz/codelists/jdbc/SQLCodeListEntry.java
  src/main/java/sirius/biz/codelists/mongo/MongoCodeListController.java
  src/main/java/sirius/biz/codelists/mongo/MongoCodeListEntry.java
  src/main/java/sirius/biz/jobs/params/CodeListEntryParameter.java
  src/main/java/sirius/biz/tenants/jdbc/SQLUserAccountImportHandler.java
  src/main/java/sirius/biz/tenants/mongo/MongoUserAccountImportHandler.java
  src/main/java/sirius/biz/translations/BasicTranslations.java
  src/main/java/sirius/biz/translations/MultiLanguageString.java
  src/main/java/sirius/biz/translations/MultiLanguageStringProperty.java
  src/main/java/sirius/biz/translations/Translatable.java
  src/main/java/sirius/biz/translations/Translation.java
  src/main/java/sirius/biz/translations/TranslationData.java
  src/main/java/sirius/biz/translations/jdbc/SQLTranslation.java
  src/main/java/sirius/biz/translations/jdbc/SQLTranslations.java
  src/main/java/sirius/biz/translations/mongo/MongoTranslation.java
  src/main/java/sirius/biz/translations/mongo/MongoTranslations.java
  src/main/java/sirius/biz/web/SaveHelper.java
  src/main/resources/biz_de.properties
  src/main/resources/component-biz.conf
  src/main/resources/default/taglib/w/codelistMultiSelect.html.pasta
  src/main/resources/default/taglib/w/codelistSelect.html.pasta
  src/main/resources/default/taglib/w/multiLanguageTextArea.html.pasta
  src/main/resources/default/taglib/w/multiLanguageTextField.html.pasta
  src/main/resources/default/templates/biz/codelists/code-list-entries.html.pasta
  src/main/resources/default/templates/biz/codelists/code-list-entry.html.pasta
  src/main/resources/default/templates/biz/codelists/code-list.html.pasta
  src/main/resources/default/templates/biz/jobs/params/codelistentry.html.pasta
  src/test/java/sirius/biz/codelists/CodeListsSpec.groovy
  src/test/java/sirius/biz/tenants/TenantsHelper.java
  src/test/java/sirius/biz/translations/MongoMultiLanguageStringPropertySpec.groovy
  src/test/java/sirius/biz/translations/MongoTranslatable.java
  src/test/java/sirius/biz/translations/MongoTranslationsSpec.groovy
  src/test/java/sirius/biz/translations/SQLMultiLanguageStringEntity.java
  src/test/java/sirius/biz/translations/SQLMultiLanguageStringPropertySpec.groovy
  src/test/java/sirius/biz/translations/SQLTranslatable.java
  src/test/java/sirius/biz/translations/SQLTranslationsSpec.groovy
  src/test/java/sirius/biz/translations/TranslationsSpec.groovy
Labels:  💣 BREAKING CHANGE, 🧬 Enhancement

#1025 Outputs the translated value for CodeListEntries again
  src/main/java/sirius/biz/translations/MultiLanguageStringProperty.java
  src/main/resources/default/taglib/w/codelistMultiSelect.html.pasta
  src/main/resources/default/taglib/w/codelistSelect.html.pasta
  src/main/resources/default/templates/biz/jobs/params/codelistentry.html.pasta
Labels: 👶🏻 Trivial

#1030 Allow duplicate file names over FTP & Support UTF-8 file names in FTP uplinks
  src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplink.java
  src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplinkConnectorConfig.java
  src/main/resources/component-biz.conf
Labels: 🐛 Bugfix, 🧬 Enhancement

#1033 Update to the latest sirius-db
  pom.xml
Labels: dependencies

#1034 Adds missing texts
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
Labels: 👶🏻 Trivial

#1037 Fixes context and language initialization
  src/main/java/sirius/biz/cluster/work/DistributedTasks.java
  src/main/java/sirius/biz/cluster/work/WorkLoaderLoop.java
  src/main/java/sirius/biz/process/Processes.java
  src/main/resources/component-biz.conf
Labels: 🐛 Bugfix

#1028 Fixes Im- and Export of CodeLists
  src/main/java/sirius/biz/codelists/jdbc/SQLCodeListEntryImportHandler.java
  src/main/java/sirius/biz/codelists/jdbc/SQLCodeListExportJobFactory.java
  src/main/java/sirius/biz/codelists/jdbc/SQLCodeListImportJobFactory.java
  src/main/java/sirius/biz/codelists/mongo/MongoCodeListEntryImportHandler.java
  src/main/java/sirius/biz/codelists/mongo/MongoCodeListExportJobFactory.java
  src/main/java/sirius/biz/codelists/mongo/MongoCodeListImportJobFactory.java
  src/main/java/sirius/biz/translations/MultiLanguageString.java
  src/main/java/sirius/biz/translations/MultiLanguageStringProperty.java
Labels: 🐛 Bugfix

#1040 Actually sets the supplied name for the regular text field
  src/main/resources/default/taglib/w/multiLanguageTextArea.html.pasta
  src/main/resources/default/taglib/w/multiLanguageTextField.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1041 BREAKING: Changes the index settings for AuditLogEntries for deduplic…
  src/main/java/sirius/biz/protocol/AuditLogEntry.java
Labels:  💣 BREAKING CHANGE, 🐛 Bugfix

#1039 Ensure unrouted queries when resaving ES entities
  src/main/java/sirius/biz/model/ResaveEntitiesJobFactory.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1042 Translates Country.us into the short form uniformly for all languages.
  src/main/resources/biz_cs.properties
  src/main/resources/biz_fr.properties
  src/main/resources/biz_ro.properties
  src/main/resources/biz_sk.properties
Labels: 👶🏻 Trivial

#1046 Fixes a resource leak when exracting large files from a 7-zip archive.
  src/main/java/sirius/biz/util/ExtractedFileBuffer.java
  src/main/java/sirius/biz/util/LocalArchiveExtractCallback.java
  src/main/java/sirius/biz/util/SevenZipAdapter.java
Labels: 🐛 Bugfix

#1045 Provides an async download API, a DownloadManager and a ZipBuilder for the storage framework.
  src/main/java/sirius/biz/storage/layer1/DownloadManager.java
  src/main/java/sirius/biz/storage/layer1/FSObjectStorageSpace.java
  src/main/java/sirius/biz/storage/layer1/ObjectStorageSpace.java
  src/main/java/sirius/biz/storage/layer1/S3ObjectStorageSpace.java
  src/main/java/sirius/biz/storage/s3/ObjectStore.java
  src/main/java/sirius/biz/util/ZipBuilder.java
Labels: 🧬 Enhancement

#1044 Improves the API of ProcessContext and updates to the latest sirius-kernel.
  pom.xml
  src/main/java/sirius/biz/ide/JobTaskContextAdapter.java
  src/main/java/sirius/biz/jupiter/JupiterSync.java
  src/main/java/sirius/biz/process/ExportLogsAsFileTaskExecutor.java
  src/main/java/sirius/biz/process/ProcessContext.java
  src/main/java/sirius/biz/process/ProcessEnvironment.java
  src/main/java/sirius/biz/process/Processes.java
  src/main/java/sirius/biz/storage/layer3/ExtractArchiveJob.java
  src/main/java/sirius/biz/storage/s3/ObjectStore.java
  src/main/java/sirius/biz/tycho/search/OpenSearchController.java
  src/main/resources/biz_de.properties
  src/main/resources/component-biz.conf
Labels: 🕔 Wait on sirius, 🧬 Enhancement
