Repository scireum/sirius-biz, pull requests merged in 2021-11, with the labels that each got.

#1287 Allows to mark a process output as system output
  src/main/java/sirius/biz/process/Process.java
  src/main/java/sirius/biz/process/ProcessController.java
  src/main/java/sirius/biz/process/output/ProcessOutput.java
  src/main/resources/default/templates/biz/process/process.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1291 Fix typo in requestSubmitForm at sql export
  src/main/resources/default/templates/biz/model/sql.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1290 Removes annotation to make pre-authorized articles accessible (and not all without an authKey)
  src/main/java/sirius/biz/tycho/kb/KnowledgeBaseController.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1296 Adjust path error message and category if DL is disabled
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
  src/main/resources/biz_de.properties
Labels: 👶🏻 Trivial

#1298 Allows to intercept before/after deletion of tenant aware entities
  src/main/java/sirius/biz/codelists/jdbc/DeleteSQLCodeListsTask.java
  src/main/java/sirius/biz/codelists/mongo/DeleteMongoCodeListsTask.java
  src/main/java/sirius/biz/jobs/presets/jdbc/DeleteSQLJobPresetsTask.java
  src/main/java/sirius/biz/jobs/presets/mongo/DeleteMongoJobPresetsTask.java
  src/main/java/sirius/biz/jobs/scheduler/jdbc/DeleteSQLSchedulerEntriesTask.java
  src/main/java/sirius/biz/jobs/scheduler/mongo/DeleteMongoSchedulerEntriesTask.java
  src/main/java/sirius/biz/tenants/jdbc/DeleteSQLEntitiesTask.java
  src/main/java/sirius/biz/tenants/jdbc/DeleteSQLUserAccountsTask.java
  src/main/java/sirius/biz/tenants/mongo/DeleteMongoEntitiesTask.java
  src/main/java/sirius/biz/tenants/mongo/DeleteMongoUserAccountTask.java
Labels: 🧬 Enhancement, 👶🏻 Trivial,  💣 BREAKING CHANGE

#1302 Update jcifs dependency 2.1.11 -> 2.1.27
  pom.xml
Labels: 👶🏻 Trivial

#1305 Fixes errors with unpacking archives using 7ZIP
  src/main/java/sirius/biz/storage/layer3/ExtractArchiveJob.java
  src/main/java/sirius/biz/util/SevenZipAdapter.java
Labels: 🐛 Bugfix

#1313 ErrorContext: Retains message key and count hints, if a handled exception was annotated
  src/main/java/sirius/biz/process/ErrorContext.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1314 Fixes the w:blobSoftRefField taglib
  src/main/resources/default/assets/javascript/blobreffield.js
Labels: 🐛 Bugfix, 🔥 Hotfix

#1315 Adds a tycho tag for hardRefFields for images
  pom.xml
  src/main/java/sirius/biz/storage/layer2/BlobController.java
  src/main/resources/default/taglib/t/blobImageHardRefField.html.pasta
Labels: 🕔 Wait on sirius
