Repository scireum/sirius-biz, pull requests merged in 2021-10, with the labels that each got.

#1253 Fixes the class of a toggle link to match the JS code.
  src/main/resources/default/assets/scripts/lookupTables.js
Labels: 👶🏻 Trivial

#1252 Permits for longe titles in complex delete jobs and updates to the latest MongoDB.
  docker-compose.yml
  src/main/java/sirius/biz/web/BizController.java
  src/test/resources/docker-compose.yml
Labels: 👶🏻 Trivial

#1257 Properly handles exceptions so that we do not loose stacktraces.
  src/main/java/sirius/biz/model/ResaveEntitiesJobFactory.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1258 Moves SortField / SortValue from sirius-db.
  src/main/java/sirius/biz/mongo/CustomSortValues.java
  src/main/java/sirius/biz/mongo/SortField.java
  src/main/java/sirius/biz/mongo/SortValue.java
Labels: 👶🏻 Trivial

#1264 Validates missing fallback text for multi-language strings
  pom.xml
  src/main/java/sirius/biz/translations/MultiLanguageStringProperty.java
Labels: 🧬 Enhancement, 🕔 Wait on sirius

#1268 Limits the frequency in which VirtualFiles are downloaded from URLs & Enhances the options for Jupiter Sync.
  src/main/java/sirius/biz/jupiter/JupiterSync.java
  src/main/java/sirius/biz/storage/layer2/L3Uplink.java
  src/main/java/sirius/biz/storage/layer3/ExtractArchiveJob.java
  src/main/java/sirius/biz/storage/layer3/MutableVirtualFile.java
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
  src/main/resources/component-biz.conf
Labels: 🧬 Enhancement
