Repository scireum/sirius-biz, pull requests merged in 2021-08, with the labels that each got.

#1179 Provides a clickable administrator link to the query tool in journal entries.
  src/main/java/sirius/biz/protocol/JournalEntry.java
  src/main/resources/default/templates/biz/protocol/protocol.html.pasta
Labels: 🧬 Enhancement

#1183 Ensures that language keys in MultiLanguageStrings cannot be empty
  src/main/java/sirius/biz/translations/MultiLanguageString.java
  src/test/java/sirius/biz/translations/MultiLanguageStringSpec.groovy
Labels:  💣 BREAKING CHANGE

#1186 Upgrade apache sshd lib and fix SFTP read error
  pom.xml
  src/main/java/sirius/biz/storage/layer3/downlink/ssh/SSHServer.java
  src/main/java/sirius/biz/storage/layer3/downlink/ssh/scp/BridgeScpCommand.java
  src/main/java/sirius/biz/storage/layer3/downlink/ssh/scp/BridgeScpCommandFactory.java
  src/main/java/sirius/biz/storage/layer3/downlink/ssh/scp/BridgeScpFileOpener.java
  src/main/java/sirius/biz/storage/layer3/downlink/ssh/scp/BridgeScpSourceStreamResolver.java
  src/main/java/sirius/biz/storage/layer3/downlink/ssh/scp/BridgeScpTargetStreamResolver.java
  src/main/java/sirius/biz/storage/layer3/downlink/ssh/sftp/BridgeFileSystemAccessor.java
  src/main/java/sirius/biz/storage/layer3/downlink/ssh/sftp/BridgeSeekableByteChannel.java
  src/main/java/sirius/biz/storage/layer3/downlink/ssh/sftp/BridgeSftpSubsystem.java
  src/main/java/sirius/biz/storage/layer3/downlink/ssh/sftp/BridgeSftpSubsystemFactory.java
  src/main/java/sirius/biz/storage/layer3/uplink/sftp/SFTPUplink.java
  src/main/java/sirius/biz/storage/layer3/uplink/sftp/SFTPUplinkConnectorConfig.java
Labels:  💣 BREAKING CHANGE

#1187 Provides a value selection and "view lookup table" modal.
  docker-compose.yml
  pom.xml
  src/main/java/sirius/biz/codelists/CodeListLookupTable.java
  src/main/java/sirius/biz/codelists/CustomLookupTable.java
  src/main/java/sirius/biz/codelists/IDBFilteredLookupTable.java
  src/main/java/sirius/biz/codelists/IDBLookupTable.java
  src/main/java/sirius/biz/codelists/LookupTable.java
  src/main/java/sirius/biz/codelists/LookupTableController.java
  src/main/java/sirius/biz/codelists/LookupTableEntry.java
  src/main/java/sirius/biz/codelists/LookupTableMessageExpander.java
  src/main/java/sirius/biz/codelists/LookupValueSuggestionController.java
  src/main/java/sirius/biz/jupiter/IDBSet.java
  src/main/java/sirius/biz/jupiter/IDBTable.java
  src/main/resources/biz_de.properties
  src/main/resources/default/assets/scripts/lookupTables.js
  src/main/resources/default/assets/scripts/tycho-biz.js.pasta
  src/main/resources/default/extensions/biz-tycho-menu/menu-system-tenant.html.pasta
  src/main/resources/default/extensions/tycho-page/lookupTables.html.pasta
  src/main/resources/default/taglib/t/lookupValue.html.pasta
  src/main/resources/default/taglib/t/lookupValues.html.pasta
  src/main/resources/default/taglib/w/lookupValue.html.pasta
  src/main/resources/default/taglib/w/lookupValues.html.pasta
  src/main/resources/default/templates/biz/ide/scripting.html.pasta
Labels: 🧬 Enhancement

#1189 Fix missing entity details on system/sql for only one result
  src/main/resources/default/templates/biz/model/sql.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1191 Correctly translates entries from a SelectStringParameter
  src/main/java/sirius/biz/jobs/params/SelectStringParameter.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1190 Marks the txnId with AutoImport
  src/main/java/sirius/biz/importer/txn/ImportTransactionData.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1195 Differentiation between deletion of files and whole directories
  src/main/java/sirius/biz/storage/layer3/uplink/fs/LocalDirectoryUplink.java
Labels: 👶🏻 Trivial

#1197 Permits to enable the system maintenance mode by default.
  src/main/java/sirius/biz/web/DisasterModeInfo.java
  src/main/resources/component-biz.conf
Labels: 🧬 Enhancement

#1200 Improves processes and their logging and downloads of URLs from VirtualFile
  src/main/java/sirius/biz/process/Process.java
  src/main/java/sirius/biz/process/ProcessContext.java
  src/main/java/sirius/biz/process/ProcessEnvironment.java
  src/main/java/sirius/biz/process/Processes.java
  src/main/java/sirius/biz/process/logs/ProcessLog.java
  src/main/java/sirius/biz/storage/layer2/variants/ConversionEngine.java
  src/main/java/sirius/biz/storage/layer3/FetchFromUrlMode.java
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
  src/main/resources/biz_de.properties
Labels: 🧬 Enhancement,  💣 BREAKING CHANGE

#1201 Provides the "SmartValues" framework.
  src/main/java/sirius/biz/tycho/smart/EmailSmartValueProvider.java
  src/main/java/sirius/biz/tycho/smart/EntityResolver.java
  src/main/java/sirius/biz/tycho/smart/README.md
  src/main/java/sirius/biz/tycho/smart/SmartValue.java
  src/main/java/sirius/biz/tycho/smart/SmartValueProvider.java
  src/main/java/sirius/biz/tycho/smart/SmartValueResolver.java
  src/main/java/sirius/biz/tycho/smart/SmartValuesController.java
  src/main/java/sirius/biz/tycho/smart/TenantResolver.java
  src/main/java/sirius/biz/tycho/smart/TenantSmartValueProvider.java
  src/main/java/sirius/biz/tycho/smart/UserAccountResolver.java
  src/main/java/sirius/biz/tycho/smart/UserAccountSmartValueProvider.java
  src/main/resources/default/assets/scripts/smartValues.js
  src/main/resources/default/assets/scripts/tycho-biz.js.pasta
  src/main/resources/default/assets/styles/smartValues.scss
  src/main/resources/default/assets/styles/tycho-biz.scss
  src/main/resources/default/taglib/t/smartValue.html.pasta
Labels: 🧬 Enhancement

#1203 Allows to access the importer of an import job externally
  src/main/java/sirius/biz/jobs/batch/ImportJob.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1202 No longer always fills the total items with the current items
  src/main/java/sirius/biz/web/BasePageHelper.java
Labels: 🐛 Bugfix

#1209 Adds performInContext variants
  src/main/java/sirius/biz/process/ErrorContext.java
Labels: 🧬 Enhancement

#1211 Adds a tag for a generic create button to a single url or a dropdown
  pom.xml
  src/main/resources/default/taglib/t/createButton.html.pasta
Labels: 🧬 Enhancement

#1212 Adds a "has warnings" filter to the processes UI.
  src/main/java/sirius/biz/process/ProcessController.java
Labels: 🧬 Enhancement

#1213 Includes causing error in download failed error message
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
Labels: 🐛 Bugfix
