Repository scireum/sirius-biz, pull requests merged in 2021-12, with the labels that each got.

#1321 We should really not attempt to bind a user "only" for event logging
  src/main/java/sirius/biz/analytics/events/UserData.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1317 Renames Spock Specification to *Spec
  src/test/java/sirius/biz/cluster/RedisUserMessageCacheSpec.groovy
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1319 Normalizes VFS to Unicode NFC Form
  src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLDirectory.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoDirectory.java
  src/main/java/sirius/biz/storage/util/StorageUtils.java
Labels:  💣 BREAKING CHANGE

#1322 Changes visibility of DictionaryBasedImport to public
  src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedImport.java
Labels: 👶🏻 Trivial

#1323 Properly passes the selected database to the job when exporting a query from /system/sql.
  src/main/java/sirius/biz/cluster/work/DistributedTasks.java
  src/main/java/sirius/biz/jdbc/DatabaseController.java
  src/main/resources/default/templates/biz/model/sql.html.pasta
Labels: 🐛 Bugfix

#1327 SAML initial system setup fix
  src/main/java/sirius/biz/tenants/BaseTenantAutoSetup.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1326 Excludes system tables from the size calculations of the database.
  src/main/java/sirius/biz/analytics/events/ClickhouseSizeChartJobFactory.java
Labels: 👶🏻 Trivial

#1324 Changes the default for the ignore empty values parameter
  src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedImport.java
  src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedImportJob.java
Labels: 👶🏻 Trivial,  💣 BREAKING CHANGE

#1330 Reverts visibility changes
  src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedImport.java
Labels: 👶🏻 Trivial

#1331 Makes the Jupiter synchronization more resilient.
  src/main/java/sirius/biz/jupiter/JupiterSync.java
Labels: 🐛 Bugfix

#1333 Fixes automatic jupiter update deactivate by config
  src/main/java/sirius/biz/jupiter/JupiterSync.java
Labels: 🐛 Bugfix

#1332 Permits to create temporary Uplinks via the VirtualFileSystem.
  src/main/java/sirius/biz/storage/layer3/VirtualFileSystem.java
  src/main/java/sirius/biz/storage/layer3/uplink/ConfigBasedUplink.java
  src/main/java/sirius/biz/storage/layer3/uplink/ConfigBasedUplinksRoot.java
  src/main/java/sirius/biz/storage/layer3/uplink/UplinkFactory.java
  src/main/java/sirius/biz/storage/layer3/uplink/cifs/CIFSUplink.java
  src/main/java/sirius/biz/storage/layer3/uplink/fs/LocalDirectoryUplink.java
  src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplink.java
  src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplinkConnectorConfig.java
  src/main/java/sirius/biz/storage/layer3/uplink/sftp/SFTPUplink.java
  src/main/java/sirius/biz/storage/layer3/uplink/sftp/SFTPUplinkConnectorConfig.java
  src/main/java/sirius/biz/storage/layer3/uplink/util/UplinkConnector.java
  src/main/java/sirius/biz/storage/layer3/uplink/util/UplinkConnectorConfig.java
Labels: 🧬 Enhancement
