Repository scireum/sirius-biz, pull requests merged in 2021-06, with the labels that each got.

#1103 Provides a helper for generating YAML files in Jupiter and some security updates.
  pom.xml
  src/main/java/sirius/biz/analytics/scheduler/BaseEntityBatchEmitter.java
  src/main/java/sirius/biz/jupiter/JupiterYamlDataProvider.java
Labels: 👶🏻 Trivial

#1105 Allows MultiLanguageStrings to validate against a LookupTable and...
  src/main/java/sirius/biz/model/InternationalAddressData.java
  src/main/java/sirius/biz/model/PersonData.java
  src/main/java/sirius/biz/tenants/TenantData.java
  src/main/java/sirius/biz/tenants/TenantUserManager.java
  src/main/java/sirius/biz/tenants/UserAccountData.java
  src/main/java/sirius/biz/translations/MultiLanguageString.java
  src/main/java/sirius/biz/translations/MultiLanguageStringProperty.java
  src/main/java/sirius/biz/util/Countries.java
  src/main/java/sirius/biz/util/Languages.java
  src/main/resources/default/templates/biz/tenants/profile.html.pasta
  src/main/resources/default/templates/biz/tenants/tenant-details-fields.html.pasta
  src/main/resources/default/templates/biz/tenants/tenant-details.html.pasta
  src/main/resources/default/templates/biz/tenants/user-account-details-fields.html.pasta
  src/test/java/sirius/biz/translations/ESMultiLanguageStringPropertySpec.groovy
  src/test/java/sirius/biz/translations/MongoMultiLanguageStringPropertySpec.groovy
  src/test/java/sirius/biz/translations/SQLMultiLanguageStringEntity.java
  src/test/java/sirius/biz/translations/SQLMultiLanguageStringPropertySpec.groovy
Labels:  💣 BREAKING CHANGE

#1109 Provides a 'rest of world' icon for both countries and languages.
  src/main/resources/default/assets/images/flags/countries/row.png
  src/main/resources/default/assets/images/flags/languages/globe.png
  src/main/resources/default/assets/images/flags/languages/row.png
  src/main/resources/default/assets/javascript/multiLanguageField.js
Labels: 👶🏻 Trivial

#1112 activate nightly tests in drone
  .drone.yml
Labels: 👶🏻 Trivial

#1111 Displays the short version string on the cluster page for all nodes
  pom.xml
  src/main/java/sirius/biz/cluster/BackgroundInfo.java
  src/main/java/sirius/biz/cluster/ClusterController.java
  src/main/java/sirius/biz/cluster/NeighborhoodWatch.java
  src/main/resources/default/templates/biz/cluster/cluster.html.pasta
Labels: 👶🏻 Trivial, 🧬 Enhancement

#1118 wait more time to hopefully make the test running stable
  src/test/java/sirius/biz/storage/layer1/ReplicationSpec.groovy
Labels: 👶🏻 Trivial

#1117 Updates to the latest sirius-web and performs required changes.
  develop.conf
  pom.xml
  src/main/java/sirius/biz/analytics/flags/jdbc/SQLPerformanceData.java
  src/main/java/sirius/biz/analytics/flags/mongo/MongoPerformanceData.java
  src/main/java/sirius/biz/cluster/RedisUserMessageCache.java
  src/main/java/sirius/biz/codelists/CodeListController.java
  src/main/java/sirius/biz/codelists/LookupTableEntry.java
  src/main/java/sirius/biz/codelists/LookupValue.java
  src/main/java/sirius/biz/codelists/jdbc/SQLCodeListController.java
  src/main/java/sirius/biz/jobs/scheduler/SchedulerController.java
  src/main/java/sirius/biz/model/QueryController.java
  src/main/java/sirius/biz/process/ProcessController.java
  src/main/java/sirius/biz/storage/layer3/VFSController.java
  src/main/java/sirius/biz/storage/legacy/StorageController.java
  src/main/java/sirius/biz/tenants/BizInterceptor.java
  src/main/java/sirius/biz/tenants/TenantController.java
  src/main/java/sirius/biz/tenants/UserAccountController.java
  src/main/java/sirius/biz/tenants/UserAccountData.java
  src/main/java/sirius/biz/tycho/kb/KnowledgeBaseController.java
  src/main/java/sirius/biz/tycho/search/OpenSearchController.java
  src/main/java/sirius/biz/web/BasePageHelper.java
  src/main/java/sirius/biz/web/BizController.java
  src/main/java/sirius/biz/web/DisasterModeInfo.java
  src/main/java/sirius/biz/web/ElasticPageHelper.java
  src/main/java/sirius/biz/web/MongoPageHelper.java
  src/main/java/sirius/biz/web/SQLPageHelper.java
  src/main/resources/biz_de.properties
  src/main/resources/component-biz.conf
  src/main/resources/default/taglib/k/base.html.pasta
  src/main/resources/default/taglib/k/code.html.pasta
  src/main/resources/default/templates/biz/tycho/kb/welcome.html.pasta
  src/main/resources/default/templates/biz/tycho/kb/welcome_de.html.pasta
  src/main/resources/default/templates/biz/tycho/search/search.html.pasta
  src/test/java/sirius/biz/cluster/RedisUserMessageCacheTest.groovy
Labels:  💣 BREAKING CHANGE

#1121 Enables bootstrap field styling for token autocomplete fields
  src/main/resources/default/taglib/w/lookupValueSingleSelect.html.pasta
  src/main/resources/default/taglib/w/lookupValuesMultiSelect.html.pasta
Labels: 👶🏻 Trivial

#1125 Logs and skips 0-byte file when extracting archives
  src/main/java/sirius/biz/storage/layer3/ExtractArchiveJob.java
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
Labels: 🧬 Enhancement

#1123 Language configuration via Scopes
  pom.xml
  src/main/java/sirius/biz/codelists/CodeListEntryData.java
  src/main/java/sirius/biz/importer/format/FieldDefinition.java
  src/main/java/sirius/biz/jupiter/IDBTable.java
  src/main/java/sirius/biz/tenants/TenantUserManager.java
  src/main/java/sirius/biz/translations/MultiLanguageStringProperty.java
  src/main/java/sirius/biz/util/Languages.java
  src/main/resources/component-biz.conf
Labels:  💣 BREAKING CHANGE

#1128 Resolves cast error parsing 7-zip entries
  src/main/java/sirius/biz/util/SevenZipAdapter.java
Labels: 🐛 Bugfix
