Repository scireum/sirius-biz, pull requests merged in 2021-04, with the labels that each got.

#1048 Increases the tenants cache size to a more reasonable number
  src/main/resources/component-biz.conf
Labels: 👶🏻 Trivial

#1051 Ensures the login is recorded everytime findUserByCredentials is called
  src/main/java/sirius/biz/tenants/TenantUserManager.java
Labels: 🧬 Enhancement

#1052 Invokes the failure consumer when no file is present
  src/main/java/sirius/biz/storage/layer1/DownloadManager.java
  src/main/java/sirius/biz/storage/layer1/ObjectStorageSpace.java
Labels: 🐛 Bugfix

#1053 Enhancements processing line-based files from archives
  src/main/java/sirius/biz/importer/format/ImportDictionary.java
  src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedImportJob.java
  src/main/java/sirius/biz/jobs/batch/file/FileImportJob.java
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
Labels: 🧬 Enhancement

#1056 Provides an ImportHelper and an EntityImportHandlerExtender to properly im- and export MultiLanguageStrings
  src/main/java/sirius/biz/codelists/jdbc/SQLCodeListEntryImportHandler.java
  src/main/java/sirius/biz/codelists/mongo/MongoCodeListEntryImportHandler.java
  src/main/java/sirius/biz/translations/MultiLanguageString.java
  src/main/java/sirius/biz/translations/MultiLanguageStringExtender.java
  src/main/java/sirius/biz/translations/MultiLanguageStringHelper.java
  src/main/java/sirius/biz/translations/MultiLanguageStringProperty.java
Labels: 🧬 Enhancement

#1057 Updates API calls for consistency and allow fluent calls
  src/main/java/sirius/biz/translations/MultiLanguageStringHelper.java
Labels: 👶🏻 Trivial

#1059 Adds a method to easily write journal entries
  src/main/java/sirius/biz/protocol/DelegateJournalData.java
Labels: 👶🏻 Trivial

#1060 Adds "mappings" support to LookupTable andprovides/enhances Countries and Languages.
  src/main/java/sirius/biz/codelists/CodeListLookupTable.java
  src/main/java/sirius/biz/codelists/CustomLookupTable.java
  src/main/java/sirius/biz/codelists/IDBFilteredLookupTable.java
  src/main/java/sirius/biz/codelists/IDBLookupTable.java
  src/main/java/sirius/biz/codelists/LookupTable.java
  src/main/java/sirius/biz/model/InternationalAddressData.java
  src/main/java/sirius/biz/util/Countries.java
  src/main/java/sirius/biz/util/Languages.java
  src/main/resources/component-biz.conf
Labels: 🧬 Enhancement

#1063 Escapes the JSON in the multiLanguageStringField to allow " in the translations
  src/main/resources/default/taglib/w/multiLanguageTextArea.html.pasta
  src/main/resources/default/taglib/w/multiLanguageTextField.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1064 BREAKING CHANGE: Updates to the latest sirius dependencies and adds common menu items to the new Tycho menus.
  pom.xml
  src/main/resources/default/extensions/biz-tycho-menu/menu-code-lists.html.pasta
  src/main/resources/default/extensions/biz-tycho-menu/menu-jobs.html.pasta
  src/main/resources/default/extensions/biz-tycho-menu/menu-protcols.html.pasta
  src/main/resources/default/extensions/biz-tycho-menu/menu-system-tenant.html.pasta
  src/main/resources/default/extensions/biz-tycho-menu/menu-tenants.html.pasta
  src/main/resources/default/extensions/biz-tycho-menu/menu-user-logout.html.pasta
  src/main/resources/default/extensions/biz-tycho-menu/menu-vfs.html.pasta
  src/main/resources/default/extensions/tycho-page-menu/menu.html.pasta
Labels:  💣 BREAKING CHANGE, 🧬 Enhancement

#1066 Uses the proper field prefix when resolving/normalizing with mappings.
  src/main/java/sirius/biz/codelists/LookupTable.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1067 Uses the new tycho error page template when rendering a permission error
  src/main/java/sirius/biz/tenants/BizInterceptor.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1069 Provides a toString and forceName for LookupValue.
  src/main/java/sirius/biz/codelists/CodeListLookupTable.java
  src/main/java/sirius/biz/codelists/CustomLookupTable.java
  src/main/java/sirius/biz/codelists/IDBFilteredLookupTable.java
  src/main/java/sirius/biz/codelists/IDBLookupTable.java
  src/main/java/sirius/biz/codelists/LookupTable.java
  src/main/java/sirius/biz/codelists/LookupValue.java
Labels: 👶🏻 Trivial, 🧬 Enhancement

#1070 Tycho: Replaces some icons with their new FontAwesome names
  src/main/resources/default/extensions/biz-tycho-menu/menu-system-tenant.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial
