Repository scireum/sirius-biz, pull requests merged in 2022-02, with the labels that each got.

#1350 SIRI-524 fix a bug on moving files in the vfs
  src/main/java/sirius/biz/importer/ImportHandlerFactory.java
  src/main/java/sirius/biz/storage/README.md
  src/main/java/sirius/biz/storage/layer3/BlockwiseIterator.java
  src/main/java/sirius/biz/storage/layer3/ChildProvider.java
  src/main/java/sirius/biz/storage/layer3/ExtractArchiveJob.java
  src/main/java/sirius/biz/storage/layer3/FetchFromUrlMode.java
  src/main/java/sirius/biz/storage/layer3/FileSearch.java
  src/main/java/sirius/biz/storage/layer3/TmpRoot.java
  src/main/java/sirius/biz/storage/layer3/Transfer.java
  src/main/java/sirius/biz/storage/layer3/TreeVisitorBuilder.java
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
  src/main/java/sirius/biz/storage/layer3/VirtualFileSystem.java
  src/main/java/sirius/biz/storage/layer3/VirtualFileWalker.java
Labels: 🐛 Bugfix

#1351 Removes parent reference on deletion propagation of sql directories
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLProcessBlobChangesLoop.java
Labels: 🐛 Bugfix

#1352 Properly notes connectivyIssue on retry
  src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
Labels: 🐛 Bugfix

#1354 Specifies a proper (and supported) TLS protocol to use for ftps.
  src/main/java/sirius/biz/storage/layer3/downlink/ftp/FTPServer.java
  src/main/resources/component-biz.conf
Labels: 🐛 Bugfix

#1355 Translates "name" more literally.
  src/main/resources/biz_da.properties
  src/main/resources/biz_es.properties
  src/main/resources/biz_no.properties
  src/main/resources/biz_ro.properties
  src/main/resources/biz_sv.properties
Labels: 👶🏻 Trivial

#1357 Correctly encodes file name when uploading files
  src/main/resources/default/assets/scripts/vfs-modals.js
  src/main/resources/default/taglib/t/blobImageHardRefField.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1359 restore logic for uplinkRoot to get correct name (and id only as fallback)
  src/main/java/sirius/biz/storage/layer3/uplink/ConfigBasedUplinksRoot.java
  src/main/java/sirius/biz/storage/layer3/uplink/cifs/CIFSUplink.java
  src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplinkConnectorConfig.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1363 Uses a more consistent naming for addRow.
  pom.xml
  src/main/java/sirius/biz/jdbc/ExportQueryResultJobFactory.java
  src/main/java/sirius/biz/jobs/batch/file/EntityExportJob.java
  src/main/java/sirius/biz/jobs/batch/file/ExportCSV.java
  src/main/java/sirius/biz/jobs/batch/file/ExportXLSX.java
  src/main/java/sirius/biz/jobs/batch/file/LineBasedExport.java
  src/main/java/sirius/biz/process/ExportLogsAsFileTaskExecutor.java
Labels: 👶🏻 Trivial

#1364 Provides a bunch of metrics / performance flags for tenants.
  src/main/java/sirius/biz/analytics/charts/Timeseries.java
  src/main/java/sirius/biz/analytics/flags/PerformanceFlag.java
  src/main/java/sirius/biz/analytics/metrics/DailyGlobalMetricComputer.java
  src/main/java/sirius/biz/analytics/metrics/GlobalBestEffortDailyMetricScheduler.java
  src/main/java/sirius/biz/analytics/metrics/GlobalGuaranteedDailyMetricScheduler.java
  src/main/java/sirius/biz/analytics/metrics/GlobalGuaranteedMonthlyMetricScheduler.java
  src/main/java/sirius/biz/analytics/metrics/jdbc/SQLDailyGlobalMetricComputer.java
  src/main/java/sirius/biz/analytics/metrics/jdbc/SQLMonthlyGlobalMetricComputer.java
  src/main/java/sirius/biz/analytics/metrics/mongo/MongoDailyGlobalMetricComputer.java
  src/main/java/sirius/biz/analytics/metrics/mongo/MongoMonthlyGlobalMetricComputer.java
  src/main/java/sirius/biz/analytics/scheduler/AnalyticsBatchExecutor.java
  src/main/java/sirius/biz/analytics/scheduler/BaseAnalyticalTaskScheduler.java
  src/main/java/sirius/biz/analytics/scheduler/MongoAnalyticalTaskScheduler.java
  src/main/java/sirius/biz/analytics/scheduler/SQLAnalyticalTaskScheduler.java
  src/main/java/sirius/biz/cluster/work/NamedRegions.java
  src/main/java/sirius/biz/jobs/interactive/TimeseriesChartJobFactory.java
  src/main/java/sirius/biz/tenants/TenantMetricComputer.java
  src/main/java/sirius/biz/tenants/UserAccountAcademyMetricComputer.java
  src/main/java/sirius/biz/tenants/UserAccountActivityMetricComputer.java
  src/main/java/sirius/biz/tenants/jdbc/SQLTenantGlobalMetricComputer.java
  src/main/java/sirius/biz/tenants/jdbc/SQLTenantMetricComputer.java
  src/main/java/sirius/biz/tenants/jdbc/SQLUserAccountAcademyMetricComputer.java
  src/main/java/sirius/biz/tenants/mongo/MongoTenantGlobalMetricComputer.java
  src/main/java/sirius/biz/tenants/mongo/MongoTenantMetricComputer.java
  src/main/java/sirius/biz/tenants/mongo/MongoUserAccountAcademyMetricComputer.java
  src/main/java/sirius/biz/tycho/DashboardController.java
  src/main/java/sirius/biz/tycho/academy/OnboardingVideoData.java
  src/main/resources/component-biz.conf
Labels:  💣 BREAKING CHANGE

#1366 fixes startup-warnings (and typos :) )
  src/main/java/sirius/biz/tenants/jdbc/SQLTenant.java
  src/main/java/sirius/biz/tenants/jdbc/SQLUserAccount.java
  src/main/java/sirius/biz/tenants/jdbc/SQLUserAccountAcademyMetricComputer.java
  src/main/java/sirius/biz/tenants/mongo/MongoUserAccountAcademyMetricComputer.java
Labels: 👶🏻 Trivial

#1365 Improves Query Tool Functionality and moves to Tycho
  pom.xml
  src/main/java/sirius/biz/model/QueryController.java
  src/main/resources/default/templates/biz/model/query-descriptors.html.pasta
  src/main/resources/default/templates/biz/model/query-header.html.pasta
  src/main/resources/default/templates/biz/model/query-map-property.html.pasta
  src/main/resources/default/templates/biz/model/query-nested-property.html.pasta
  src/main/resources/default/templates/biz/model/query-ref-list-property.html.pasta
  src/main/resources/default/templates/biz/model/query-results.html.pasta
Labels: 🧬 Enhancement

#1367 Improves /system/scripting to directly report into a Process(Context).
  src/main/java/sirius/biz/ide/Scripting.java
  src/main/java/sirius/biz/process/Processes.java
  src/main/java/sirius/biz/process/output/TableOutput.java
  src/main/java/sirius/biz/tenants/Tenants.java
  src/main/resources/default/kb/en/system/scripting.html.pasta
  src/main/resources/default/taglib/k/code.html.pasta
Labels: 🧬 Enhancement

#1368 Adds a AllInListCheck for FieldDefinition
  src/main/java/sirius/biz/importer/format/AllInListCheck.java
  src/main/java/sirius/biz/importer/format/ValueInListCheck.java
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
Labels: 🧬 Enhancement

#1369 Calls the new methods to follow all redirects
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
Labels: 👶🏻 Trivial

#1370 No longer logs conversion failures to storage log
  src/main/java/sirius/biz/storage/layer2/variants/ConversionEngine.java
Labels: 👶🏻 Trivial
