Repository scireum/sirius-biz, pull requests merged in 2022-01, with the labels that each got.

#1340 Adds a few languages
  src/main/resources/component-biz.conf
Labels: 👶🏻 Trivial

#1299 ports system/schema to tycho
  develop.conf
  src/main/java/sirius/biz/jdbc/DatabaseController.java
  src/main/java/sirius/biz/process/Process.java
  src/main/java/sirius/biz/tenants/SAMLController.java
  src/main/resources/biz_bg.properties
  src/main/resources/biz_cs.properties
  src/main/resources/biz_da.properties
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
  src/main/resources/biz_es.properties
  src/main/resources/biz_fi.properties
  src/main/resources/biz_fr.properties
  src/main/resources/biz_hu.properties
  src/main/resources/biz_it.properties
  src/main/resources/biz_nl.properties
  src/main/resources/biz_pl.properties
  src/main/resources/biz_pt.properties
  src/main/resources/biz_ro.properties
  src/main/resources/biz_ru.properties
  src/main/resources/biz_sk.properties
  src/main/resources/biz_sv.properties
  src/main/resources/default/kb/en/system/schema.html.pasta
  src/main/resources/default/templates/biz/model/schema.html.pasta
Labels: 🧬 Enhancement

#1341 Fixes Lookup of Blobs via Filename.
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java
Labels: 🐛 Bugfix

#1344 Calls the correct javascript function when moving files
  src/main/resources/default/templates/biz/storage/list.html.pasta
Labels: 🐛 Bugfix

#1346 removes "return false" because it crashes the page in firefox
  src/main/resources/default/templates/biz/model/schema.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1343 ErrorContext: permits to only log messages under the current context
  src/main/java/sirius/biz/process/ErrorContext.java
Labels: 🧬 Enhancement

#1347 make IE-users happy again for system/schema
  src/main/resources/default/templates/biz/model/schema.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1345 ImportFileJob: new Parent Directory(ies) parameter
  src/main/java/sirius/biz/jobs/batch/file/FileImportJob.java
  src/main/java/sirius/biz/jobs/batch/file/FileImportJobFactory.java
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
Labels: 🧬 Enhancement
