Repository scireum/sirius-biz, pull requests merged in 2022-08, with the labels that each got.

#1447 SIRI 595 Migrate Sirius-Web, fix double nesting detail.detail
  pom.xml
  src/main/resources/default/templates/biz/jobs/job.html.pasta
  src/main/resources/default/templates/biz/jobs/params/lookuptable.html.pasta
  src/main/resources/default/templates/biz/jobs/params/paramSingleSelect.html.pasta
Labels: 🐛 Bugfix,  💣 BREAKING CHANGE

#1448 SIRI-595: Tycho Jobs Bugfixes
  src/main/java/sirius/biz/jobs/BasicJobFactory.java
  src/main/java/sirius/biz/jobs/JobFactory.java
  src/main/resources/default/assets/scripts/vfs-modals.js
  src/main/resources/default/taglib/t/fileField.html.pasta
  src/main/resources/default/templates/biz/jobs/job.html.pasta
Labels: 🐛 Bugfix

#1451 Increases the max runtime for blob changes
  src/main/java/sirius/biz/storage/layer2/ProcessBlobChangesLoop.java
Labels: 👶🏻 Trivial

#1453 Creates a helper to show grouped actions and uses this for /jobs
  src/main/java/sirius/biz/analytics/events/ClickhousePartsReportJobFactory.java
  src/main/java/sirius/biz/analytics/events/ClickhouseSizeChartJobFactory.java
  src/main/java/sirius/biz/codelists/jdbc/SQLCodeListExportJobFactory.java
  src/main/java/sirius/biz/codelists/jdbc/SQLCodeListImportJobFactory.java
  src/main/java/sirius/biz/codelists/mongo/MongoCodeListExportJobFactory.java
  src/main/java/sirius/biz/codelists/mongo/MongoCodeListImportJobFactory.java
  src/main/java/sirius/biz/elastic/ElasticIndexSizeReportJobFactory.java
  src/main/java/sirius/biz/elastic/MoveIndexAliasJobFactory.java
  src/main/java/sirius/biz/elastic/ReindexJobFactory.java
  src/main/java/sirius/biz/importer/BaseImportHandler.java
  src/main/java/sirius/biz/isenguard/BlockedIPsReportJobFactory.java
  src/main/java/sirius/biz/isenguard/RateLimitEventsReportJobFactory.java
  src/main/java/sirius/biz/isenguard/RateLimitReportJobFactory.java
  src/main/java/sirius/biz/jdbc/ExportQueryResultJobFactory.java
  src/main/java/sirius/biz/jdbc/ExportSchemaChangesJobFactory.java
  src/main/java/sirius/biz/jobs/JobCategory.java
  src/main/java/sirius/biz/jobs/JobFactory.java
  src/main/java/sirius/biz/jobs/Jobs.java
  src/main/java/sirius/biz/jobs/JobsController.java
  src/main/java/sirius/biz/jobs/StandardJobCategories.java
  src/main/java/sirius/biz/jobs/batch/CheckBatchProcessFactory.java
  src/main/java/sirius/biz/jobs/batch/DefaultBatchProcessFactory.java
  src/main/java/sirius/biz/jobs/batch/ExportBatchProcessFactory.java
  src/main/java/sirius/biz/jobs/batch/ImportBatchProcessFactory.java
  src/main/java/sirius/biz/jobs/batch/ReportBatchProcessFactory.java
  src/main/java/sirius/biz/jobs/batch/SimpleBatchProcessJobFactory.java
  src/main/java/sirius/biz/jobs/batch/SimpleReportBatchProcessFactory.java
  src/main/java/sirius/biz/jobs/batch/file/LineBasedExportJobFactory.java
  src/main/java/sirius/biz/jobs/batch/file/LineBasedImportJobFactory.java
  src/main/java/sirius/biz/jobs/interactive/ReportJobFactory.java
  src/main/java/sirius/biz/jobs/interactive/SingleDatasetChartJobFactory.java
  src/main/java/sirius/biz/jupiter/JupiterSyncJob.java
  src/main/java/sirius/biz/model/ResaveEntitiesJobFactory.java
  src/main/java/sirius/biz/process/Processes.java
  src/main/java/sirius/biz/storage/layer1/replication/ForceReplicationJob.java
  src/main/java/sirius/biz/storage/layer3/ExtractArchiveJob.java
  src/main/java/sirius/biz/storage/layer3/TransferFilesJob.java
  src/main/java/sirius/biz/tenants/deletion/DeleteTenantJobFactory.java
  src/main/java/sirius/biz/tenants/jdbc/SQLTenantExportJobFactory.java
  src/main/java/sirius/biz/tenants/jdbc/SQLUserAccountExportJobFactory.java
  src/main/java/sirius/biz/tenants/jdbc/SQLUserAccountImportJobFactory.java
  src/main/java/sirius/biz/tenants/mongo/MongoTenantExportJobFactory.java
  src/main/java/sirius/biz/tenants/mongo/MongoUserAccountExportJobFactory.java
  src/main/java/sirius/biz/tenants/mongo/MongoUserAccountImportJobFactory.java
  src/main/java/sirius/biz/util/ReportUnusedNLSKeysJob.java
  src/main/java/sirius/biz/web/Action.java
  src/main/resources/biz_de.properties
  src/main/resources/default/taglib/t/actions.html.pasta
  src/main/resources/default/templates/biz/jobs/jobs.html.pasta
Labels:  💣 BREAKING CHANGE

#1455 Sets a cookie manager when downloading files
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
Labels: 👶🏻 Trivial
