Repository scireum/sirius-biz, pull requests merged in 2022-12, with the labels that each got.

#1544 Adds separate metric for number of delayed replication tasks
  src/main/java/sirius/biz/storage/layer1/replication/ReplicationTaskStorage.java
  src/main/java/sirius/biz/storage/layer1/replication/jdbc/SQLReplicationTaskStorage.java
  src/main/java/sirius/biz/storage/layer1/replication/mongo/MongoReplicationTaskStorage.java
  src/main/java/sirius/biz/storage/util/StorageMetrics.java
Labels: 👶🏻 Trivial

#1545 Removes constrain for transaction source
  src/main/java/sirius/biz/importer/txn/ImportTransactionHelper.java
Labels: 👶🏻 Trivial, 🔥 Hotfix

#1550 SIRI-678: Increases the size of the 'name' column for Facts.
  src/main/java/sirius/biz/analytics/metrics/jdbc/Fact.java
  src/main/java/sirius/biz/analytics/metrics/mongo/Fact.java
Labels: 🔥 Hotfix

#1554 Makes SFTP downlink support file renaming
  src/main/java/sirius/biz/storage/layer3/downlink/ssh/sftp/BridgeFileSystemAccessor.java
Labels: 🔥 Hotfix
