Repository scireum/sirius-biz, pull requests merged in 2022-07, with the labels that each got.

#1430 Fixes an NPE deleting variants
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLVariant.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoVariant.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1435 Adds a new kb tag: link
  src/main/resources/default/taglib/k/link.html.pasta
Labels: 👶🏻 Trivial

#1437 Auto-Creation of System Tenant with Correct ID
  src/main/java/sirius/biz/tenants/jdbc/SQLTenantAutoSetup.java
  src/main/java/sirius/biz/tenants/mongo/MongoTenantAutoSetup.java
Labels:  💣 BREAKING CHANGE

#1440 Adds an empty default value to the name argument
  src/main/resources/default/taglib/k/link.html.pasta
Labels: 👶🏻 Trivial

#1442 Improves the versatility of the link tag
  src/main/resources/default/taglib/k/link.html.pasta
Labels: 👶🏻 Trivial
