Repository scireum/sirius-biz, pull requests merged in 2022-09, with the labels that each got.

#1459 Renames a class and fixes some typos.
  src/main/java/sirius/biz/analytics/events/ClickhousePartsReportJobFactory.java
  src/main/java/sirius/biz/analytics/events/ClickhouseSizeChartJobFactory.java
  src/main/java/sirius/biz/codelists/jdbc/SQLCodeListExportJobFactory.java
  src/main/java/sirius/biz/codelists/jdbc/SQLCodeListImportJobFactory.java
  src/main/java/sirius/biz/codelists/mongo/MongoCodeListExportJobFactory.java
  src/main/java/sirius/biz/codelists/mongo/MongoCodeListImportJobFactory.java
  src/main/java/sirius/biz/elastic/ElasticIndexSizeReportJobFactory.java
  src/main/java/sirius/biz/elastic/MoveIndexAliasJobFactory.java
  src/main/java/sirius/biz/elastic/ReindexJobFactory.java
  src/main/java/sirius/biz/elastic/SearchableEntity.java
  src/main/java/sirius/biz/isenguard/BlockedIPsReportJobFactory.java
  src/main/java/sirius/biz/isenguard/RateLimitEventsReportJobFactory.java
  src/main/java/sirius/biz/isenguard/RateLimitReportJobFactory.java
  src/main/java/sirius/biz/jdbc/ExportQueryResultJobFactory.java
  src/main/java/sirius/biz/jdbc/ExportSchemaChangesJobFactory.java
  src/main/java/sirius/biz/jobs/JobFactory.java
  src/main/java/sirius/biz/jobs/StandardCategories.java
  src/main/java/sirius/biz/jobs/batch/DefaultBatchProcessFactory.java
  src/main/java/sirius/biz/jupiter/JupiterSyncJob.java
  src/main/java/sirius/biz/model/ResaveEntitiesJobFactory.java
  src/main/java/sirius/biz/storage/layer1/replication/ForceReplicationJob.java
  src/main/java/sirius/biz/storage/layer3/ExtractArchiveJob.java
  src/main/java/sirius/biz/storage/layer3/TransferFilesJob.java
  src/main/java/sirius/biz/tenants/TenantUserManager.java
  src/main/java/sirius/biz/tenants/deletion/DeleteTenantJobFactory.java
  src/main/java/sirius/biz/tenants/jdbc/SQLTenantExportJobFactory.java
  src/main/java/sirius/biz/tenants/jdbc/SQLUserAccountExportJobFactory.java
  src/main/java/sirius/biz/tenants/jdbc/SQLUserAccountImportJobFactory.java
  src/main/java/sirius/biz/tenants/mongo/MongoTenantExportJobFactory.java
  src/main/java/sirius/biz/tenants/mongo/MongoUserAccountExportJobFactory.java
  src/main/java/sirius/biz/tenants/mongo/MongoUserAccountImportJobFactory.java
  src/main/java/sirius/biz/util/ReportUnusedNLSKeysJob.java
  src/main/resources/biz_de.properties
Labels: 👶🏻 Trivial

#1457 Adds an image tag which can be used to uniformly render an image…
  src/main/resources/default/taglib/k/image.html.pasta
Labels: 👶🏻 Trivial

#1468 SIRI-619: Fixes setting the job name.
  src/main/java/sirius/biz/jobs/JobConfigData.java
Labels: 👶🏻 Trivial

#1471 Fixes image width being wider than its parent container
  src/main/resources/default/taglib/k/image.html.pasta
Labels: 👶🏻 Trivial

#1473 Correctly formats the tenant autocomplete description
  src/main/java/sirius/biz/tenants/TenantController.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1474 SIRI-627: Fixes Icons for Pie Chart Jobs.
  src/main/java/sirius/biz/jobs/interactive/DougnutChartJobFactory.java
  src/main/java/sirius/biz/jobs/interactive/PolarAreaChartJobFactory.java
Labels: 👶🏻 Trivial

#1475 Displays job icons correctly in wondergem
  src/main/java/sirius/biz/jobs/JobFactory.java
  src/main/java/sirius/biz/jobs/batch/file/LineBasedExportJobFactory.java
  src/main/java/sirius/biz/jobs/batch/file/LineBasedImportJobFactory.java
  src/main/resources/default/taglib/w/jobs.html.pasta
Labels: 🐛 Bugfix

#1476 Fixes another job icon for wondergem
  src/main/java/sirius/biz/jobs/interactive/ReportJobFactory.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1481 Restores fileparameter creating file logic
  src/main/java/sirius/biz/jobs/params/FileParameter.java
Labels: 🔥 Hotfix

#1484 Updates to the latest snake-yaml.
  pom.xml
Labels: 👶🏻 Trivial

#1489 Fixes file parameter for non existent parent
  src/main/java/sirius/biz/jobs/params/FileParameter.java
Labels: 🔥 Hotfix

#1488 Provides an EventTimeSeriesComputer.
  pom.xml
  src/main/java/sirius/biz/analytics/charts/explorer/EventTimeSeriesComputer.java
  src/main/java/sirius/biz/analytics/charts/explorer/TimeSeriesComputer.java
  src/main/java/sirius/biz/analytics/charts/explorer/UserAgentsTimeSeriesComputer.java
  src/main/java/sirius/biz/tenants/metrics/NumberOfUserInteractionsChart.java
  src/main/java/sirius/biz/tenants/metrics/NumberOfUserInteractionsPerTenantChart.java
  src/main/java/sirius/biz/tenants/metrics/UserAccountActivityMetricComputer.java
  src/main/java/sirius/biz/tycho/DashboardUserAgentsChart.java
  src/main/java/sirius/biz/tycho/kb/KnowledgeBaseEntryViewsChart.java
  src/main/java/sirius/biz/tycho/kb/KnowledgeBaseUserAgentsChart.java
  src/main/java/sirius/biz/tycho/kb/KnowledgeBaseViewsChart.java
  src/main/java/sirius/biz/tycho/updates/NumberOfUpdateClicksChart.java
  src/main/resources/biz_de.properties
Labels: 🕔 Wait on sirius

#1487 Kills deprecated code and fixes sonarlint inspections.
  pom.xml
  src/main/java/sirius/biz/analytics/reports/Cell.java
  src/main/java/sirius/biz/analytics/scheduler/AnalyticalEngine.java
  src/main/java/sirius/biz/cluster/ClusterController.java
  src/main/java/sirius/biz/cluster/InterconnectClusterManager.java
  src/main/java/sirius/biz/cluster/RedisUserMessageCache.java
  src/main/java/sirius/biz/codelists/LookupTable.java
  src/main/java/sirius/biz/codelists/LookupValues.java
  src/main/java/sirius/biz/codelists/LookupValuesProperty.java
  src/main/java/sirius/biz/ide/JobTaskContextAdapter.java
  src/main/java/sirius/biz/importer/BaseImportHandler.java
  src/main/java/sirius/biz/importer/MongoEntityImportHandler.java
  src/main/java/sirius/biz/importer/SQLEntityImportHandler.java
  src/main/java/sirius/biz/importer/format/ImportDictionary.java
  src/main/java/sirius/biz/isenguard/Isenguard.java
  src/main/java/sirius/biz/jdbc/DatabaseController.java
  src/main/java/sirius/biz/jdbc/DatabaseParameter.java
  src/main/java/sirius/biz/jobs/Jobs.java
  src/main/java/sirius/biz/jobs/batch/file/EntityExportJob.java
  src/main/java/sirius/biz/jobs/batch/file/FileExportJob.java
  src/main/java/sirius/biz/jobs/params/EntityDescriptorParameter.java
  src/main/java/sirius/biz/jobs/params/FileParameter.java
  src/main/java/sirius/biz/jobs/params/PriorizedPartListParameter.java
  src/main/java/sirius/biz/jobs/params/SelectStringParameter.java
  src/main/java/sirius/biz/jupiter/IDBTable.java
  src/main/java/sirius/biz/jupiter/InfoGraphDB.java
  src/main/java/sirius/biz/jupiter/Jupiter.java
  src/main/java/sirius/biz/jupiter/Repository.java
  src/main/java/sirius/biz/locks/RedisLockManager.java
  src/main/java/sirius/biz/locks/jdbc/SQLLockManager.java
  src/main/java/sirius/biz/model/ContactData.java
  src/main/java/sirius/biz/model/QueryController.java
  src/main/java/sirius/biz/model/ResaveEntitiesJobFactory.java
  src/main/java/sirius/biz/packages/Packages.java
  src/main/java/sirius/biz/process/Process.java
  src/main/java/sirius/biz/process/ProcessContext.java
  src/main/java/sirius/biz/process/ProcessEnvironment.java
  src/main/java/sirius/biz/process/Processes.java
  src/main/java/sirius/biz/process/output/TableProcessOutputType.java
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
  src/main/java/sirius/biz/storage/layer3/downlink/ftp/BridgeFtplet.java
  src/main/java/sirius/biz/storage/layer3/downlink/ssh/BridgePath.java
  src/main/java/sirius/biz/storage/layer3/uplink/ConfigBasedUplinksRoot.java
  src/main/java/sirius/biz/storage/s3/ObjectStore.java
  src/main/java/sirius/biz/storage/util/WatchableInputStream.java
  src/main/java/sirius/biz/tenants/TenantController.java
  src/main/java/sirius/biz/tenants/TenantUserManager.java
  src/main/java/sirius/biz/tenants/jdbc/SQLTenantGlobalMetricComputer.java
  src/main/java/sirius/biz/tenants/metrics/GlobalTenantMetricComputer.java
  src/main/java/sirius/biz/translations/MultiLanguageStringExtender.java
  src/main/java/sirius/biz/translations/MultiLanguageStringProperty.java
  src/main/java/sirius/biz/tycho/academy/RecomputeOnboardingVideosCheck.java
  src/main/java/sirius/biz/tycho/kb/KBHelper.java
  src/main/java/sirius/biz/tycho/kb/KnowledgeBaseController.java
  src/main/java/sirius/biz/util/ArchiveHelper.java
  src/main/java/sirius/biz/util/RedisController.java
  src/main/java/sirius/biz/web/BizController.java
  src/main/resources/component-biz.conf
  src/test/java/sirius/biz/cluster/RedisUserMessageCacheSpec.groovy
  src/test/java/sirius/biz/model/ContactDataTest.java
Labels: 🖐 Keep open,  💣 BREAKING CHANGE, 🕔 Wait on sirius

#1480 improve searching scheduled jobs typos, autoformat, toList
  src/main/java/sirius/biz/jobs/JobStartingRoot.java
  src/main/java/sirius/biz/jobs/Jobs.java
  src/main/java/sirius/biz/jobs/scheduler/SchedulerController.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1485 Adds platform distribution charts
  src/main/java/sirius/biz/analytics/charts/explorer/BrowserDistributionTimeSeriesChartFactory.java
  src/main/java/sirius/biz/analytics/charts/explorer/BrowserDistributionTimeSeriesComputer.java
  src/main/java/sirius/biz/analytics/charts/explorer/EventTimeSeriesComputer.java
  src/main/java/sirius/biz/analytics/charts/explorer/PlatformDistributionTimeSeriesChartFactory.java
  src/main/java/sirius/biz/analytics/charts/explorer/PlatformDistributionTimeSeriesComputer.java
  src/main/java/sirius/biz/analytics/charts/explorer/UserAgentsTimeSeriesChartFactory.java
  src/main/java/sirius/biz/tycho/DashboardBrowserDistributionChart.java
  src/main/java/sirius/biz/tycho/DashboardPlatformDistributionChart.java
  src/main/java/sirius/biz/tycho/DashboardUserAgentsChart.java
  src/main/java/sirius/biz/tycho/kb/KnowledgeBaseBrowserDistributionChart.java
  src/main/java/sirius/biz/tycho/kb/KnowledgeBasePlatformDistributionChart.java
  src/main/java/sirius/biz/tycho/kb/KnowledgeBaseUserAgentsChart.java
  src/main/resources/biz_de.properties
Labels: 🖐 Keep open, 🕔 Wait on sirius

#1491 Correctly hides non-interactive jobs in overview again
  src/main/java/sirius/biz/jobs/JobsController.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1495 ClickHouse: Properly formats SQL Arrays in SQL Query Tool
  src/main/java/sirius/biz/jdbc/DatabaseController.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1493 Initializes limits in standby processes
  src/main/java/sirius/biz/process/ProcessEnvironment.java
Labels: 🐛 Bugfix

#1496 Updates to the latest sirius dependencies and mitigates breaking changes.
  pom.xml
  src/main/java/sirius/biz/i5/I5MetricProvider.java
  src/main/java/sirius/biz/ide/LogMacro.java
  src/main/java/sirius/biz/jupiter/Jupiter.java
  src/main/java/sirius/biz/storage/util/StorageMetrics.java
  src/main/java/sirius/biz/web/ComputeAuthSignatureMacro.java
  src/main/java/sirius/biz/web/CurrentUserNameMacro.java
  src/main/java/sirius/biz/web/SignLinkMacro.java
Labels: 👶🏻 Trivial

#1499 Job parameter fixes
  src/main/resources/default/templates/biz/jobs/job-parameters-logic.html.pasta
  src/main/resources/default/templates/biz/jobs/params/textarea.html.pasta
  src/main/resources/default/templates/biz/jobs/params/textfield.html.pasta
Labels: 🐛 Bugfix
