Repository scireum/sirius-biz, pull requests merged in 2022-11, with the labels that each got.

#1515 Corrects translation key
  src/main/resources/biz_de.properties
  src/main/resources/default/templates/biz/protocol/mail.html.pasta
Labels: 👶🏻 Trivial

#1520 Handles uploading input streams with no contents
  src/main/java/sirius/biz/storage/s3/ObjectStore.java
Labels: 🧬 Enhancement

#1521 Fixes falsely altered border colors in logs
  pom.xml
  src/main/java/sirius/biz/protocol/LoggedMessage.java
  src/main/resources/default/assets/scripts/lookup-tables.js.pasta
  src/main/resources/default/templates/biz/model/schema.html.pasta
  src/main/resources/default/templates/biz/process/process-logs.html.pasta
  src/main/resources/default/templates/biz/process/process-output-logs.html.pasta
  src/main/resources/default/templates/biz/protocol/audit_logs.html.pasta
  src/main/resources/default/templates/biz/protocol/logs.html.pasta
  src/main/resources/default/templates/biz/protocol/mails.html.pasta
Labels: 🐛 Bugfix

#1522 Method Namespace
  src/main/resources/default/assets/scripts/images.js
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1526 Removes the i5 connectivity framework.
  README.md
  pom.xml
  src/main/java/sirius/biz/i5/I5Command.java
  src/main/java/sirius/biz/i5/I5Connection.java
  src/main/java/sirius/biz/i5/I5ConnectionPool.java
  src/main/java/sirius/biz/i5/I5Connector.java
  src/main/java/sirius/biz/i5/I5MetricProvider.java
  src/main/java/sirius/biz/i5/README.md
  src/main/java/sirius/biz/i5/Transform.java
  src/main/java/sirius/biz/i5/Transformable.java
  src/main/java/sirius/biz/i5/Transformer.java
Labels:  💣 BREAKING CHANGE

#1528 Uses the new error handling / HTTP Status code capabilities of sirius-web
  pom.xml
  src/main/java/sirius/biz/jobs/JobsController.java
Labels: 🕔 Wait on sirius

#1531 Adds proper URI encoding.
  src/main/resources/default/extensions/tycho-page-menu/footer.html.pasta
  src/main/resources/default/extensions/wondergem-page-menu/footer.html.pasta
Labels: 👶🏻 Trivial

#1532 SIRI-663 fix upper/lowercases in NLS-keys, use NLS instead of $
  src/main/java/sirius/biz/jobs/interactive/TimeseriesChartJobFactory.java
  src/main/java/sirius/biz/tycho/updates/UpdatesReport.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1535 Possible Fix: Freezing Log Export (SIRI-645)
  src/main/java/sirius/biz/process/Processes.java
  src/main/resources/biz_de.properties
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1525 Defines a source in import transactions
  src/main/java/sirius/biz/importer/txn/ImportTransactionData.java
  src/main/java/sirius/biz/importer/txn/ImportTransactionHelper.java
  src/main/java/sirius/biz/jobs/batch/file/RelationalEntityImportJob.java
  src/main/java/sirius/biz/jobs/batch/file/RelationalEntityImportJobFactory.java
  src/main/resources/biz_de.properties
Labels: 🧬 Enhancement

#1536 Fixes permission for 'system-wide user interaction chart'
  src/main/java/sirius/biz/tenants/metrics/NumberOfUserInteractionsChart.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1542 limit transactionData.source to 50 for suppress startup-warnings in sql
  src/main/java/sirius/biz/importer/txn/ImportTransactionData.java
Labels: 🐛 Bugfix, 👶🏻 Trivial, 🔥 Hotfix

#1543 Corrects variable type of line chart datasets
  src/main/resources/default/templates/biz/jobs/linechart.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial, 🔥 Hotfix

#1541 Only links to job in process when job can be started via UI
  src/main/java/sirius/biz/jobs/batch/BatchProcessJobFactory.java
Labels: 🐛 Bugfix, 👶🏻 Trivial, 🎁 Next version
