Repository scireum/sirius-biz, pull requests merged in 2022-10, with the labels that each got.

#1501 Permits to load groups of CSV files in stages
  src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedArchiveImportJob.java
Labels: 🧬 Enhancement

#1497 Properly document and extends services provided by biz.
  pom.xml
  src/main/java/sirius/biz/i5/I5MetricProvider.java
  src/main/java/sirius/biz/jobs/JobsController.java
  src/main/java/sirius/biz/model/QueryController.java
  src/main/java/sirius/biz/process/ProcessController.java
  src/main/java/sirius/biz/process/Processes.java
  src/main/resources/component-biz.conf
Labels: 🕔 Wait on sirius

#1502 Events: Support for Fluent Calls
  src/main/java/sirius/biz/analytics/events/Event.java
Labels: 👶🏻 Trivial

#1503 Dependency updates.
  pom.xml
  src/main/java/sirius/biz/analytics/events/EventRecorder.java
Labels: 👶🏻 Trivial, dependencies

#1504 Fixes Redis calls after breaking update.
  pom.xml
  src/main/java/sirius/biz/cluster/work/RedisPrioritizedQueue.java
  src/main/java/sirius/biz/isenguard/RedisLimiter.java
  src/main/java/sirius/biz/jupiter/IDBTable.java
  src/main/java/sirius/biz/jupiter/JupiterConnector.java
  src/test/java/sirius/biz/storage/layer1/ReplicationSpec.groovy
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1507 Adds suggested dependency to suppress a warning
  pom.xml
Labels: 👶🏻 Trivial

#1509 Fixes some trivial bugs in the NumberOfInteractions chart.
  docker-compose.yml
  pom.xml
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLDirectory.java
  src/main/java/sirius/biz/tenants/metrics/NumberOfUserInteractionsChart.java
  src/main/java/sirius/biz/tenants/metrics/NumberOfUserInteractionsPerTenantChart.java
  src/main/resources/biz_de.properties
  src/test/resources/docker-compose.yml
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1513 some cosmetics in log & footer for tycho
  src/main/resources/default/extensions/tycho-page-menu/footer.html.pasta
  src/main/resources/default/templates/biz/protocol/audit_logs.html.pasta
  src/main/resources/default/templates/biz/protocol/entity_protocol.html.pasta
  src/main/resources/default/templates/biz/protocol/errors.html.pasta
  src/main/resources/default/templates/biz/protocol/logs.html.pasta
  src/main/resources/default/templates/biz/protocol/mails.html.pasta
  src/main/resources/default/templates/biz/protocol/protocol.html.pasta
  src/main/resources/default/templates/biz/tycho/page-footer-help.html.pasta
Labels: 🧬 Enhancement
