Repository scireum/sirius-biz, pull requests merged in 2022-04, with the labels that each got.

#1390 Uses the correct type in MLS for loops
  src/main/resources/default/taglib/t/multiLanguageTextArea.html.pasta
  src/main/resources/default/taglib/t/multiLanguageTextField.html.pasta
  src/main/resources/default/taglib/w/multiLanguageTextArea.html.pasta
  src/main/resources/default/taglib/w/multiLanguageTextField.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1392 Fixes a StringIndexOutOfBoundsException exception
  src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/BlobDispatcher.java
  src/main/java/sirius/biz/storage/layer2/URLBuilder.java
Labels: 🐛 Bugfix

#1393 Warns when unloading while a file is uploading
  src/main/resources/default/taglib/t/blobImageHardRefField.html.pasta
Labels: 🕔 Wait on sirius

#1395 Binds global tenant metric computation to correct framework
  src/main/java/sirius/biz/tenants/mongo/MongoTenantGlobalMetricComputer.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1398 Renders parent structure of current kb article as breadcrumbs
  src/main/java/sirius/biz/tycho/kb/KnowledgeBaseArticle.java
  src/main/resources/default/taglib/k/base.html.pasta
Labels: 🧬 Enhancement

#1400 Adds text breaks to process output table cells
  src/main/resources/default/templates/biz/process/process-output-table.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial
