Repository scireum/sirius-biz, pull requests merged in 2022-03, with the labels that each got.

#1371 bump underlying sirius-versions and fix some nls/typos
  README.md
  pom.xml
  src/main/resources/biz_bg.properties
  src/main/resources/biz_cs.properties
  src/main/resources/biz_da.properties
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
  src/main/resources/biz_es.properties
  src/main/resources/biz_fi.properties
  src/main/resources/biz_fr.properties
  src/main/resources/biz_hr.properties
  src/main/resources/biz_hu.properties
  src/main/resources/biz_it.properties
  src/main/resources/biz_lt.properties
  src/main/resources/biz_lv.properties
  src/main/resources/biz_nl.properties
  src/main/resources/biz_no.properties
  src/main/resources/biz_pl.properties
  src/main/resources/biz_pt.properties
  src/main/resources/biz_ro.properties
  src/main/resources/biz_ru.properties
  src/main/resources/biz_sk.properties
  src/main/resources/biz_sl.properties
  src/main/resources/biz_sr.properties
  src/main/resources/biz_sv.properties
  src/main/resources/biz_uk.properties
  src/main/resources/default/templates/biz/jobs/scheduler/entry.html.pasta
Labels:  💣 BREAKING CHANGE

#1372 Upgrades clickhouse to version 0.2.6.
  develop.conf
  pom.xml
  src/test/resources/test.conf
Labels:  💣 BREAKING CHANGE

#1374 Provides a bunch of misc minor improvments.
  src/main/java/sirius/biz/analytics/scheduler/MongoAnalyticalTaskScheduler.java
  src/main/java/sirius/biz/analytics/scheduler/SQLAnalyticalTaskScheduler.java
  src/main/java/sirius/biz/ide/Scripting.java
  src/main/java/sirius/biz/storage/layer3/ExtractArchiveJob.java
  src/main/java/sirius/biz/web/BizClassAliasProvider.java
Labels: 🧬 Enhancement

#1375 Add parameter "showAddon" with default value "true".
  src/main/resources/default/taglib/t/lookupValue.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1379 Added parameter to set allowCustomEntries in lookupValue from template
  src/main/resources/default/taglib/t/lookupValue.html.pasta
  src/main/resources/default/taglib/w/lookupValue.html.pasta
Labels: 👶🏻 Trivial

#1378 Ensures system processes cannot accidentally be started in another tenant
  pom.xml
  src/main/java/sirius/biz/jobs/batch/BatchProcessJobFactory.java
  src/main/java/sirius/biz/tenants/TenantUserManager.java
  src/main/java/sirius/biz/web/SpyUser.java
Labels: 🧬 Enhancement

#1382 Creates a line-based archive import job class
  src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedArchiveImportJob.java
  src/main/java/sirius/biz/jobs/batch/file/LineBasedArchiveImportJob.java
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
Labels: 🧬 Enhancement
