Repository scireum/sirius-biz, pull requests merged in 2023-11, with the labels that each got.

#1864 correct autofocus for pages with useful autofocus
  pom.xml
  src/main/resources/default/extensions/tycho-page-menu/menu.html.pasta
  src/main/resources/default/taglib/t/actions.html.pasta
  src/main/resources/default/templates/biz/model/query-header.html.pasta
  src/main/resources/default/templates/biz/model/redis.html.pasta
  src/main/resources/default/templates/biz/model/sql.html.pasta
  src/main/resources/default/templates/biz/password/password-tycho.html.pasta
  src/main/resources/default/templates/biz/tycho/analytics/data-explorer.html.pasta
  src/main/resources/default/templates/biz/tycho/search/search.html.pasta
Labels: 🐛 Bugfix

#1865 Upgrades Apache MINA SSHD
  pom.xml
Labels: ⬆️ Dependencies

#1867 Sirius
  pom.xml
Labels: 👶🏻 Trivial

#1866 Some small enhancements for tab-focus and around
  src/main/java/sirius/biz/codelists/LookupValue.java
  src/main/resources/default/assets/javascript/blobreffield.js
  src/main/resources/default/assets/scripts/multi-language-field.js
  src/main/resources/default/assets/scripts/smart-values.js
  src/main/resources/default/taglib/t/actions.html.pasta
  src/main/resources/default/taglib/t/lookupValue.html.pasta
  src/main/resources/default/taglib/t/multiLanguageTextField.html.pasta
  src/main/resources/default/taglib/t/tracing.html.pasta
  src/main/resources/default/templates/biz/model/query-header.html.pasta
  src/main/resources/default/templates/biz/tycho/analytics/data-explorer.html.pasta
Labels: 🧬 Enhancement, 🛠️ Maintenance

#1868 do not allow customEntries in tenant-country + user-salutation
  src/main/resources/default/templates/biz/tenants/tenant-details-fields.html.pasta
  src/main/resources/default/templates/biz/tenants/user-account-details-fields.html.pasta
Labels: 👶🏻 Trivial

#1869 Adds a sidebar to the base of the kb and enables it in the kb articles
  pom.xml
  src/main/resources/default/taglib/k/article.html.pasta
  src/main/resources/default/taglib/k/base.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1870 BREAKING - Revamps the kb tags 'toc' and 'tocEntry'/'tocLink'
  src/main/resources/default/taglib/k/toc.html.pasta
  src/main/resources/default/taglib/k/tocLink.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial, 💣 BREAKING CHANGE, 🛠️ Maintenance

#1871 Unlocks files when extraction fails
  src/main/java/sirius/biz/storage/layer3/ExtractArchiveJob.java
Labels: 🐛 Bugfix

#1875 Avoids an NPE cascade deleting blobs
  src/main/java/sirius/biz/storage/layer2/BlobHardRefProperty.java
Labels: 👶🏻 Trivial

#1873 Fix: Current Tenant from `UserInfo`
  src/main/java/sirius/biz/tenants/Tenants.java
Labels: 🐛 Bugfix

#1874 Fix: Restores Synthetic Administrator User in Processes
  src/main/java/sirius/biz/cluster/work/DistributedTasks.java
  src/main/java/sirius/biz/jobs/Jobs.java
  src/main/java/sirius/biz/jobs/JobsRoot.java
  src/main/java/sirius/biz/jobs/batch/BatchProcessTaskExecutor.java
  src/main/java/sirius/biz/process/ProcessEnvironment.java
  src/main/java/sirius/biz/process/Processes.java
  src/main/java/sirius/biz/tenants/Tenant.java
  src/main/java/sirius/biz/tenants/Tenants.java
  src/main/java/sirius/biz/tenants/UserAccountData.java
Labels: 🐛 Bugfix, 💣 BREAKING CHANGE

#1872 don't link jobs of tenants and user-accounts on new entities
  src/main/resources/default/templates/biz/tenants/tenant.html.pasta
  src/main/resources/default/templates/biz/tenants/user-account.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1877 Process Persistence
  src/main/java/sirius/biz/process/Processes.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1878 jUnit: Migrates SqlBlobEntityMapping Tests to Kotlin
  src/test/java/sirius/biz/storage/layer2/BlobEntityMappingSpec.groovy
  src/test/kotlin/sirius/biz/storage/layer2/SQLBlobEntityMappingTest.kt
Labels: 🛠️ Maintenance

#1880 Revamps Storage URLs validity and caching
  src/main/java/sirius/biz/storage/layer2/BlobDispatcher.java
  src/main/java/sirius/biz/storage/layer2/URLBuilder.java
  src/main/java/sirius/biz/storage/util/StorageUtils.java
  src/main/java/sirius/biz/tenants/TenantData.java
  src/main/java/sirius/biz/tenants/UserAccountData.java
  src/main/resources/component-070-biz.conf
Labels: 💣 BREAKING CHANGE

#1882 Adds an icon to a tocLink to make the entry look less "empty"
  src/main/resources/default/taglib/k/tocLink.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1881 KB - Adds a toc to multiple articles of the knowledgebase
  src/main/resources/default/kb/de/user/ftp-import.html.pasta
  src/main/resources/default/kb/en/system/cluster.html.pasta
  src/main/resources/default/kb/en/system/customization-flags.html.pasta
  src/main/resources/default/kb/en/system/health.html.pasta
  src/main/resources/default/kb/en/system/kb.html.pasta
  src/main/resources/default/kb/en/system/permissions.html.pasta
  src/main/resources/default/kb/en/system/troubleshooting.html.pasta
  src/main/resources/default/kb/en/user/noodle.html.pasta
  src/main/resources/default/kb/en/user/tagliatelle.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1884 jUnit: Migrate ReplicationTest to Kotlin
  src/test/kotlin/sirius/biz/storage/layer1/ReplicationTest.kt
Labels: 🛠️ Maintenance

#1887 Clarifies priority of lookup table fallbacks
  src/main/java/sirius/biz/codelists/LookupTables.java
Labels: 🐛 Bugfix

#1888 Propagates the eternally valid information from virtual to physical URLs
  src/main/java/sirius/biz/storage/layer2/BlobDispatcher.java
Labels: 🐛 Bugfix

#1889 LookupValueProperty: Considers empty strings as null
  src/main/java/sirius/biz/codelists/LookupValueProperty.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1892 Parses unused NLS keys from other nodes correctly
  src/main/java/sirius/biz/util/ReportUnusedNLSKeysJob.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1894 Fixes sftp deletion of files
  src/main/java/sirius/biz/storage/layer3/downlink/ssh/BridgeFileSystem.java
  src/main/java/sirius/biz/storage/layer3/downlink/ssh/BridgePath.java
Labels: 🐛 Bugfix

#1895 Fixes sftp deletion on S3 backed filesystems
  src/main/java/sirius/biz/storage/layer3/downlink/ssh/BridgeFileSystem.java
  src/main/java/sirius/biz/storage/layer3/downlink/ssh/BridgePath.java
Labels: 🐛 Bugfix
