Repository scireum/sirius-biz, pull requests merged in 2023-09, with the labels that each got.

#1828 Fixes a missing method reference which was caused when changing the default language selection
  src/main/java/sirius/biz/tycho/kb/KnowledgeBase.java
  src/main/resources/default/kb/00000.html.pasta
Labels: 👶🏻 Trivial

#1829 Save Helper: Optional Suppression of Save Message
  pom.xml
  src/main/java/sirius/biz/web/SaveHelper.java
Labels: 🧬 Enhancement

#1830 SIRI-861: Adds support of displaying an appropriate Icon as Preview to Upload Fields
  src/main/resources/default/taglib/t/blobImageSoftRefField.html.pasta
Labels: 🧬 Enhancement

#1833 Changes ContactData phonenumber validation to non-strict
  pom.xml
  src/main/java/sirius/biz/model/ContactData.java
Labels: 🧬 Enhancement

#1832 SE-12943: Allows Configuring a Custom Number of retries for 503 Responses
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
  src/main/resources/component-biz.conf
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1834 SIRI-861: Minor Blob Upload Fix
  src/main/resources/default/assets/scripts/blob-upload-url-popover.js
  src/main/resources/default/taglib/t/blobImageSoftRefField.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1835 User Administration: Set Password and Revisions (SIRI-852)
  src/main/java/sirius/biz/tenants/ProfileController.java
  src/main/java/sirius/biz/tenants/UserAccountController.java
  src/main/java/sirius/biz/tenants/UserAccountData.java
  src/main/java/sirius/biz/tenants/jdbc/SQLUserAccountController.java
  src/main/java/sirius/biz/tenants/mongo/MongoUserAccountController.java
  src/main/resources/biz_de.properties
  src/main/resources/default/templates/biz/password/password-tycho.html.pasta
  src/main/resources/default/templates/biz/password/password.html.pasta
  src/main/resources/default/templates/biz/tenants/profile-change-password.html.pasta
  src/main/resources/default/templates/biz/tenants/select-user-account.html.pasta
  src/main/resources/default/templates/biz/tenants/user-account.html.pasta
  src/main/resources/default/templates/biz/tenants/user-accounts-list.html.pasta
  src/main/resources/default/templates/biz/tenants/user-accounts.html.pasta
Labels: 💣 BREAKING CHANGE

#1838 StoredIncidents: Limits errors messages in incident list to 5 lines
  src/main/java/sirius/biz/protocol/IncidentController.java
  src/main/resources/default/templates/biz/protocol/errors.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1841 Adds taglib for switching between different display modes of lists (SIRI-877)
  src/main/java/sirius/biz/tycho/ContentListLayout.java
  src/main/resources/default/assets/scripts/list-layout-switch.js
  src/main/resources/default/assets/scripts/tycho-biz.js.pasta
  src/main/resources/default/taglib/t/listLayoutSwitch.html.pasta
Labels: 🧬 Enhancement

#1843 Fixes an issue where paperclip files have not been deleted from the S3 storage, although they were older than the retention date
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java
Labels: 🐛 Bugfix

#1846 Data Explorer: Improves History Handling
  src/main/resources/default/templates/biz/tycho/analytics/data-explorer.html.pasta
Labels: 🐛 Bugfix

#1847 Data Explorer: Properly handles range and period in history
  src/main/resources/default/templates/biz/tycho/analytics/data-explorer.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1844 Storage: Only warns about a failing update task when deletion is queued
  src/main/java/sirius/biz/storage/layer1/replication/mongo/MongoReplicationTaskStorage.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1849 SIRI-873: Multi-Select Job Parameter Fixes
  src/main/java/sirius/biz/jobs/params/MultiSelectParameter.java
  src/main/java/sirius/biz/jobs/params/MultiSelectStringParameter.java
  src/main/java/sirius/biz/jobs/presets/JobPresetsController.java
  src/main/resources/default/templates/biz/jobs/job-parameters-logic.html.pasta
  src/main/resources/default/templates/biz/jobs/job.html.pasta
  src/main/resources/default/templates/biz/jobs/params/selectMultiString.html.pasta
Labels: 🐛 Bugfix

#1850 Tycho: Adds option to edit a smart value tenant
  pom.xml
  src/main/java/sirius/biz/tycho/smart/TenantSmartValueProvider.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1851 BREAKING: Uses new sirius JS clipboard helper
  pom.xml
  src/main/resources/default/assets/scripts/smart-values.js
  src/main/resources/default/extensions/tycho-page-menu/footer.html.pasta
  src/main/resources/default/taglib/k/section.html.pasta
  src/main/resources/default/templates/biz/storage/list.html.pasta
Labels: 💣 BREAKING CHANGE, ⬆️ Dependencies, 🛠️ Maintenance
