Repository scireum/sirius-biz, pull requests merged in 2023-06, with the labels that each got.

#1740 Calls super method to run required framework code
  src/main/java/sirius/biz/jobs/batch/file/FileImportJob.java
Labels: 🐛 Bugfix

#1741 Fixes readonly changes in uplinks
  src/main/java/sirius/biz/storage/layer3/uplink/cifs/CIFSUplink.java
  src/main/java/sirius/biz/storage/layer3/uplink/fs/LocalDirectoryUplink.java
  src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplink.java
Labels: 🐛 Bugfix

#1743 Uses appropriate filename in cifs fast move
  src/main/java/sirius/biz/storage/layer3/uplink/cifs/CIFSUplink.java
Labels: 🐛 Bugfix

#1742 Remembers user-preferences even when having switched to another tenant.
  src/main/java/sirius/biz/tenants/TenantUserManager.java
  src/main/java/sirius/biz/tenants/jdbc/SQLUserAccount.java
  src/main/java/sirius/biz/tenants/mongo/MongoUserAccount.java
Labels: 🐛 Bugfix

#1744 Permits to sum events over the provided mapping
  src/main/java/sirius/biz/analytics/events/EventRecorder.java
Labels: 🧬 Enhancement

#1745 Adds PackageData.ADDITIONAL_PERMISSIONS as extra filter in the tenants view.
  src/main/java/sirius/biz/tenants/mongo/MongoTenantController.java
  src/main/resources/biz_de.properties
Labels: 🧬 Enhancement

#1746 Statistics: Access Check
  src/main/java/sirius/biz/analytics/explorer/ChartFactory.java
Labels: 🐛 Bugfix

#1749 Checks the content-type received in VirtualFile.loadFromOutcall
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
Labels: 🧬 Enhancement

#1751 Hides deprecated additional features for which no translations exists.
  pom.xml
  src/main/java/sirius/biz/tenants/mongo/MongoTenantController.java
Labels: 🐛 Bugfix, 👶🏻 Trivial,  💣 BREAKING CHANGE

#1723 Moves /tenants and /user-accounts to Tycho
  src/main/java/sirius/biz/tenants/TenantData.java
  src/main/java/sirius/biz/tenants/TenantUserManager.java
  src/main/java/sirius/biz/tenants/UserAccountController.java
  src/main/java/sirius/biz/tenants/UserAccountData.java
  src/main/resources/biz_de.properties
  src/main/resources/component-biz.conf
  src/main/resources/default/assets/images/tenant_image_fallback.png
  src/main/resources/default/assets/images/user_image_fallback.png
  src/main/resources/default/assets/styles/blob-ref-field.scss
  src/main/resources/default/assets/styles/tycho-biz.scss
  src/main/resources/default/taglib/t/blobImageHardRefField.html.pasta
  src/main/resources/default/taglib/t/blobImageSoftRefField.html.pasta
  src/main/resources/default/templates/biz/packages/additional-and-revoked-permissions.html.pasta
  src/main/resources/default/templates/biz/packages/packages-and-upgrades.html.pasta
  src/main/resources/default/templates/biz/password/password-tycho-script.html.pasta
  src/main/resources/default/templates/biz/password/password-tycho.html.pasta
  src/main/resources/default/templates/biz/tenants/profile-change-password.html.pasta
  src/main/resources/default/templates/biz/tenants/profile.html.pasta
  src/main/resources/default/templates/biz/tenants/select-tenant.html.pasta
  src/main/resources/default/templates/biz/tenants/select-user-account.html.pasta
  src/main/resources/default/templates/biz/tenants/tenant-config.html.pasta
  src/main/resources/default/templates/biz/tenants/tenant-details-fields.html.pasta
  src/main/resources/default/templates/biz/tenants/tenant-details.html.pasta
  src/main/resources/default/templates/biz/tenants/tenant-extended.html.pasta
  src/main/resources/default/templates/biz/tenants/tenant-package.html.pasta
  src/main/resources/default/templates/biz/tenants/tenant-permissions.html.pasta
  src/main/resources/default/templates/biz/tenants/tenant-saml.html.pasta
  src/main/resources/default/templates/biz/tenants/tenant.html.pasta
  src/main/resources/default/templates/biz/tenants/tenants.html.pasta
  src/main/resources/default/templates/biz/tenants/user-account-config.html.pasta
  src/main/resources/default/templates/biz/tenants/user-account-details-fields.html.pasta
  src/main/resources/default/templates/biz/tenants/user-account-details.html.pasta
  src/main/resources/default/templates/biz/tenants/user-account.html.pasta
  src/main/resources/default/templates/biz/tenants/user-accounts.html.pasta
Labels:  💣 BREAKING CHANGE

#1752 Provides images in tenants an user accounts lists
  src/main/java/sirius/biz/tenants/TenantData.java
  src/main/java/sirius/biz/tenants/UserAccountController.java
  src/main/java/sirius/biz/tenants/UserAccountData.java
  src/main/resources/component-biz.conf
  src/main/resources/default/templates/biz/tenants/profile.html.pasta
  src/main/resources/default/templates/biz/tenants/select-tenant.html.pasta
  src/main/resources/default/templates/biz/tenants/select-user-account.html.pasta
  src/main/resources/default/templates/biz/tenants/tenant.html.pasta
  src/main/resources/default/templates/biz/tenants/tenants.html.pasta
  src/main/resources/default/templates/biz/tenants/user-account-details-fields.html.pasta
  src/main/resources/default/templates/biz/tenants/user-account-details.html.pasta
  src/main/resources/default/templates/biz/tenants/user-account.html.pasta
  src/main/resources/default/templates/biz/tenants/user-accounts.html.pasta
Labels:  💣 BREAKING CHANGE

#1756 Upgrades jupiter 2.2.0 -> 3.1.1
  docker-compose.yml
Labels: ⬆️ Dependencies

#1760 Add getter for value of sort field
  src/main/java/sirius/biz/mongo/SortField.java
Labels: 👶🏻 Trivial

#1762 Changes the order in which passwords and API-Tokens are checked
  src/main/java/sirius/biz/tenants/TenantUserManager.java
Labels: 👶🏻 Trivial

#1757 Fixes ES Index Health Job
  src/main/java/sirius/biz/elastic/ElasticIndexSizeReportJobFactory.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1765 Sirius upgrade
  pom.xml
Labels: 👶🏻 Trivial

#1766 Makes roles checkbox labels clickable
  src/main/resources/default/templates/biz/tenants/user-account-details-fields.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial
