Repository scireum/sirius-biz, pull requests merged in 2023-05, with the labels that each got.

#1700 SIRI-772 display message and don´t log calls to not-existing job
  src/main/java/sirius/biz/jobs/JobsController.java
  src/main/resources/biz_de.properties
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1697 copy salutation for resolving correct user-icon on tenant-switching
  src/main/java/sirius/biz/model/AddressData.java
  src/main/java/sirius/biz/model/InternationalAddressData.java
  src/main/java/sirius/biz/model/LoginData.java
  src/main/java/sirius/biz/model/PersonData.java
  src/main/java/sirius/biz/model/QueryController.java
  src/main/java/sirius/biz/tenants/AdditionalRolesProvider.java
  src/main/java/sirius/biz/tenants/ProfileController.java
  src/main/java/sirius/biz/tenants/TenantUserManager.java
  src/main/java/sirius/biz/tenants/UserAccountSearchProvider.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1708 EventRecorder: Allows counting distinct event field values
  src/main/java/sirius/biz/analytics/events/EventRecorder.java
Labels: 🧬 Enhancement

#1711 Increases the max runtime for some loops
  src/main/java/sirius/biz/storage/layer1/replication/ReplicationBackgroundLoop.java
  src/main/java/sirius/biz/storage/layer2/ProcessBlobChangesLoop.java
  src/main/java/sirius/biz/storage/layer2/TouchWritebackLoop.java
Labels: 👶🏻 Trivial

#1713 Adds Model.language in parallel to Model.lang
  src/main/resources/biz_de.properties
  src/main/resources/default/templates/biz/tenants/profile.html.pasta
  src/main/resources/default/templates/biz/tenants/tenant-details-fields.html.pasta
  src/main/resources/default/templates/biz/tenants/tenant-details.html.pasta
  src/main/resources/default/templates/biz/tenants/user-account-details-fields.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1714 Replaces PartCollection by List in order to get rid of the warning caused by it
  src/main/java/sirius/biz/storage/layer3/VirtualFileSystemController.java
Labels: 👶🏻 Trivial

#1717 Small improvements/fixes to JSON handling via Jackson
  src/main/java/sirius/biz/analytics/reports/ListCellFormat.java
  src/main/java/sirius/biz/codelists/LookupTable.java
  src/main/java/sirius/biz/translations/MultiLanguageString.java
  src/main/java/sirius/biz/translations/MultiLanguageStringProperty.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1721 Jackson: Fixes Small Bugs in Job Framework
  src/main/java/sirius/biz/analytics/reports/Cells.java
  src/main/java/sirius/biz/jobs/JobConfigData.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1720 Storage Framework meets read-only files
  src/main/java/sirius/biz/jobs/BasicJobFactory.java
  src/main/java/sirius/biz/jobs/batch/BatchProcessJobFactory.java
  src/main/java/sirius/biz/jobs/batch/file/FileImportJob.java
  src/main/java/sirius/biz/jobs/batch/file/FileImportJobFactory.java
  src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/Blob.java
  src/main/java/sirius/biz/storage/layer2/L3Uplink.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer3/ExtractArchiveJob.java
  src/main/java/sirius/biz/storage/layer3/FileSearch.java
  src/main/java/sirius/biz/storage/layer3/MutableVirtualFile.java
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
  src/main/java/sirius/biz/storage/layer3/VirtualFileSystemController.java
  src/main/java/sirius/biz/storage/layer3/downlink/ftp/BridgeFile.java
  src/main/java/sirius/biz/storage/layer3/uplink/ConfigBasedUplink.java
  src/main/java/sirius/biz/storage/layer3/uplink/cifs/CIFSUplink.java
  src/main/java/sirius/biz/storage/layer3/uplink/fs/LocalDirectoryUplink.java
  src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplink.java
  src/main/resources/biz_de.properties
  src/main/resources/default/assets/scripts/vfs-dropzone-and-modals.js.pasta
  src/main/resources/default/extensions/wondergem-page/storage-vfs-modals.html.pasta
  src/main/resources/default/templates/biz/storage/list.html.pasta
Labels:  💣 BREAKING CHANGE

#1725 Upgrades ClickHouse Container to 23.4.2.11
  docker-compose.yml
  src/test/resources/docker-compose.yml
Labels: 👶🏻 Trivial

#1727 Correctly converts the entry source from JSON to YAML for display in modal
  src/main/java/sirius/biz/codelists/LookupTableEntry.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1726 Adds support for user-preferences and fixes a caching bug in the TenantUserManager and extends tenant auto-setup
  src/main/java/sirius/biz/tenants/BaseTenantAutoSetup.java
  src/main/java/sirius/biz/tenants/TenantData.java
  src/main/java/sirius/biz/tenants/UserAccount.java
  src/main/java/sirius/biz/tenants/UserAccountData.java
  src/main/java/sirius/biz/tenants/jdbc/SQLTenantUserManager.java
  src/main/java/sirius/biz/tenants/jdbc/SQLUserAccount.java
  src/main/java/sirius/biz/tenants/mongo/MongoTenantUserManager.java
  src/main/java/sirius/biz/tenants/mongo/MongoUserAccount.java
  src/main/resources/component-biz.conf
Labels: 🧬 Enhancement, 🐛 Bugfix

#1728 Analytics: Scheduling Fixes
  src/main/java/sirius/biz/analytics/metrics/DailyMetricComputer.java
  src/main/java/sirius/biz/analytics/metrics/MetricComputerContext.java
  src/main/java/sirius/biz/analytics/metrics/MonthlyLargeMetricComputer.java
  src/main/java/sirius/biz/analytics/metrics/MonthlyMetricComputer.java
  src/main/java/sirius/biz/analytics/metrics/jdbc/SQLDailyGlobalMetricComputer.java
  src/main/java/sirius/biz/analytics/metrics/jdbc/SQLMonthlyGlobalMetricComputer.java
  src/main/java/sirius/biz/analytics/metrics/mongo/MongoDailyGlobalMetricComputer.java
  src/main/java/sirius/biz/analytics/metrics/mongo/MongoMonthlyGlobalMetricComputer.java
  src/main/java/sirius/biz/process/ProcessesDailyMetrics.java
  src/main/java/sirius/biz/process/ProcessesMonthlyMetrics.java
  src/main/java/sirius/biz/tenants/jdbc/SQLTenantGlobalMetricComputer.java
  src/main/java/sirius/biz/tenants/metrics/computers/TenantMetricComputer.java
  src/main/java/sirius/biz/tenants/metrics/computers/UserAccountAcademyMetricComputer.java
  src/main/java/sirius/biz/tenants/metrics/computers/UserAccountActivityMetricComputer.java
  src/main/java/sirius/biz/tenants/mongo/MongoTenantGlobalMetricComputer.java
Labels:  💣 BREAKING CHANGE

#1731 ES Upgrade - Removes TODOs
  src/main/java/sirius/biz/process/logs/ProcessLog.java
  src/main/java/sirius/biz/protocol/JournalData.java
  src/main/java/sirius/biz/protocol/Protocols.java
  src/main/resources/component-biz.conf
Labels: 👶🏻 Trivial

#1729 Changes the accepted file extension for XML-Exports to "zip"
  src/main/java/sirius/biz/jobs/batch/file/XMLExportJobFactory.java
Labels: 👶🏻 Trivial

#1732 Displays proper message if there are no video academy tracks
  src/main/resources/default/templates/biz/tycho/academy/tracks.html.pasta
Labels: 👶🏻 Trivial

#1738 Impedes updating contents of read-only files
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
Labels: 👶🏻 Trivial

#1739 Marks a config value as nullable
  src/main/java/sirius/biz/tenants/BaseTenantAutoSetup.java
Labels: 👶🏻 Trivial
