Repository scireum/sirius-biz, pull requests merged in 2023-10, with the labels that each got.

#1853 Tycho: Escapes single ticks in the dropzone upload URLs
  src/main/resources/default/taglib/t/blobImageHardRefField.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1854 Tenants: Uses identity converter for tenant and user images
  src/main/resources/component-biz.conf
  src/main/resources/default/taglib/t/blobImageHardRefField.html.pasta
Labels: 👶🏻 Trivial, 🛠️ Maintenance

#1855 Provides some codelist values for local testing
  develop.conf
Labels: 👶🏻 Trivial, 🛠️ Maintenance

#1856 Allows extensive process tables to scroll horizontally
  src/main/resources/default/templates/biz/process/process-output-table.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1857 Renames component conf to support a controlled load order
  pom.xml
  src/main/resources/component-070-biz.conf
Labels: 👶🏻 Trivial, 🛠️ Maintenance

#1860 Permits sorting lookup values by a given field.
  src/main/java/sirius/biz/codelists/LookupTable.java
Labels: 🧬 Enhancement

#1858 Switch project to Java 21
  .drone.yml
  pom.xml
  src/main/java/sirius/biz/ide/Scripting.java
  src/main/java/sirius/biz/jobs/batch/file/XMLValidator.java
  src/main/java/sirius/biz/locks/Locks.java
  src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
  src/main/java/sirius/biz/storage/s3/ObjectStores.java
  src/main/java/sirius/biz/tycho/updates/UpdatesReport.java
Labels: 💣 BREAKING CHANGE, 🛠️ Maintenance

#1861 Redirect to Safe Referers
  src/main/java/sirius/biz/web/BizController.java
Labels: 🧬 Enhancement

#1862 Referer Regex
  src/main/java/sirius/biz/web/BizController.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1863 Translates field when generating job documentation pages
  pom.xml
  src/main/java/sirius/biz/importer/format/BaseFieldDefinitionTransformer.java
Labels: 🧬 Enhancement, 👶🏻 Trivial
