Repository scireum/sirius-biz, pull requests merged in 2023-01, with the labels that each got.

#1555 Doesn't swallow exceptions in the completion handling of watchable streams
  src/main/java/sirius/biz/process/ProcessEnvironment.java
  src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplink.java
  src/main/java/sirius/biz/storage/layer3/uplink/sftp/SFTPUplink.java
  src/main/java/sirius/biz/storage/util/StorageUtils.java
  src/main/java/sirius/biz/storage/util/WatchableInputStream.java
  src/main/java/sirius/biz/storage/util/WatchableOutputStream.java
Labels: 🐛 Bugfix,  💣 BREAKING CHANGE

#1564 Adds a convenience method for hideWhen and boolean parameter
  src/main/java/sirius/biz/jobs/params/ParameterBuilder.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1563 Allows logging all messages without limitations.
  src/main/java/sirius/biz/jobs/BasicJobFactory.java
  src/main/java/sirius/biz/jobs/batch/file/FileImportJobFactory.java
  src/main/java/sirius/biz/process/ProcessEnvironment.java
  src/main/resources/biz_de.properties
Labels: 🧬 Enhancement

#1566 Invokes BlobCreatedRenamedHandler when updating the raw file
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1561 Replace all remaining lang to language
  pom.xml
  src/main/java/sirius/biz/tenants/TenantData.java
  src/main/java/sirius/biz/tenants/TenantUserManager.java
  src/main/java/sirius/biz/tenants/UserAccountData.java
  src/main/java/sirius/biz/tenants/jdbc/SQLTenantImportHandler.java
  src/main/java/sirius/biz/tenants/mongo/MongoTenantImportHandler.java
  src/main/java/sirius/biz/tycho/kb/KnowledgeBase.java
  src/main/java/sirius/biz/tycho/kb/KnowledgeBaseEntry.java
  src/main/java/sirius/biz/tycho/kb/SynchronizeArticlesTask.java
  src/main/resources/biz_bg.properties
  src/main/resources/biz_cs.properties
  src/main/resources/biz_da.properties
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
  src/main/resources/biz_es.properties
  src/main/resources/biz_fi.properties
  src/main/resources/biz_fr.properties
  src/main/resources/biz_hr.properties
  src/main/resources/biz_hu.properties
  src/main/resources/biz_it.properties
  src/main/resources/biz_lt.properties
  src/main/resources/biz_lv.properties
  src/main/resources/biz_nl.properties
  src/main/resources/biz_no.properties
  src/main/resources/biz_pl.properties
  src/main/resources/biz_pt.properties
  src/main/resources/biz_ro.properties
  src/main/resources/biz_ru.properties
  src/main/resources/biz_sk.properties
  src/main/resources/biz_sl.properties
  src/main/resources/biz_sr.properties
  src/main/resources/biz_sv.properties
  src/main/resources/biz_uk.properties
  src/main/resources/default/templates/biz/tenants/profile.html.pasta
  src/main/resources/default/templates/biz/tenants/tenant-details-fields.html.pasta
  src/main/resources/default/templates/biz/tenants/tenant-details.html.pasta
  src/main/resources/default/templates/biz/tenants/user-account-details-fields.html.pasta
  src/test/java/sirius/biz/translations/ESMultiLanguageStringEntity.java
  src/test/java/sirius/biz/translations/ESMultiLanguageStringPropertySpec.groovy
  src/test/java/sirius/biz/translations/MongoMultiLanguageStringPropertySpec.groovy
  src/test/java/sirius/biz/translations/SQLMultiLanguageStringPropertySpec.groovy
Labels:  💣 BREAKING CHANGE

#1567 SE-12352: Tenant Permission for Log Limit Job Parameter
  src/main/java/sirius/biz/jobs/BasicJobFactory.java
  src/main/java/sirius/biz/jobs/batch/file/FileImportJobFactory.java
  src/main/java/sirius/biz/process/ProcessEnvironment.java
  src/main/resources/biz_de.properties
  src/main/resources/component-biz.conf
Labels: 🧬 Enhancement

#1571 Tycho: Allows to overwrite the image style of the blobImage tag
  src/main/resources/default/taglib/t/blobImage.html.pasta
Labels: 👶🏻 Trivial

#1572 fix missing refactoring in templates for #1561
  src/main/resources/default/templates/biz/tenants/profile.html.pasta
  src/main/resources/default/templates/biz/tenants/tenant-details-fields.html.pasta
  src/main/resources/default/templates/biz/tenants/tenant-details.html.pasta
  src/main/resources/default/templates/biz/tenants/user-account-details-fields.html.pasta
Labels: 🐛 Bugfix

#1573 Always makes all metric schedulers visible
  src/main/java/sirius/biz/analytics/metrics/jdbc/SQLBestEffortDailyScheduler.java
  src/main/java/sirius/biz/analytics/metrics/jdbc/SQLGuaranteedDailyMetricScheduler.java
  src/main/java/sirius/biz/analytics/metrics/jdbc/SQLGuaranteedMonthlyScheduler.java
  src/main/java/sirius/biz/analytics/metrics/jdbc/SQLMonthlyLargeMetricsScheduler.java
  src/main/java/sirius/biz/analytics/metrics/mongo/MongoBestEffortDailyScheduler.java
  src/main/java/sirius/biz/analytics/metrics/mongo/MongoGuaranteedDailyMetricScheduler.java
  src/main/java/sirius/biz/analytics/metrics/mongo/MongoGuaranteedMonthlyScheduler.java
  src/main/java/sirius/biz/analytics/metrics/mongo/MongoMonthlyLargeMetricsScheduler.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1570 BREAKING: better handle blob changes
  src/main/java/sirius/biz/storage/layer2/BlobContentUpdatedHandler.java
  src/main/java/sirius/biz/storage/layer2/BlobCreatedHandler.java
  src/main/java/sirius/biz/storage/layer2/BlobRenamedHandler.java
  src/main/java/sirius/biz/storage/layer2/ProcessBlobChangesLoop.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLProcessBlobChangesLoop.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoProcessBlobChangesLoop.java
Labels:  💣 BREAKING CHANGE

#1574 Provides various improvements for import jobs.
  src/main/java/sirius/biz/importer/BaseImportHandler.java
  src/main/java/sirius/biz/importer/ImportHandler.java
  src/main/java/sirius/biz/importer/Importer.java
  src/main/java/sirius/biz/importer/MongoEntityImportHandler.java
  src/main/java/sirius/biz/importer/SQLEntityImportHandler.java
  src/main/java/sirius/biz/importer/format/ImportDictionary.java
  src/main/java/sirius/biz/jobs/batch/BatchJob.java
  src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedArchiveImportJob.java
  src/main/java/sirius/biz/jobs/batch/file/EntityExportJob.java
  src/main/java/sirius/biz/jobs/batch/file/EntityImportJob.java
  src/main/java/sirius/biz/jobs/batch/file/FileImportJob.java
  src/main/java/sirius/biz/jobs/batch/file/LineBasedArchiveImportJob.java
  src/main/java/sirius/biz/jobs/batch/file/LineBasedImportJob.java
  src/main/java/sirius/biz/jobs/batch/file/RelationalEntityImportJob.java
  src/main/java/sirius/biz/jobs/batch/file/XMLImportJob.java
  src/main/java/sirius/biz/process/ErrorContext.java
  src/main/java/sirius/biz/process/ProcessContext.java
  src/main/java/sirius/biz/process/ProcessEnvironment.java
  src/main/java/sirius/biz/process/Processes.java
  src/main/java/sirius/biz/process/logs/ProcessLog.java
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
Labels:  💣 BREAKING CHANGE
