Repository scireum/sirius-biz, pull requests merged in 2023-02, with the labels that each got.

#1580 properly output amountProperty in system/query/api
  src/main/java/sirius/biz/model/QueryController.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1581 Permits to better control how data is deleted in transaction data
  pom.xml
  src/main/java/sirius/biz/importer/txn/ImportTransactionHelper.java
  src/main/java/sirius/biz/jobs/batch/file/RelationalEntityImportJob.java
  src/main/java/sirius/biz/jobs/batch/file/RelationalEntityImportJobFactory.java
  src/main/java/sirius/biz/jobs/batch/file/SyncSourceDeleteMode.java
  src/main/java/sirius/biz/jobs/params/StringParameter.java
  src/main/resources/biz_de.properties
  src/main/resources/default/taglib/t/tracing.html.pasta
Labels:  💣 BREAKING CHANGE

#1586 Correctly formats the last modified millis to a local date time
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1587 Adds KBA about API response codes.
  src/main/resources/default/kb/de/user/response-codes.html.pasta
  src/main/resources/default/kb/en/user/response-codes.html.pasta
Labels: 👶🏻 Trivial

#1588 URLBuilder: Returns what kind of URL was generated
  src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/URLBuilder.java
Labels: 🧬 Enhancement

#1589 Properly warns, if an events isn't recorded due to on-save warnings.
  src/main/java/sirius/biz/analytics/events/EventRecorder.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1583 Whitelisting for the Noodle security sandbox
  src/main/java/sirius/biz/codelists/CodeListEntry.java
  src/main/java/sirius/biz/codelists/CodeListEntryData.java
  src/main/java/sirius/biz/codelists/CodeLists.java
  src/main/java/sirius/biz/model/AddressData.java
  src/main/java/sirius/biz/model/ContactData.java
  src/main/java/sirius/biz/model/LoginData.java
  src/main/java/sirius/biz/model/PermissionData.java
  src/main/java/sirius/biz/model/PersonData.java
  src/main/java/sirius/biz/storage/layer2/Blob.java
  src/main/java/sirius/biz/storage/layer2/BlobHardRef.java
  src/main/java/sirius/biz/storage/layer2/URLBuilder.java
  src/main/java/sirius/biz/storage/legacy/StoredObjectRef.java
  src/main/java/sirius/biz/tenants/Tenant.java
  src/main/java/sirius/biz/tenants/TenantData.java
  src/main/java/sirius/biz/web/TenantAware.java
  src/main/resources/component-biz.conf
Labels: 🧬 Enhancement

#1592 Outputs the counts in query tool in a more readable form
  src/main/java/sirius/biz/model/QueryController.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1594 Adds the referencedLabel argument to the associatedProcesses tag which defines the reference label for the query
  src/main/resources/default/taglib/t/associatedProcesses.html.pasta
Labels: 👶🏻 Trivial

#1595 Displays the canceled date when the job has not been completed properly (and therefore completed has not been set)
  src/main/resources/default/taglib/t/associatedProcesses.html.pasta
Labels: 👶🏻 Trivial

#1597 beautify system/query for small width
  src/main/resources/default/templates/biz/model/query-header.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1593 Permits to control which and how many computers are created by passin…
  src/main/java/sirius/biz/analytics/explorer/TimeSeriesChartFactory.java
  src/main/java/sirius/biz/process/NumberOfProcessesChart.java
  src/main/java/sirius/biz/process/ProcessDurationChart.java
  src/main/java/sirius/biz/tenants/metrics/AverageActivityPerTenantChart.java
  src/main/java/sirius/biz/tenants/metrics/AverageEducationPerTenantChart.java
  src/main/java/sirius/biz/tenants/metrics/NumberOfActiveTenantsChart.java
  src/main/java/sirius/biz/tenants/metrics/NumberOfActiveUsersChart.java
  src/main/java/sirius/biz/tenants/metrics/NumberOfActiveUsersPerTenantChart.java
  src/main/java/sirius/biz/tenants/metrics/NumberOfProcessesPerTenantChart.java
  src/main/java/sirius/biz/tenants/metrics/NumberOfTenantsChart.java
  src/main/java/sirius/biz/tenants/metrics/NumberOfUserInteractionsChart.java
  src/main/java/sirius/biz/tenants/metrics/NumberOfUserInteractionsPerTenantChart.java
  src/main/java/sirius/biz/tenants/metrics/ProcessDurationPerTenantChart.java
  src/main/java/sirius/biz/tycho/DashboardBrowserDistributionChart.java
  src/main/java/sirius/biz/tycho/DashboardPlatformDistributionChart.java
  src/main/java/sirius/biz/tycho/kb/KnowledgeBaseBrowserDistributionChart.java
  src/main/java/sirius/biz/tycho/kb/KnowledgeBaseEntryViewsChart.java
  src/main/java/sirius/biz/tycho/kb/KnowledgeBasePlatformDistributionChart.java
  src/main/java/sirius/biz/tycho/kb/KnowledgeBaseViewsChart.java
  src/main/java/sirius/biz/tycho/updates/NumberOfUpdateClicksChart.java
Labels: 👶🏻 Trivial,  💣 BREAKING CHANGE

#1599 enable search for codelist-autocomplete, fix typo
  src/main/java/sirius/biz/codelists/CodeListController.java
  src/main/java/sirius/biz/web/BasePageHelper.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1602 Whitelists more methods
  src/main/java/sirius/biz/codelists/CodeListEntryData.java
  src/main/java/sirius/biz/model/InternationalAddressData.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1603 Returns null for empty StringParameter
  src/main/java/sirius/biz/jobs/params/StringParameter.java
Labels: 🐛 Bugfix

#1604 Improve dropzone progress bar
  src/main/resources/default/assets/scripts/vfs-dropzone-and-modals.js
Labels: 🐛 Bugfix

#1605 SIRI-709 dropzone progress
  src/main/resources/default/assets/scripts/vfs-dropzone-and-modals.js
Labels: 🐛 Bugfix

#1606 VFS: Uses the correct timezone for outputting blob modified dates
  src/main/java/sirius/biz/storage/layer2/L3Uplink.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1610 BREAKING: adds a description to the file and auxFileMode parameter
  src/main/java/sirius/biz/jobs/batch/file/ArchiveImportJob.java
  src/main/java/sirius/biz/jobs/batch/file/FileImportJob.java
  src/main/java/sirius/biz/jobs/batch/file/FileImportJobFactory.java
  src/main/resources/biz_de.properties
Labels:  💣 BREAKING CHANGE

#1609 Adds missing NLS Key & Beautifies Login Page
  src/main/resources/biz_de.properties
  src/main/resources/default/templates/biz/login.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1611 Tycho: Code Style for process menu icon
  src/main/resources/default/extensions/tycho-page-menu/menu.html.pasta
Labels: 👶🏻 Trivial

#1612 MLS Text Area: Fixes layout of language selection
  src/main/resources/default/assets/javascript/multiLanguageField.js
  src/main/resources/default/assets/scripts/multi-language-field.js
  src/main/resources/default/assets/styles/multiLanguageField.scss
  src/main/resources/default/assets/stylesheets/multiLanguageField.scss
  src/main/resources/default/taglib/t/multiLanguageTextArea.html.pasta
  src/main/resources/default/taglib/w/multiLanguageTextArea.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1616 Adjusts the playtime icon for videos within the video academy to match the icon within the video content section
  src/main/resources/default/templates/biz/tycho/academy/video-card.html.pasta
Labels: 👶🏻 Trivial

#1614 Metrics: Queries the correct class for mongo user metrics
  src/main/java/sirius/biz/tenants/mongo/MongoTenantGlobalMetricComputer.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1613 Misc optimizations for Blob / BlobDispatcher and URLBuilder
  src/main/java/sirius/biz/storage/layer1/ObjectStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/Blob.java
  src/main/java/sirius/biz/storage/layer2/BlobDispatcher.java
  src/main/java/sirius/biz/storage/layer2/L3Uplink.java
  src/main/java/sirius/biz/storage/layer2/URLBuilder.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java
  src/main/java/sirius/biz/storage/layer3/VirtualFileSystemController.java
  src/main/resources/default/taglib/t/fileField.html.pasta
Labels:  💣 BREAKING CHANGE

#1619 Removes a double word
  src/main/resources/biz_de.properties
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1620 Adds a getter for the file extension of a blob
  src/main/java/sirius/biz/storage/layer2/Blob.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java
Labels: 👶🏻 Trivial

#1622 Allows error messages to wrap in details view
  src/main/resources/default/templates/biz/protocol/error.html.pasta
Labels: 👶🏻 Trivial, 🛠️ Maintenance

#1623 Preserves the intentional use of whitespace for formatting in tagliatelle errors
  src/main/resources/default/templates/biz/protocol/error.html.pasta
Labels: 👶🏻 Trivial, 🛠️ Maintenance

#1630 Adds a warning popup when someone tries to leave the page while a file is uploaded
  src/main/resources/default/assets/scripts/vfs-dropzone-and-modals.js
Labels: 👶🏻 Trivial

#1629 use required, because input-required isn´t present in tycho and set placeholder
  src/main/java/sirius/biz/storage/layer3/VirtualFileSystemController.java
  src/main/resources/default/templates/biz/storage/list.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1628 use text-muted for tycho-templates as muted isn´t present anymore
  src/main/resources/default/templates/biz/cluster/cluster.html.pasta
  src/main/resources/default/templates/biz/model/schema.html.pasta
  src/main/resources/default/templates/biz/protocol/errors.html.pasta
  src/main/resources/default/templates/biz/protocol/protocol.html.pasta
  src/main/resources/default/templates/biz/storage/list.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1626 add check for undefined result if result is empty
  src/main/resources/default/templates/biz/model/sql.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1621 Removes unused config & unifies layout in the jobs header
  src/main/resources/component-biz.conf
  src/main/resources/default/templates/biz/jobs/jobs.html.pasta
Labels: 👶🏻 Trivial, 🛠️ Maintenance

#1627 Ignores ClosedChannelException.
  src/main/java/sirius/biz/storage/layer1/ObjectStorageSpace.java
Labels: 🐛 Bugfix, 👶🏻 Trivial
