Repository scireum/sirius-biz, pull requests merged in 2023-07, with the labels that each got.

#1767 Prioritize the fallback value reading from disabled multi-language strings
  src/main/java/sirius/biz/translations/MultiLanguageString.java
Labels: 🐛 Bugfix

#1768 Properly disables all attached permissions if revoked permissions contains a profile
  pom.xml
  src/main/java/sirius/biz/packages/PackageData.java
  src/main/java/sirius/biz/tenants/TenantUserManager.java
Labels: 🐛 Bugfix

#1772 Provides a framework to check customization flags.
  src/main/java/sirius/biz/tenants/Tenant.java
  src/main/java/sirius/biz/tenants/flags/CustomizationFlag.java
  src/main/java/sirius/biz/tenants/flags/CustomizationFlags.java
  src/main/java/sirius/biz/tenants/flags/README.md
  src/main/java/sirius/biz/tenants/jdbc/SQLTenant.java
  src/main/java/sirius/biz/tenants/mongo/MongoTenant.java
  src/main/resources/default/kb/en/admin/customization-flags.html.pasta
Labels: 🧬 Enhancement

#1773 Improves reporting for CustomizationFlags
  src/main/java/sirius/biz/tenants/flags/CustomizationFlag.java
  src/main/java/sirius/biz/tenants/flags/CustomizationFlags.java
  src/main/resources/default/kb/en/system/customization-flags.html.pasta
Labels: 🧬 Enhancement,  💣 BREAKING CHANGE

#1774 Improves the UIs for tenants and user-accounts
  src/main/resources/biz_de.properties
  src/main/resources/default/templates/biz/tenants/tenants-list.html.pasta
  src/main/resources/default/templates/biz/tenants/user-account.html.pasta
  src/main/resources/default/templates/biz/tenants/user-accounts-list.html.pasta
Labels: 🧬 Enhancement

#1775 Use proper method for ftp access when checking for readonly
  src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplink.java
Labels: 🐛 Bugfix

#1776 Fixes permissions check for FTP servers not delivering any information
  src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplink.java
Labels: 🐛 Bugfix

#1777 Executes the tenant export job in the original tenant while spying another user
  src/main/java/sirius/biz/tenants/mongo/MongoTenantExportJobFactory.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1778 SIRI-837: Fix Pagination on Tenant Select Page
  src/main/resources/default/templates/biz/tenants/select-tenant.html.pasta
Labels: 🐛 Bugfix

#1780 Fixes ftp upload
  src/main/java/sirius/biz/storage/layer3/downlink/ftp/BridgeFile.java
Labels: 🐛 Bugfix

#1781 SIRI-839 fix ftp upload to root
  src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplink.java
Labels: 🐛 Bugfix

#1783 Read-Out of Multi-Language-Strings for All Users (OX-10242)
  src/main/java/sirius/biz/translations/MultiLanguageString.java
Labels: 🐛 Bugfix, 👶🏻 Trivial, 🔥 Hotfix

#1782 Improves the tenant deletion job
  pom.xml
  src/main/java/sirius/biz/tenants/deletion/DeleteTenantJobFactory.java
  src/main/resources/biz_de.properties
  src/main/resources/default/templates/biz/tenants/tenants-list.html.pasta
Labels: 🔥 Hotfix

#1786 LookupTables: Adds method to force resolve the name
  src/main/java/sirius/biz/codelists/LookupTable.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1758 Refactors the download of remote files into our storage
  src/main/java/sirius/biz/storage/layer3/HeadRequestFileResolver.java
  src/main/java/sirius/biz/storage/layer3/PathAndQueryStringFileResolver.java
  src/main/java/sirius/biz/storage/layer3/RemoteFileResolver.java
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
  src/test/java/sirius/biz/storage/layer3/VirtualFileTest.java
  src/test/kotlin/sirius/biz/storage/layer3/VirtualFileTest.kt
Labels: 🧬 Enhancement,  💣 BREAKING CHANGE

#1759 Implements a RemoteFileResolver for /dasd/ storage paths
  src/main/java/sirius/biz/storage/layer2/BlobDispatcher.java
  src/main/java/sirius/biz/storage/layer2/BlobUri.java
  src/main/java/sirius/biz/storage/layer2/BlobUriParser.java
  src/main/java/sirius/biz/storage/layer3/BlobUriFileResolver.java
  src/test/kotlin/sirius/biz/storage/layer2/BlobUriParserTest.kt
  src/test/kotlin/sirius/biz/storage/layer3/VirtualFileTest.kt
Labels: 🧬 Enhancement

#1788 Makes sure that the delete button is only rendered when the user has the associated permission
  src/main/resources/default/templates/biz/tenants/user-account.html.pasta
  src/main/resources/default/templates/biz/tenants/user-accounts-list.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial, 🔥 Hotfix

#1787 Adds three helper methods for counting events in the last month, last year and last 12 months
  src/main/java/sirius/biz/analytics/events/EventRecorder.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1790 Upgrades sirius web from dev-67.7.2 to dev-67.7.4
  pom.xml
Labels: 👶🏻 Trivial, 🛠️ Maintenance

#1789 Retries downloading remote files
  src/main/java/sirius/biz/storage/layer3/HeadRequestFileResolver.java
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
Labels: 🧬 Enhancement

#1796 move editor.resize() to proper location
  src/main/resources/default/templates/biz/tenants/tenant-config.html.pasta
  src/main/resources/default/templates/biz/tenants/user-account-config.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1784 Supports lookup tables defined directly in the test configuration file
  src/main/java/sirius/biz/codelists/CodeLists.java
  src/main/java/sirius/biz/codelists/ConfigLookupTable.java
  src/main/java/sirius/biz/codelists/LookupTables.java
  src/test/kotlin/sirius.biz.codelists/LookupTablesTest.kt
  src/test/resources/test.conf
Labels: 🧬 Enhancement

#1770 Event Cleanup + Code Inspection Fixes
  docker-compose.yml
  src/main/java/sirius/biz/analytics/events/Event.java
  src/main/java/sirius/biz/analytics/events/EventRecorder.java
  src/main/java/sirius/biz/analytics/events/PageImpressionEvent.java
  src/main/java/sirius/biz/analytics/events/UserActivityEvent.java
  src/main/java/sirius/biz/analytics/explorer/BrowserDistributionTimeSeriesComputer.java
  src/main/java/sirius/biz/analytics/explorer/EventTimeSeriesComputer.java
  src/main/java/sirius/biz/analytics/explorer/PlatformDistributionTimeSeriesComputer.java
  src/main/java/sirius/biz/codelists/LookupTable.java
  src/main/java/sirius/biz/importer/AutoImport.java
  src/main/java/sirius/biz/isenguard/IPBlockedEvent.java
  src/main/java/sirius/biz/isenguard/Isenguard.java
  src/main/java/sirius/biz/isenguard/RateLimitingTriggeredEvent.java
  src/main/java/sirius/biz/process/ProcessContext.java
  src/main/java/sirius/biz/storage/layer2/variants/BlobConversionEvent.java
  src/main/java/sirius/biz/storage/layer3/VirtualFileSystem.java
  src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplink.java
  src/main/java/sirius/biz/storage/legacy/BucketInfo.java
  src/main/java/sirius/biz/storage/legacy/Storage.java
  src/main/java/sirius/biz/storage/legacy/StorageController.java
  src/main/java/sirius/biz/storage/legacy/UpdatingOutputStream.java
  src/main/java/sirius/biz/storage/legacy/VersionManager.java
  src/main/java/sirius/biz/storage/legacy/VersionedFiles.java
  src/main/java/sirius/biz/storage/legacy/VirtualObject.java
  src/main/java/sirius/biz/tenants/TenantSearchProvider.java
  src/main/java/sirius/biz/tenants/deletion/DeleteTenantTask.java
  src/main/java/sirius/biz/tenants/jdbc/SQLUserAccountController.java
  src/main/java/sirius/biz/tycho/updates/UpdateClickEvent.java
  src/main/java/sirius/biz/util/SOAPCallEvent.java
  src/main/resources/biz_fi.properties
  src/main/resources/biz_nl.properties
  src/test/java/sirius/biz/analytics/events/TestEvent1.java
  src/test/java/sirius/biz/analytics/events/TestEvent2.java
  src/test/java/sirius/biz/analytics/events/TestEvent3ThrowsExceptionOnSave.java
  src/test/java/sirius/biz/web/autoloading/AutoLoadController.java
  src/test/resources/docker-compose.yml
Labels: 🧬 Enhancement,  💣 BREAKING CHANGE

#1798 Migrates some tests to jUnit5 + Kotlin
  src/main/java/sirius/biz/analytics/events/EventRecorder.java
  src/test/java/sirius/biz/analytics/events/EventRecorderSpec.groovy
  src/test/java/sirius/biz/analytics/indicators/IndicatorSpec.groovy
  src/test/java/sirius/biz/cluster/RedisUserMessageCacheSpec.groovy
  src/test/java/sirius/biz/cluster/work/DistributedTasksSpec.groovy
  src/test/java/sirius/biz/cluster/work/FifoQueueSpec.groovy
  src/test/java/sirius/biz/cluster/work/NamedCounterSpec.groovy
  src/test/java/sirius/biz/cluster/work/PrioritizedQueueSpec.groovy
  src/test/java/sirius/biz/codelists/CodeListsSpec.groovy
  src/test/java/sirius/biz/elastic/SearchableEntitySpec.groovy
  src/test/kotlin/sirius/biz/analytics/events/EventRecorderTest.kt
  src/test/kotlin/sirius/biz/analytics/indicators/IndicatorTest.kt
  src/test/kotlin/sirius/biz/cluster/RedisUserMessageCacheTest.kt
  src/test/kotlin/sirius/biz/cluster/work/DistributedTasksTest.kt
  src/test/kotlin/sirius/biz/cluster/work/FifoQueueTest.kt
  src/test/kotlin/sirius/biz/cluster/work/NamedCounterTest.kt
  src/test/kotlin/sirius/biz/cluster/work/PrioritizedQueueTest.kt
  src/test/kotlin/sirius/biz/codelists/CodeListsTest.kt
  src/test/kotlin/sirius/biz/elastic/SearchableEntityTest.kt
Labels: 🛠️ Maintenance

#1799 Replaces usages of ContentHelper with equivalents from StringCleanup
  pom.xml
  src/main/java/sirius/biz/analytics/reports/CSSCellFormat.java
  src/main/java/sirius/biz/analytics/reports/Cells.java
  src/main/java/sirius/biz/analytics/reports/LinkCellFormat.java
  src/main/java/sirius/biz/analytics/reports/ListCellFormat.java
  src/main/java/sirius/biz/analytics/reports/TrendCellFormat.java
  src/main/java/sirius/biz/tycho/search/OpenSearchResult.java
Labels: 👶🏻 Trivial

#1802 SIRI-814: Fix Exporting SQL Results
  src/main/java/sirius/biz/jdbc/DatabaseController.java
  src/main/java/sirius/biz/jdbc/DatabaseDisplayUtils.java
  src/main/java/sirius/biz/jdbc/ExportQueryResultJobFactory.java
Labels: 🐛 Bugfix

#1804 Adds a method which counts the number of events which have occurred in the given calendar month based on the given queryTuner
  src/main/java/sirius/biz/analytics/events/EventRecorder.java
Labels: 🧬 Enhancement
