Repository scireum/sirius-biz, pull requests merged in 2023-04, with the labels that each got.

#1668 /system/query: Appends query parameters to the URL on submit
  src/main/resources/default/templates/biz/model/query-header.html.pasta
Labels: 🧬 Enhancement

#1665 adjust styling for job-preset-list on job page
  src/main/resources/default/templates/biz/jobs/job.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1669 Fixes and improves blob cache invalidation
  src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
Labels: 🐛 Bugfix

#1670 Corrects the path for the VFS
  src/main/resources/default/taglib/t/blobImageSoftRefField.html.pasta
Labels: 🐛 Bugfix

#1671 Metrics: Unifies class naming and package structure
  src/main/java/sirius/biz/tenants/jdbc/SQLTenantGlobalMetricComputer.java
  src/main/java/sirius/biz/tenants/jdbc/SQLTenantMetricComputer.java
  src/main/java/sirius/biz/tenants/jdbc/SQLUserAccountAcademyMetricComputer.java
  src/main/java/sirius/biz/tenants/jdbc/SQLUserAccountActivityMetricComputer.java
  src/main/java/sirius/biz/tenants/metrics/charts/AverageActivityForTenantChart.java
  src/main/java/sirius/biz/tenants/metrics/charts/AverageEducationForTenantChart.java
  src/main/java/sirius/biz/tenants/metrics/charts/NumberOfActiveTenantsChart.java
  src/main/java/sirius/biz/tenants/metrics/charts/NumberOfActiveUsersChart.java
  src/main/java/sirius/biz/tenants/metrics/charts/NumberOfActiveUsersForTenantChart.java
  src/main/java/sirius/biz/tenants/metrics/charts/NumberOfProcessesForTenantChart.java
  src/main/java/sirius/biz/tenants/metrics/charts/NumberOfTenantsChart.java
  src/main/java/sirius/biz/tenants/metrics/charts/NumberOfUserInteractionsChart.java
  src/main/java/sirius/biz/tenants/metrics/charts/NumberOfUserInteractionsForTenantChart.java
  src/main/java/sirius/biz/tenants/metrics/charts/ProcessDurationForTenantChart.java
  src/main/java/sirius/biz/tenants/metrics/charts/TenantResolver.java
  src/main/java/sirius/biz/tenants/metrics/computers/GlobalTenantMetricComputer.java
  src/main/java/sirius/biz/tenants/metrics/computers/TenantMetricComputer.java
  src/main/java/sirius/biz/tenants/metrics/computers/UserAccountAcademyMetricComputer.java
  src/main/java/sirius/biz/tenants/metrics/computers/UserAccountActivityMetricComputer.java
  src/main/java/sirius/biz/tenants/mongo/MongoTenantGlobalMetricComputer.java
  src/main/java/sirius/biz/tenants/mongo/MongoTenantMetricComputer.java
  src/main/java/sirius/biz/tenants/mongo/MongoUserAccountAcademyMetricComputer.java
  src/main/java/sirius/biz/tenants/mongo/MongoUserAccountActivityMetricComputer.java
  src/main/resources/biz_bg.properties
  src/main/resources/biz_cs.properties
  src/main/resources/biz_da.properties
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
  src/main/resources/biz_es.properties
  src/main/resources/biz_fi.properties
  src/main/resources/biz_fr.properties
  src/main/resources/biz_hr.properties
  src/main/resources/biz_hu.properties
  src/main/resources/biz_it.properties
  src/main/resources/biz_lt.properties
  src/main/resources/biz_lv.properties
  src/main/resources/biz_nl.properties
  src/main/resources/biz_no.properties
  src/main/resources/biz_pl.properties
  src/main/resources/biz_pt.properties
  src/main/resources/biz_ro.properties
  src/main/resources/biz_ru.properties
  src/main/resources/biz_sk.properties
  src/main/resources/biz_sl.properties
  src/main/resources/biz_sr.properties
  src/main/resources/biz_sv.properties
  src/main/resources/biz_uk.properties
Labels:  💣 BREAKING CHANGE, 🛠️ Maintenance

#1662 Brings job-documentation to Tycho
  src/main/java/sirius/biz/jobs/BasicJobFactory.java
  src/main/java/sirius/biz/jobs/batch/file/EntityExportJobFactory.java
  src/main/java/sirius/biz/jobs/batch/file/EntityImportJobFactory.java
  src/main/java/sirius/biz/jobs/batch/file/RelationalEntityImportJobFactory.java
  src/main/java/sirius/biz/jobs/infos/CardInfo.java
  src/main/java/sirius/biz/jobs/infos/JobInfoCollector.java
  src/main/resources/default/taglib/t/report.html.pasta
  src/main/resources/default/templates/biz/jobs/infos.html.pasta
  src/main/resources/default/templates/biz/jobs/infos/card.html.pasta
  src/main/resources/default/templates/biz/jobs/infos/heading.html.pasta
  src/main/resources/default/templates/biz/jobs/infos/report.html.pasta
  src/main/resources/default/templates/biz/jobs/infos/well.html.pasta
Labels: 🧬 Enhancement,  💣 BREAKING CHANGE

#1672 Permits to start conversions from a local file
  src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/Blob.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java
  src/main/java/sirius/biz/storage/layer2/variants/ConversionProcess.java
Labels: 🧬 Enhancement

#1677 Fixes a format string
  src/main/java/sirius/biz/storage/s3/ObjectStore.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1676 Fixes moving of files via SFTP
  src/main/java/sirius/biz/storage/layer3/downlink/ssh/BridgeFileSystemProvider.java
  src/main/java/sirius/biz/storage/layer3/downlink/ssh/sftp/BridgeFileSystemAccessor.java
Labels: 🐛 Bugfix

#1682 Data-Explorer: Improves Header Actions
  src/main/resources/biz_de.properties
  src/main/resources/default/templates/biz/tycho/analytics/data-explorer.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1683 Enhances the parsing of a VirtualFile's path from a given URI
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
  src/test/java/sirius/biz/storage/layer3/VirtualFileTest.java
Labels: 🧬 Enhancement

#1684 Adds an export btn / route to the Data-Explorer
  src/main/java/sirius/biz/analytics/explorer/ChartFactory.java
  src/main/java/sirius/biz/analytics/explorer/DataExplorerController.java
  src/main/java/sirius/biz/analytics/explorer/TimeSeriesChartFactory.java
  src/main/java/sirius/biz/analytics/explorer/TimeSeriesData.java
  src/main/resources/biz_de.properties
  src/main/resources/default/templates/biz/tycho/analytics/data-explorer.html.pasta
Labels: 🧬 Enhancement

#1687 Provides a simple way for inserting help/user assistance into backed …
  src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/BlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer3/VirtualFileSystemController.java
  src/main/java/sirius/biz/tycho/UserAssistant.java
  src/main/resources/component-biz.conf
  src/main/resources/default/extensions/tycho-page-header/user-assistant.html.pasta
Labels: 🧬 Enhancement

#1689 Properly checks if a setting is present, before reading it.
  src/main/java/sirius/biz/tycho/UserAssistant.java
Labels: 🐛 Bugfix

#1686 Temporarily reduce the length of logged incidences, mails, and messages
  src/main/java/sirius/biz/protocol/Protocols.java
  src/main/resources/component-biz.conf
Labels: 🐛 Bugfix

#1690 Minor Fixes
  src/main/resources/biz_de.properties
  src/main/resources/default/taglib/t/videoAcademyBtn.html.pasta
  src/main/resources/default/templates/biz/tycho/analytics/data-explorer.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1693 Fixes the export feature of the DataExplorer: now values are being exported properly
  src/main/java/sirius/biz/analytics/explorer/ChartFactory.java
  src/main/java/sirius/biz/analytics/explorer/DataExplorerController.java
  src/main/java/sirius/biz/analytics/explorer/TimeSeriesChartFactory.java
Labels: 🐛 Bugfix

#1696 Only attempts to perform a lookup for sane / plausible / working paths.
  src/main/java/sirius/biz/tycho/UserAssistant.java
Labels: 🐛 Bugfix

#1699 Temporarily reduces more ES message fields
  src/main/java/sirius/biz/process/logs/ProcessLog.java
  src/main/java/sirius/biz/protocol/JournalData.java
Labels: 🐛 Bugfix, 🔥 Hotfix

#1701 Permits DataExplorer charts to take their time when computing a chart.
  src/main/java/sirius/biz/analytics/explorer/DataExplorerController.java
Labels: 🐛 Bugfix, 👶🏻 Trivial, 🔥 Hotfix

#1703 Fixes an unhandled exception within the ConversionEngine by adding a tenant id check
  src/main/java/sirius/biz/storage/layer2/variants/ConversionEngine.java
Labels: 🐛 Bugfix

#1704 Enhances the usability and user experience of the dropzone (t:fileField)
  src/main/resources/default/assets/scripts/tycho-biz.js.pasta
  src/main/resources/default/assets/scripts/vfs-dropzone-and-modals.js
  src/main/resources/default/assets/scripts/vfs-dropzone-and-modals.js.pasta
  src/main/resources/default/taglib/t/fileField.html.pasta
Labels: 🧬 Enhancement
