Repository scireum/sirius-biz, pull requests merged in 2023-08, with the labels that each got.

#1805 SQL: Switches query input field to textarea
  pom.xml
  src/main/java/sirius/biz/ide/Scripting.java
  src/main/java/sirius/biz/jdbc/DatabaseController.java
  src/main/resources/default/templates/biz/model/sql.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1803 Reduces elements per page from 25 to 24
  src/main/java/sirius/biz/web/BasePageHelper.java
Labels: 👶🏻 Trivial

#1808 Adds a method which calculates the cumulative sum of metrics, commencing from the specified startDate and continuing until the untilDate is reached
  src/main/java/sirius/biz/analytics/metrics/MetricQuery.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1810 Jupiter: Usability for Products without the Tenant Framework
  src/main/java/sirius/biz/analytics/explorer/EntityChartObjectResolver.java
  src/main/java/sirius/biz/jupiter/JupiterSync.java
  src/main/java/sirius/biz/jupiter/JupiterSyncSystemTenantSupplier.java
  src/main/java/sirius/biz/tenants/flags/CustomizationFlags.java
Labels: 🧬 Enhancement

#1812 KB: Allows to easily copy the deeplink of an article section
  src/main/resources/default/taglib/k/section.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1806 enhance css on saml-login-page - now the whole card is clickable
  src/main/resources/default/templates/biz/tenants/saml.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1811 Processes: Allows to attach kba link to a log message
  src/main/java/sirius/biz/tycho/kb/OpenKbaLogHandler.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1814 Improves process deletion and persistence changes
  src/main/java/sirius/biz/process/DeleteExpiredProcessesTask.java
  src/main/java/sirius/biz/process/Process.java
  src/main/java/sirius/biz/process/Processes.java
  src/main/java/sirius/biz/process/logs/ProcessLog.java
Labels: 🧬 Enhancement, 🐛 Bugfix

#1815 t:blobHardRefImage: uses the high-res default image from URLBuilder.IMAGE_FALLBACK_URI
  src/main/resources/default/taglib/t/blobImageHardRefField.html.pasta
Labels: 👶🏻 Trivial

#1817 Adds a convenient method to the Metrics framework which fetches the metric values of the last 12 months for the given entity
  src/main/java/sirius/biz/analytics/metrics/BasicMetrics.java
  src/main/java/sirius/biz/analytics/metrics/Metrics.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1785 Moves FTP KBA from oxomi to sirius and generalises formulations
  src/main/java/sirius/biz/storage/layer3/downlink/ftp/FTPServer.java
  src/main/java/sirius/biz/storage/layer3/downlink/ssh/SSHServer.java
  src/main/java/sirius/biz/tenants/AdditionalRolesProvider.java
  src/main/resources/component-biz.conf
  src/main/resources/default/kb/de/user/ftp-import.html.pasta
Labels: 🖐 Keep open

#1818 Validates mail addresses and phone numbers via new shared `PropertyValidators`
  pom.xml
  src/main/java/sirius/biz/model/ContactData.java
  src/main/java/sirius/biz/tenants/EmailAddressValidator.java
  src/main/java/sirius/biz/tenants/PhoneNumberValidator.java
  src/main/java/sirius/biz/tenants/UserAccountData.java
  src/test/java/sirius/biz/model/ContactDataTest.java
  src/test/kotlin/sirius/biz/tenants/ContactDataTestEntity.kt
  src/test/kotlin/sirius/biz/tenants/PhoneNumberValidatorTest.kt
Labels: 🧬 Enhancement

#1819 Focuses first field im MLS modal when it is opened
  src/main/resources/default/assets/javascript/multiLanguageField.js
  src/main/resources/default/assets/scripts/multi-language-field.js
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1820 Improves saving multi-language-strings lacking i18n permission
  src/main/java/sirius/biz/translations/MultiLanguageStringProperty.java
  src/test/java/sirius/biz/translations/ESMultiLanguageStringPropertySpec.groovy
  src/test/java/sirius/biz/translations/MongoMultiLanguageStringPropertySpec.groovy
  src/test/java/sirius/biz/translations/MultiLanguageStringSpec.groovy
  src/test/java/sirius/biz/translations/SQLMultiLanguageStringPropertySpec.groovy
  src/test/kotlin/sirius/biz/translations/ESMultiLanguageStringPropertyTest.kt
  src/test/kotlin/sirius/biz/translations/MongoMultiLanguageStringPropertyTest.kt
  src/test/kotlin/sirius/biz/translations/MultiLanguageStringTest.kt
  src/test/kotlin/sirius/biz/translations/SQLMultiLanguageStringPropertyTest.kt
Labels: 🧬 Enhancement, 🐛 Bugfix

#1822 Updates to breaking sirius-web and sirius-db
  pom.xml
  src/main/java/sirius/biz/mongo/SortField.java
  src/main/java/sirius/biz/process/ProcessContext.java
Labels: 👶🏻 Trivial, 💣 BREAKING CHANGE

#1824 Introduces the Blob.duplicate() method
  src/main/java/sirius/biz/storage/layer1/FSObjectStorageSpace.java
  src/main/java/sirius/biz/storage/layer1/ObjectStorageSpace.java
  src/main/java/sirius/biz/storage/layer1/S3ObjectStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/Blob.java
  src/main/java/sirius/biz/storage/layer2/BlobDuplicator.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java
  src/main/java/sirius/biz/storage/s3/ObjectStore.java
Labels: 🧬 Enhancement

#1827 BREAKING: KBA - Remodels the fallback language mechanism for the knowledgebase system in order to support multiple fallback languages
  src/main/java/sirius/biz/tycho/kb/KnowledgeBase.java
  src/main/java/sirius/biz/tycho/kb/README.md
  src/main/resources/component-biz.conf
Labels: 🧬 Enhancement, 💣 BREAKING CHANGE
