Repository scireum/sirius-biz, pull requests merged in 2023-12, with the labels that each got.

#1897 Properly calculates parent hierarchy
  src/main/java/sirius/biz/storage/layer3/downlink/ssh/BridgePath.java
Labels: 🐛 Bugfix

#1900 Simplifies code by utilizing sequenced collection helpers
  src/main/java/sirius/biz/analytics/explorer/TimeSeries.java
  src/main/java/sirius/biz/analytics/metrics/MetricQuery.java
  src/main/java/sirius/biz/codelists/LookupTableController.java
  src/main/java/sirius/biz/ide/Scripting.java
  src/main/java/sirius/biz/ide/ScriptingController.java
  src/main/java/sirius/biz/importer/format/AllInListCheck.java
  src/main/java/sirius/biz/storage/layer2/L3Uplink.java
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
  src/main/java/sirius/biz/tenants/UserAccountController.java
  src/main/java/sirius/biz/tycho/academy/OnboardingEngine.java
  src/main/java/sirius/biz/tycho/kb/KnowledgeBase.java
  src/main/java/sirius/biz/tycho/kb/KnowledgeBaseArticle.java
  src/main/java/sirius/biz/tycho/kb/SynchronizeArticlesTask.java
  src/main/java/sirius/biz/web/BasePageHelper.java
Labels: 🎁 Next version, 🛠️ Maintenance

#1903 Fuzzy matches entity names in Query Tool
  src/main/java/sirius/biz/model/QueryController.java
Labels: 🧬 Enhancement, 🎁 Next version

#1902 Adds progress tracking to processes
  src/main/java/sirius/biz/process/ProcessContext.java
  src/main/java/sirius/biz/process/ProcessEnvironment.java
  src/main/java/sirius/biz/process/ProgressTracker.java
  src/main/resources/biz_de.properties
Labels: 🧬 Enhancement

#1899 Fixes alignment for tenant permission table in safari
  src/main/resources/default/templates/biz/packages/additional-and-revoked-permissions.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1904 Redirects to the correct KB entry point on typo
  src/main/java/sirius/biz/tycho/kb/KnowledgeBaseController.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1901 Implementation of PageHelper::withTotalCount()
  src/main/java/sirius/biz/process/output/ChartProcessOutputType.java
  src/main/java/sirius/biz/process/output/LogsProcessOutputType.java
  src/main/java/sirius/biz/process/output/TableProcessOutputType.java
  src/main/java/sirius/biz/protocol/AuditLogController.java
  src/main/java/sirius/biz/protocol/IncidentController.java
  src/main/java/sirius/biz/protocol/JournalController.java
  src/main/java/sirius/biz/protocol/LogController.java
  src/main/java/sirius/biz/protocol/MailController.java
Labels: 🧬 Enhancement, 🎁 Next version

#1908 Locks Command
  src/main/java/sirius/biz/locks/LocksCommand.java
Labels: 🧬 Enhancement

#1909 Permits to check if a transactional entity can be deleted
  src/main/java/sirius/biz/importer/txn/ImportTransactionHelper.java
Labels: 🧬 Enhancement

#1907 Fetches total count for blobs in VFS-UI
  src/main/java/sirius/biz/storage/layer2/L3Uplink.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1906 streamBlockwise deletions SIRI-915
  pom.xml
  src/main/java/sirius/biz/process/DeleteExpiredProcessesTask.java
  src/main/java/sirius/biz/storage/layer1/replication/jdbc/SQLReplicationTaskStorage.java
  src/main/java/sirius/biz/storage/layer1/replication/mongo/MongoReplicationTaskStorage.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLProcessBlobChangesLoop.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java
  src/main/java/sirius/biz/tenants/jdbc/DeleteSQLEntitiesTask.java
  src/main/java/sirius/biz/tenants/mongo/DeleteMongoEntitiesTask.java
Labels: 🐛 Bugfix

#1905 Added missing scroll method call for tenant and user config
  src/main/resources/default/templates/biz/tenants/tenant-config.html.pasta
  src/main/resources/default/templates/biz/tenants/user-account-config.html.pasta
Labels: 🐛 Bugfix

#1896 Support MultiSelectParameter in job scheduler entries
  src/main/java/sirius/biz/jobs/JobConfigData.java
  src/main/java/sirius/biz/jobs/presets/JobPresetsController.java
  src/main/resources/default/templates/biz/jobs/scheduler/entry.html.pasta
  src/test/kotlin/sirius/biz/jobs/JobConfigDataTest.kt
Labels: 🐛 Bugfix, 💣 BREAKING CHANGE

#1911 Encased description in raw to implement HTML formatting in /fs
  src/main/java/sirius/biz/storage/layer3/MutableVirtualFile.java
  src/main/java/sirius/biz/storage/layer3/VirtualFile.java
  src/main/resources/default/templates/biz/storage/list.html.pasta
Labels: 👶🏻 Trivial

#1912 Fixed unnecessary systemwide logging for BMEcat XML import job
  src/main/java/sirius/biz/jobs/batch/file/XMLImportJob.java
Labels: 👶🏻 Trivial

#1913 Improves error logging in BMEcat import + archive extract jobs
  src/main/java/sirius/biz/jobs/batch/file/XMLImportJob.java
  src/main/java/sirius/biz/storage/layer3/ExtractArchiveJob.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1910 Update some dependencies
  pom.xml
  src/main/java/sirius/biz/storage/layer3/uplink/util/UplinkConnectorPool.java
  src/main/java/sirius/biz/util/ExtractedFileBuffer.java
Labels: ⬆️ Dependencies
