Repository scireum/sirius-biz, pull requests merged in 2023-03, with the labels that each got.

#1631 Disables the Sandbox in /system/scripting
  src/main/java/sirius/biz/ide/Scripting.java
  src/main/java/sirius/biz/ide/ScriptingController.java
Labels: 🐛 Bugfix, 🔥 Hotfix

#1636 remove useless (probably typo) class
  src/main/resources/default/taglib/t/actions.html.pasta
Labels: 👶🏻 Trivial, 🛠️ Maintenance

#1635 adjust css for menu size on small widths
  src/main/resources/default/assets/styles/menu.scss
Labels: 🧬 Enhancement

#1637 bring /saml to tycho without jquery
  src/main/resources/default/templates/biz/tenants/saml-complete.html.pasta
  src/main/resources/default/templates/biz/tenants/saml.html.pasta
Labels: 🧬 Enhancement

#1639 FTP Uplink: Return borrowed uplink even when error occurs
  src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplink.java
  src/main/java/sirius/biz/storage/layer3/uplink/util/ListUplinkConnectorsCommand.java
Labels: 🐛 Bugfix, 🔥 Hotfix

#1640 Permits to provide a custom button class for t:chartsBtn
  src/main/resources/default/taglib/t/chartsBtn.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1643 BREAKING: Improves the download with filename functionality by splitting the filename from the download in order to allow inline downloads
  src/main/java/sirius/biz/storage/layer2/BlobDispatcher.java
  src/main/java/sirius/biz/storage/layer2/L3Uplink.java
  src/main/java/sirius/biz/storage/layer2/URLBuilder.java
Labels:  💣 BREAKING CHANGE

#1647 Adds Kazakhstan and Kazakh
  src/main/resources/biz_de.properties
Labels: 👶🏻 Trivial

#1650 Allows to open node-pinned URLs on cluster page
  src/main/java/sirius/biz/cluster/BackgroundInfo.java
  src/main/java/sirius/biz/cluster/ClusterController.java
  src/main/resources/default/templates/biz/cluster/cluster.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1649 Adds new tycho tag for uploading a softRef
  src/main/resources/biz_de.properties
  src/main/resources/default/assets/scripts/blob-upload-url-popover.js
  src/main/resources/default/assets/scripts/tycho-biz.js.pasta
  src/main/resources/default/assets/styles/popover.scss
  src/main/resources/default/assets/styles/soft-blob-ref-field.scss
  src/main/resources/default/assets/styles/tycho-biz.scss
  src/main/resources/default/taglib/t/blobImageSoftRefField.html.pasta
Labels: 🧬 Enhancement

#1651 Adds dropdown item to node card with new node-pinned link
  src/main/resources/default/templates/biz/cluster/cluster.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1653 Adds a helper-method commonly used when computing metrics.
  src/main/java/sirius/biz/analytics/events/EventRecorder.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1652 unify look of audit-log view like other log-pages
  pom.xml
  src/main/resources/biz_bg.properties
  src/main/resources/biz_cs.properties
  src/main/resources/biz_da.properties
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
  src/main/resources/biz_es.properties
  src/main/resources/biz_fi.properties
  src/main/resources/biz_fr.properties
  src/main/resources/biz_hr.properties
  src/main/resources/biz_hu.properties
  src/main/resources/biz_it.properties
  src/main/resources/biz_lt.properties
  src/main/resources/biz_lv.properties
  src/main/resources/biz_nl.properties
  src/main/resources/biz_no.properties
  src/main/resources/biz_pl.properties
  src/main/resources/biz_pt.properties
  src/main/resources/biz_ro.properties
  src/main/resources/biz_ru.properties
  src/main/resources/biz_sk.properties
  src/main/resources/biz_sl.properties
  src/main/resources/biz_sr.properties
  src/main/resources/biz_sv.properties
  src/main/resources/biz_uk.properties
  src/main/resources/default/templates/biz/protocol/audit_logs.html.pasta
Labels: 👶🏻 Trivial, ⬆️ Dependencies, 🛠️ Maintenance

#1655 Permits Jupiter to sync against multiple S3 repositories (buckets)
  src/main/java/sirius/biz/jupiter/JupiterConfigUpdater.java
  src/main/java/sirius/biz/jupiter/JupiterConnector.java
  src/main/java/sirius/biz/jupiter/JupiterSync.java
  src/main/java/sirius/biz/jupiter/LRUCacheConfigUpdater.java
  src/main/java/sirius/biz/jupiter/RepositoryConfigUpdater.java
  src/main/resources/component-biz.conf
Labels: 🧬 Enhancement

#1654 tycho enhancements
  src/main/resources/default/taglib/t/createButton.html.pasta
  src/main/resources/default/templates/biz/jobs/scheduler/entries.html.pasta
  src/main/resources/default/templates/biz/jobs/scheduler/entry.html.pasta
  src/main/resources/default/templates/biz/storage/list.html.pasta
Labels: 🧬 Enhancement

#1657 update underlying sirius-versions
  pom.xml
Labels: 👶🏻 Trivial, ⬆️ Dependencies

#1658 SIRI-769 add missing classes for t:createButton
  src/main/resources/default/taglib/t/createButton.html.pasta
Labels: 👶🏻 Trivial

#1664 Null-safety for event query tuner
  src/main/java/sirius/biz/analytics/events/EventRecorder.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1659 Adds support for the newly created PY.RUN command by Jupiter
  src/main/java/sirius/biz/jupiter/Jupiter.java
  src/main/java/sirius/biz/jupiter/JupiterConnector.java
Labels: 🧬 Enhancement

#1661 Adds classes for better look
  src/main/resources/default/templates/biz/jobs/scheduler/entry.html.pasta
  src/main/resources/default/templates/biz/process/process.html.pasta
Labels: 👶🏻 Trivial, 🛠️ Maintenance

#1663 Brings UI for Code-lists to Tycho
  src/main/resources/default/templates/biz/codelists/code-list-details.html.pasta
  src/main/resources/default/templates/biz/codelists/code-list-entries.html.pasta
  src/main/resources/default/templates/biz/codelists/code-list-entry.html.pasta
  src/main/resources/default/templates/biz/codelists/code-list.html.pasta
  src/main/resources/default/templates/biz/codelists/code-lists.html.pasta
Labels: 🧬 Enhancement

#1660 Rejects deletions early when deleting complex-delete entities
  src/main/java/sirius/biz/web/BizController.java
Labels: 🧬 Enhancement

#1666 Increases performance deleting temporary blobs
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java
Labels: 🧬 Enhancement

#1667 Small error handling improvments for Jupiter
  pom.xml
  src/main/java/sirius/biz/jupiter/JupiterConnector.java
Labels: 🧬 Enhancement, 👶🏻 Trivial
