Repository scireum/sirius-biz, pull requests merged in 2024-04, with the labels that each got.

#1959 Provides some groundwork for script based import customizations.
  src/main/java/sirius/biz/process/ProcessContext.java
  src/main/java/sirius/biz/process/Processes.java
  src/main/java/sirius/biz/scripting/JobTaskContextAdapter.java
  src/main/java/sirius/biz/scripting/LogMacro.java
  src/main/java/sirius/biz/scripting/Scripting.java
  src/main/java/sirius/biz/scripting/ScriptingController.java
  src/main/java/sirius/biz/scripting/TranscriptMessage.java
  src/main/resources/default/templates/biz/scripting/scripting.html.pasta
Labels: 🧬 Enhancement

#1960 Provides a main framework for custom scripting
  src/main/java/sirius/biz/scripting/EntityScriptableEvent.java
  src/main/java/sirius/biz/scripting/ScriptableEvent.java
  src/main/java/sirius/biz/scripting/ScriptableEventDispatcher.java
  src/main/java/sirius/biz/scripting/ScriptableEventDispatcherRepository.java
  src/main/java/sirius/biz/scripting/ScriptableEventRegistry.java
  src/main/java/sirius/biz/scripting/ScriptableEvents.java
  src/main/java/sirius/biz/scripting/SimpleScriptableEventDispatcher.java
  src/main/java/sirius/biz/scripting/TypedScriptableEvent.java
  src/main/java/sirius/biz/scripting/mongo/MongoCustomEventDispatcherRepository.java
  src/main/java/sirius/biz/scripting/mongo/MongoCustomScript.java
  src/main/java/sirius/biz/scripting/mongo/MongoCustomScriptController.java
  src/main/java/sirius/biz/tenants/mongo/MongoTenantMetricComputer.java
  src/main/resources/biz_de.properties
  src/main/resources/component-070-biz.conf
  src/main/resources/default/extensions/biz-menu/menu-custom-scripts.html.pasta
  src/main/resources/default/extensions/biz-menu/menu-tenants.html.pasta
  src/main/resources/default/extensions/biz-tycho-menu/menu-custom-scripts.html.pasta
  src/main/resources/default/extensions/biz-tycho-menu/menu-tenants.html.pasta
  src/main/resources/default/templates/biz/scripting/mongo-script.html.pasta
  src/main/resources/default/templates/biz/scripting/mongo-scripts.html.pasta
Labels: 🧬 Enhancement

#1961 Uses CustomEvents within ImportJobs
  pom.xml
  src/main/java/sirius/biz/importer/AfterLoadEvent.java
  src/main/java/sirius/biz/importer/BaseImportHandler.java
  src/main/java/sirius/biz/importer/BeforeCreateOrUpdateEvent.java
  src/main/java/sirius/biz/importer/BeforeFindEvent.java
  src/main/java/sirius/biz/importer/BeforeLoadEvent.java
  src/main/java/sirius/biz/importer/ContextScriptableEvent.java
  src/main/java/sirius/biz/importer/ImportHandler.java
  src/main/java/sirius/biz/importer/ImporterContext.java
  src/main/java/sirius/biz/importer/MongoEntityImportHandler.java
  src/main/java/sirius/biz/importer/SQLEntityImportHandler.java
  src/main/java/sirius/biz/jobs/batch/ImportBatchProcessFactory.java
  src/main/java/sirius/biz/jobs/batch/ImportJob.java
  src/main/java/sirius/biz/jobs/batch/ImportJobStartedEvent.java
  src/main/java/sirius/biz/jobs/batch/file/FileImportJobFactory.java
  src/main/java/sirius/biz/jobs/params/SelectStringParameter.java
  src/main/java/sirius/biz/scripting/EntityScriptableEvent.java
  src/main/java/sirius/biz/scripting/ScriptableEventRegistry.java
  src/main/java/sirius/biz/scripting/ScriptableEvents.java
  src/main/java/sirius/biz/scripting/mongo/MongoCustomScript.java
  src/main/resources/biz_de.properties
  src/main/resources/component-070-biz.conf
  src/main/resources/default/templates/biz/cluster/analytics-tasks-cards.html.pasta
Labels: 🧬 Enhancement

#1962 Tenant Scripting enhancements
  src/main/java/sirius/biz/jobs/batch/ImportBatchProcessFactory.java
  src/main/java/sirius/biz/scripting/TypedScriptableEvent.java
  src/main/resources/component-070-biz.conf
Labels: 🧬 Enhancement

#1964 Tenant Scripting Enhancements
  src/main/java/sirius/biz/jobs/batch/ImportBatchProcessFactory.java
  src/main/java/sirius/biz/scripting/ScriptableEventDispatcherRepository.java
  src/main/java/sirius/biz/scripting/ScriptableEvents.java
  src/main/java/sirius/biz/scripting/mongo/MongoCustomEventDispatcherRepository.java
  src/main/java/sirius/biz/scripting/mongo/MongoCustomScript.java
  src/main/java/sirius/biz/scripting/mongo/MongoCustomScriptController.java
  src/main/resources/biz_de.properties
  src/main/resources/default/templates/biz/scripting/mongo-script.html.pasta
  src/main/resources/default/templates/biz/scripting/mongo-scripts.html.pasta
Labels: 🧬 Enhancement, 🐛 Bugfix

#1963 KBA: Fixes links not opening in new tab in OXOMI KBAs
  src/main/resources/default/kb/en/user/noodle.html.pasta
  src/main/resources/default/kb/en/user/tagliatelle.html.pasta
Labels: 🐛 Bugfix

#1966 Fetches tenant scripts from all tenants in the hierarchy
  src/main/java/sirius/biz/scripting/ScriptableEventDispatcherRepository.java
  src/main/java/sirius/biz/scripting/mongo/MongoCustomEventDispatcherRepository.java
  src/main/java/sirius/biz/tenants/Tenants.java
Labels: 🧬 Enhancement

#1967 Implements entityId to t:tracing for copying entity ids more easily
  src/main/resources/biz_de.properties
  src/main/resources/default/taglib/t/tracing.html.pasta
Labels: 🧬 Enhancement

#1969 Do not collect the dispatcher parameter when no scripts exist
  src/main/java/sirius/biz/jobs/batch/ImportBatchProcessFactory.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1968 Mark blob lowercased fields with sirius db annotation
  pom.xml
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java
Labels: 🧬 Enhancement

#1970 SQLdirectory query lowercasing
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLDirectory.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoDirectory.java
Labels: 🧬 Enhancement

#1971 Lokalise: Translations update
  src/main/resources/biz_bg.properties
  src/main/resources/biz_cs.properties
  src/main/resources/biz_da.properties
  src/main/resources/biz_en.properties
  src/main/resources/biz_es.properties
  src/main/resources/biz_fi.properties
  src/main/resources/biz_fr.properties
  src/main/resources/biz_hr.properties
  src/main/resources/biz_hu.properties
  src/main/resources/biz_it.properties
  src/main/resources/biz_lt.properties
  src/main/resources/biz_lv.properties
  src/main/resources/biz_nl.properties
  src/main/resources/biz_no.properties
  src/main/resources/biz_pl.properties
  src/main/resources/biz_pt.properties
  src/main/resources/biz_ro.properties
  src/main/resources/biz_ru.properties
  src/main/resources/biz_sk.properties
  src/main/resources/biz_sl.properties
  src/main/resources/biz_sr.properties
  src/main/resources/biz_sv.properties
  src/main/resources/biz_tr.properties
  src/main/resources/biz_uk.properties
Labels: 🧬 Enhancement, 🛠️ Maintenance

#1972 Changes key value for OpenSearchProvider label
  src/main/resources/biz_de.properties
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1973 Lokalise: Translations update
  src/main/resources/biz_bg.properties
  src/main/resources/biz_cs.properties
  src/main/resources/biz_da.properties
  src/main/resources/biz_en.properties
  src/main/resources/biz_es.properties
  src/main/resources/biz_fi.properties
  src/main/resources/biz_fr.properties
  src/main/resources/biz_hr.properties
  src/main/resources/biz_hu.properties
  src/main/resources/biz_it.properties
  src/main/resources/biz_lt.properties
  src/main/resources/biz_lv.properties
  src/main/resources/biz_nl.properties
  src/main/resources/biz_no.properties
  src/main/resources/biz_pl.properties
  src/main/resources/biz_pt.properties
  src/main/resources/biz_ro.properties
  src/main/resources/biz_ru.properties
  src/main/resources/biz_sk.properties
  src/main/resources/biz_sl.properties
  src/main/resources/biz_sr.properties
  src/main/resources/biz_sv.properties
  src/main/resources/biz_tr.properties
  src/main/resources/biz_uk.properties
Labels: 🧬 Enhancement, 🛠️ Maintenance

#1974 Add some additional sandbox annotations for blob refs
  src/main/java/sirius/biz/storage/layer2/BlobHardRef.java
  src/main/java/sirius/biz/storage/layer2/BlobSoftRef.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1976 Lokalise: Translations update
  src/main/resources/biz_bg.properties
  src/main/resources/biz_cs.properties
  src/main/resources/biz_da.properties
  src/main/resources/biz_en.properties
  src/main/resources/biz_es.properties
  src/main/resources/biz_fi.properties
  src/main/resources/biz_fr.properties
  src/main/resources/biz_hr.properties
  src/main/resources/biz_hu.properties
  src/main/resources/biz_it.properties
  src/main/resources/biz_lt.properties
  src/main/resources/biz_lv.properties
  src/main/resources/biz_nl.properties
  src/main/resources/biz_no.properties
  src/main/resources/biz_pt.properties
  src/main/resources/biz_ro.properties
  src/main/resources/biz_ru.properties
  src/main/resources/biz_sk.properties
  src/main/resources/biz_sl.properties
  src/main/resources/biz_sr.properties
  src/main/resources/biz_sv.properties
  src/main/resources/biz_uk.properties
Labels: 🧬 Enhancement, 🛠️ Maintenance

#1978 SonarQube - Increase safeness of regexes by making quantifiers possessive/reluctant
  src/main/java/sirius/biz/tycho/kb/KnowledgeBaseMessageExpander.java
Labels: 🛠️ Maintenance

#1979 Open Search - Ensure select link in user and tenant search results works
  src/main/java/sirius/biz/tenants/TenantSearchProvider.java
  src/main/java/sirius/biz/tenants/UserAccountSearchProvider.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1980 Adds a "continue-on-error" parameter to the file transfer job
  src/main/java/sirius/biz/storage/layer3/Transfer.java
  src/main/java/sirius/biz/storage/layer3/TransferFilesJob.java
  src/main/resources/biz_de.properties
Labels: 🧬 Enhancement

#1981 Update some dependencies to their latest versions
  pom.xml
Labels: 👶🏻 Trivial, ⬆️ Dependencies, 🛠️ Maintenance

#1983 Update sirius parent to version targeting Java 22
  .drone.yml
  pom.xml
Labels: 👶🏻 Trivial, ⬆️ Dependencies, 🛠️ Maintenance

#1982 DH-240: Fix the SelectStringParameter.getValues() method.
  src/main/java/sirius/biz/jobs/params/SelectStringParameter.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1975 Permits to only support login via hashed API tokens
  src/main/java/sirius/biz/tenants/TenantUserManager.java
  src/main/resources/component-070-biz.conf
Labels: 🧬 Enhancement, 💣 BREAKING CHANGE
