Repository scireum/sirius-biz, pull requests merged in 2024-10, with the labels that each got.

#2037 Permits to override the suggestion uri in t:lookupValue
  src/main/resources/default/taglib/t/lookupValue.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#2038 Adds a few getters to the MultiLanguageStringHelper
  src/main/java/sirius/biz/translations/MultiLanguageStringHelper.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#2040 Version upgrades
  docker-compose.yml
  pom.xml
  src/main/java/sirius/biz/storage/s3/ObjectStore.java
  src/test/resources/docker-compose.yml
Labels: ⬆️ Dependencies

#2042 Smart Value - Show edit option in tenant smart value even when tenant is already selected
  src/main/java/sirius/biz/tycho/smart/TenantSmartValueProvider.java
  src/main/java/sirius/biz/tycho/smart/UserAccountSmartValueProvider.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#2041 Upgrade ES docker versions
  docker-compose.yml
  pom.xml
  src/test/resources/docker-compose.yml
Labels: ⬆️ Dependencies

#2043 Introduces new customer-scripting events
  src/main/java/sirius/biz/importer/AfterLineLoadEvent.java
  src/main/java/sirius/biz/importer/AfterNodeLoadEvent.java
  src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedImportJob.java
  src/main/java/sirius/biz/jobs/batch/file/LineBasedArchiveImportJob.java
  src/main/java/sirius/biz/jobs/batch/file/XMLImportJob.java
Labels: 🧬 Enhancement
