Repository scireum/sirius-biz, pull requests merged in 2024-03, with the labels that each got.

#1951 Enhance KBA message expander to support linking to section via anchor
  src/main/java/sirius/biz/tycho/kb/KnowledgeBaseMessageExpander.java
Labels: 🧬 Enhancement

#1949 SIRI-942 revamp saving of code-list-entries
  src/main/java/sirius/biz/codelists/CodeListController.java
  src/main/java/sirius/biz/codelists/jdbc/SQLCodeListController.java
  src/main/java/sirius/biz/codelists/mongo/MongoCodeListController.java
  src/main/resources/default/taglib/t/multiLanguageTextField.html.pasta
  src/main/resources/default/templates/biz/codelists/code-list-entries.html.pasta
  src/main/resources/default/templates/biz/codelists/code-list-entry.html.pasta
Labels: 🐛 Bugfix, 💣 BREAKING CHANGE

#1952 Relaxes race condition with autosetup a little
  src/main/java/sirius/biz/process/Processes.java
Labels: 🐛 Bugfix

#1953 `ArchiveImportJob`: Improvements
  src/main/java/sirius/biz/jobs/batch/file/ArchiveImportJob.java
Labels: 🧬 Enhancement

#1955 Properly marks field as nullable
  src/main/java/sirius/biz/tycho/kb/KnowledgeBaseEntry.java
Labels: 🐛 Bugfix

#1954 Properly logs errors at KB sync task
  src/main/java/sirius/biz/tycho/kb/SynchronizeArticlesTask.java
Labels: 🐛 Bugfix

#1957 Provide a temporary useful setter.
  src/main/java/sirius/biz/importer/txn/ImportTransactionHelper.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1958 SAML: Redirect Fix
  src/main/resources/default/templates/biz/login.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial
