Repository scireum/sirius-biz, pull requests merged in 2024-07, with the labels that each got.

#2017 Shows more information for wrapped exceptions
  src/main/java/sirius/biz/protocol/Protocols.java
Labels: 🧬 Enhancement, 🔥 Hotfix

#2018 SIRI-975: Uniformly take deprecated Lookup Entries into account or not
  src/main/java/sirius/biz/codelists/CodeListLookupTable.java
  src/main/java/sirius/biz/codelists/ConfigLookupTable.java
  src/main/java/sirius/biz/codelists/CustomLookupTable.java
  src/main/java/sirius/biz/codelists/IDBFilteredLookupTable.java
  src/main/java/sirius/biz/codelists/IDBLookupTable.java
  src/main/java/sirius/biz/codelists/LookupTable.java
  src/main/java/sirius/biz/codelists/LookupTableController.java
  src/main/resources/default/taglib/t/lookupValue.html.pasta
  src/main/resources/default/taglib/t/lookupValues.html.pasta
  src/main/resources/default/taglib/w/lookupValue.html.pasta
  src/main/resources/default/taglib/w/lookupValues.html.pasta
Labels: 🧬 Enhancement, 🐛 Bugfix

#2019 Permits to fine tune S3 connections
  src/main/java/sirius/biz/storage/s3/ObjectStores.java
  src/main/resources/component-070-biz.conf
Labels: 🧬 Enhancement

#2020 SIRI-989: File Storage – Fix Duplicate Listing of Files and incorrect Total Count for Pagination
  src/main/java/sirius/biz/storage/layer2/L3Uplink.java
Labels: 🐛 Bugfix

#2021 Handles AmazonClientException properly
  src/main/java/sirius/biz/storage/layer1/S3ObjectStorageSpace.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#2023 KB - Adds a head block which allows to extend the contents of the pages head
  src/main/resources/default/taglib/k/article.html.pasta
  src/main/resources/default/taglib/k/base.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#2022 BREAKING: change the way saving processTypes.
  src/main/java/sirius/biz/jobs/FixProcessTypes.java
  src/main/java/sirius/biz/jobs/batch/BatchProcessJobFactory.java
  src/main/java/sirius/biz/process/ProcessController.java
Labels: 🧬 Enhancement, 💣 BREAKING CHANGE

#2024 KB: Improved Links (OX-11128)
  src/main/resources/biz_de.properties
  src/main/resources/default/taglib/k/link.html.pasta
  src/main/resources/default/taglib/k/ref.html.pasta
Labels: 🧬 Enhancement

#2025 Fix: Deprecated Attributes (OX-11128)
  src/main/resources/default/kb/00000.html.pasta
  src/main/resources/default/kb/en/user/noodle.html.pasta
  src/main/resources/default/kb/en/user/tagliatelle.html.pasta
  src/main/resources/default/taglib/k/base.html.pasta
  src/main/resources/default/taglib/k/chapter.html.pasta
  src/main/resources/default/templates/biz/tycho/kb/welcome.html.pasta
  src/main/resources/default/templates/biz/tycho/kb/welcome_de.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial
