Repository scireum/sirius-biz, pull requests merged in 2024-01, with the labels that each got.

#1914 Processes UI
  src/main/java/sirius/biz/cluster/NeighborhoodWatch.java
  src/main/java/sirius/biz/cluster/work/DistributedTasks.java
  src/main/java/sirius/biz/cluster/work/WorkLoaderLoop.java
  src/main/resources/default/templates/biz/process/process.html.pasta
  src/main/resources/default/templates/biz/process/processes.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1917 Maintenance
  pom.xml
  src/main/resources/default/taglib/t/charts.html.pasta
  src/main/resources/default/taglib/t/chartsBtn.html.pasta
  src/main/resources/default/taglib/t/jobs.html.pasta
  src/main/resources/default/taglib/t/jobsBtn.html.pasta
  src/main/resources/default/taglib/w/jobs.html.pasta
  src/main/resources/default/templates/biz/disaster.html.pasta
  src/main/resources/default/templates/biz/login.html.pasta
Labels: 🧬 Enhancement

#1918 Overhauls Cluster Management Page
  src/main/java/sirius/biz/cluster/ClusterController.java
  src/main/java/sirius/biz/locks/LocksCommand.java
  src/main/resources/default/templates/biz/cluster/background-jobs.html.pasta
  src/main/resources/default/templates/biz/cluster/cluster.html.pasta
  src/main/resources/default/templates/biz/cluster/eod-tasks.html.pasta
  src/main/resources/default/templates/biz/cluster/locks.html.pasta
  src/main/resources/default/templates/biz/cluster/nodes.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1919 Fixes URL redirection using the overview/detail pattern (redirectToSaneReferer)
  src/main/java/sirius/biz/web/BizController.java
Labels: 🐛 Bugfix

#1920 Doughnut Charts Fix
  pom.xml
  src/main/java/sirius/biz/jobs/interactive/DoughnutChartJobFactory.java
  src/main/resources/default/templates/biz/jobs/doughnutchart.html.pasta
  src/main/resources/default/templates/biz/process/process-output-chart.html.pasta
Labels: 💣 BREAKING CHANGE

#1921 Filter out duplicated defined custom-entries and only take the custom one
  src/main/java/sirius/biz/codelists/CustomLookupTable.java
Labels: 🧬 Enhancement

#1924 Defines a new permission for unlocking files
  src/main/java/sirius/biz/storage/layer3/VirtualFileSystem.java
  src/main/java/sirius/biz/storage/layer3/VirtualFileSystemController.java
  src/main/resources/component-070-biz.conf
  src/main/resources/default/templates/biz/storage/list.html.pasta
Labels: 🧬 Enhancement

#1923 Allows to unlock all locks at once
  src/main/resources/default/templates/biz/cluster/locks.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1925 Introduces a job to bulk delete files/directories
  src/main/java/sirius/biz/storage/layer3/DeleteFilesJob.java
  src/main/java/sirius/biz/storage/layer3/DeletionCheckHandler.java
  src/main/java/sirius/biz/storage/layer3/VirtualFileSystem.java
  src/main/java/sirius/biz/storage/layer3/VirtualFileSystemController.java
  src/main/java/sirius/biz/tenants/deletion/DeleteTenantJobFactory.java
  src/main/resources/biz_de.properties
  src/main/resources/default/templates/biz/jobs/job.html.pasta
  src/main/resources/default/templates/biz/storage/list.html.pasta
Labels: 🧬 Enhancement

#1926 Avoids computing metrics for user education
  src/main/java/sirius/biz/tenants/metrics/computers/UserAccountAcademyMetricComputer.java
Labels: 🐛 Bugfix, 👶🏻 Trivial
