Repository scireum/sirius-biz, pull requests merged in 2024-08, with the labels that each got.

#2026 Blob URIs
  src/main/java/sirius/biz/storage/layer2/URLBuilder.java
Labels: 🧬 Enhancement

#2027 SIRI-1007 Allow entities to supply custom journal info
  src/main/java/sirius/biz/protocol/CustomJournalProvider.java
  src/main/java/sirius/biz/protocol/JournalData.java
Labels: 🧬 Enhancement

#2028 BREAKING: update versions to use new Value#ignore
  pom.xml
  src/main/resources/biz_de.properties
Labels: 💣 BREAKING CHANGE

#2029 Skips deleted onboarding videos from deletion marking
  src/main/java/sirius/biz/tycho/academy/jdbc/SQLOnboardingEngine.java
  src/main/java/sirius/biz/tycho/academy/mongo/MongoOnboardingEngine.java
Labels: 🐛 Bugfix, 👶🏻 Trivial
