Repository scireum/sirius-biz, pull requests merged in 2024-02, with the labels that each got.

#1928 Improvements handling S3 responses
  src/main/java/sirius/biz/storage/layer1/ObjectStorageSpace.java
  src/main/java/sirius/biz/storage/layer1/S3ObjectStorageSpace.java
Labels: 🧬 Enhancement

#1929 Only reports removal of previously filled chapters
  src/main/java/sirius/biz/tycho/kb/SynchronizeArticlesTask.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1930 Upgrades the mongo container to 6.0.13
  docker-compose.yml
  src/test/resources/docker-compose.yml
Labels: 🎁 Next version, ⬆️ Dependencies

#1931 Improves query performance when directories are deleted
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLProcessBlobChangesLoop.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoProcessBlobChangesLoop.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1933 Query Tool: Marks fields that are actually empty in DB
  src/main/resources/default/templates/biz/model/query-results.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1932 ensure unique labels in import-dictionaries
  src/main/java/sirius/biz/importer/format/ImportDictionary.java
Labels: 🧬 Enhancement

#1936 BS5: Fixes alignment of permission checkbox help texts
  src/main/resources/default/templates/biz/packages/additional-and-revoked-permissions.html.pasta
  src/main/resources/default/templates/biz/tenants/user-account-details-fields.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1937 BS5 make blobImageSoftRefField work again
  src/main/resources/default/assets/scripts/blob-upload-url-popover.js
  src/main/resources/default/taglib/t/blobImageSoftRefField.html.pasta
Labels: 🐛 Bugfix

#1935 Add Enum-Values and LookupTable-Values in Job-Documentation
  src/main/java/sirius/biz/analytics/events/ClickhousePartsReportJobFactory.java
  src/main/java/sirius/biz/analytics/reports/Cells.java
  src/main/java/sirius/biz/analytics/reports/LinkCellFormat.java
  src/main/java/sirius/biz/codelists/LookupValuesProperty.java
  src/main/java/sirius/biz/importer/format/EnumPropertyTransformer.java
  src/main/java/sirius/biz/importer/format/FieldDefinition.java
  src/main/java/sirius/biz/importer/format/ImportDictionary.java
  src/main/java/sirius/biz/importer/format/LookupValueCheck.java
  src/main/java/sirius/biz/importer/format/LookupValuePropertyTransformer.java
  src/main/java/sirius/biz/importer/format/LookupValuesCheck.java
  src/main/java/sirius/biz/importer/format/LookupValuesPropertyTransformer.java
  src/main/java/sirius/biz/importer/format/RegexCheck.java
  src/main/java/sirius/biz/importer/format/ValueCheck.java
  src/main/java/sirius/biz/tycho/updates/UpdatesReport.java
  src/main/resources/biz_de.properties
Labels: 🧬 Enhancement, 💣 BREAKING CHANGE

#1938 Exposes the ImportHandler.newEntity as public callable method
  src/main/java/sirius/biz/importer/BaseImportHandler.java
  src/main/java/sirius/biz/importer/ImportHandler.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1940 Implements input validation for SAML fingerprints for tenants
  src/main/resources/biz_de.properties
  src/main/resources/default/templates/biz/tenants/tenant-saml.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1941 S3 Storage stream: Ignores SocketException
  src/main/java/sirius/biz/storage/layer1/ObjectStorageSpace.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1942 update sirius-web version for newest fixes
  pom.xml
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1943 Adds an GH action which controls the PR labels before merging
  .github/workflows/enforce-pr-label.yml
Labels: 🛠️ Maintenance

#1944 Adds missing translation
  src/main/resources/biz_de.properties
Labels: 👶🏻 Trivial, 🛠️ Maintenance

#1945 Avoids cursor exception processing analytic computers
  src/main/java/sirius/biz/analytics/scheduler/BaseEntityBatchEmitter.java
Labels: 🐛 Bugfix, 👶🏻 Trivial, 💣 BREAKING CHANGE

#1946 fix rare case of sanitizing file names with illegal characters
  src/main/java/sirius/biz/storage/util/StorageUtils.java
Labels: 🐛 Bugfix

#1948 fix breakages for t:datefield and update to new sirius-web-version
  pom.xml
  src/main/resources/default/templates/biz/disaster.html.pasta
  src/main/resources/default/templates/biz/jobs/params/datefield.html.pasta
Labels: 🧬 Enhancement, 💣 BREAKING CHANGE
