Repository scireum/sirius-biz, pull requests merged in 2024-06, with the labels that each got.

#2001 Adds comment for results on SQL-performance regarding countIf- and GROUPBY-queries to framework
  src/main/java/sirius/biz/analytics/explorer/EventTimeSeriesComputer.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#2002 MariaDb driver upgrade
  docker-compose.yml
  pom.xml
  src/test/kotlin/sirius/biz/jupiter/JupiterTest.kt
  src/test/resources/docker-compose.yml
Labels: ⬆️ Dependencies

#1999 SQL: Show num rows and limit as info
  src/main/java/sirius/biz/jdbc/DatabaseController.java
  src/main/resources/default/templates/biz/model/sql.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#2003 Resolves startup issues caused by upgrading the Clickhouse dependencies
  pom.xml
Labels: 🐛 Bugfix, 👶🏻 Trivial, ⬆️ Dependencies

#2004 Open Search: Adds tags to results of Knowledgebase articles for easier differentiation
  src/main/java/sirius/biz/tycho/kb/KnowledgeBaseSearchProvider.java
Labels: 🧬 Enhancement

#2006 Makes Read-Only `<t:lookupValue>` and `<t:lookupValues>` Actually Read-Only
  src/main/resources/default/taglib/t/lookupValue.html.pasta
  src/main/resources/default/taglib/t/lookupValues.html.pasta
Labels: 🧬 Enhancement, 🐛 Bugfix

#2007 OpenSearch: Permits to find tenants with their exact ID
  src/main/java/sirius/biz/tenants/mongo/MongoTenantSearchProvider.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#2008 ExtractArchiveJob: Fixes job not stopping when cancelled by user, also changes state to use "cancelled" instead of "terminated"
  src/main/java/sirius/biz/process/Processes.java
  src/main/java/sirius/biz/storage/layer3/ExtractArchiveJob.java
Labels: 🐛 Bugfix

#2011 VFS - DeleteFilesJob: Fixes job skipping files while iterating over all files when job is not set to simulation
  src/main/java/sirius/biz/storage/layer3/DeleteFilesJob.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#2012 Open Search - Handle found "manual" chapters in open search correctly
  src/main/java/sirius/biz/tycho/kb/KnowledgeBaseSearchProvider.java
  src/main/resources/biz_de.properties
Labels: 🐛 Bugfix, 👶🏻 Trivial

#2013 ZIP Handling - Fall back to ISO-8859-1 when UTF8 wxtraction fails
  src/main/java/sirius/biz/util/ArchiveExtractor.java
Labels: 🧬 Enhancement

#2014 Lokalise: Translations update
  src/main/resources/biz_bg.properties
  src/main/resources/biz_cs.properties
  src/main/resources/biz_da.properties
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
  src/main/resources/biz_es.properties
  src/main/resources/biz_fi.properties
  src/main/resources/biz_fr.properties
  src/main/resources/biz_hr.properties
  src/main/resources/biz_hu.properties
  src/main/resources/biz_it.properties
  src/main/resources/biz_lt.properties
  src/main/resources/biz_lv.properties
  src/main/resources/biz_nl.properties
  src/main/resources/biz_no.properties
  src/main/resources/biz_pl.properties
  src/main/resources/biz_pt.properties
  src/main/resources/biz_ro.properties
  src/main/resources/biz_ru.properties
  src/main/resources/biz_sk.properties
  src/main/resources/biz_sl.properties
  src/main/resources/biz_sr.properties
  src/main/resources/biz_sv.properties
  src/main/resources/biz_tr.properties
  src/main/resources/biz_uk.properties
Labels: 🧬 Enhancement

#2015 fix not working lookup-tables modal pagination
  src/main/resources/default/assets/scripts/lookup-tables.js.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial
