Repository scireum/sirius-biz, pull requests merged in 2024-12, with the labels that each got.

#2050 SE-14215: Grants sandbox access to the user password settings.
  src/main/java/sirius/biz/password/PasswordSettings.java
Labels: 🐛 Bugfix

#2051 use new isHttpUrl() method from kernel#Strings
  pom.xml
  src/main/java/sirius/biz/storage/layer2/BlobSoftRef.java
  src/main/java/sirius/biz/storage/legacy/StoredObjectRef.java
Labels: 💣 BREAKING CHANGE, 🛠️ Maintenance

#2053 Switch project to Java 23
  .drone.yml
  pom.xml
Labels: 👶🏻 Trivial, ⬆️ Dependencies

#2055 Solves an issue where importing an XML file causes large portions of the file to be loaded in RAM
  src/main/java/sirius/biz/jobs/batch/file/XMLImportJob.java
Labels: 🐛 Bugfix, 🔥 Hotfix

#2052 SIRI-1035 password-field optimizations
  src/main/resources/default/templates/biz/login.html.pasta
Labels: 🧬 Enhancement

#2056 HF: dev-107.2.1 → dev-107.3.0
  src/main/java/sirius/biz/jobs/batch/file/XMLImportJob.java
Labels: 🔥 Hotfix, 🛠️ Maintenance

#2058 Ensure better caching of redirected Blob URLs
  pom.xml
  src/main/java/sirius/biz/storage/layer2/BlobDispatcher.java
Labels: 🧬 Enhancement

#2060 Processes - Waiting State
  src/main/java/sirius/biz/jobs/batch/BatchProcessTaskExecutor.java
  src/main/java/sirius/biz/process/Process.java
  src/main/java/sirius/biz/process/ProcessContext.java
  src/main/java/sirius/biz/process/ProcessEnvironment.java
  src/main/java/sirius/biz/process/ProcessState.java
  src/main/java/sirius/biz/process/Processes.java
  src/main/resources/biz_de.properties
  src/main/resources/default/templates/biz/process/process.html.pasta
  src/main/resources/default/templates/biz/process/processes.html.pasta
Labels: 🧬 Enhancement

#2059 Fixes system-files not being ignored by ZIP-native extractor when executing an import-job
  pom.xml
  src/main/java/sirius/biz/jobs/batch/file/ArchiveImportJob.java
  src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedArchiveImportJob.java
  src/main/java/sirius/biz/storage/layer3/VirtualFileSystemController.java
  src/main/java/sirius/biz/storage/s3/ObjectStore.java
  src/main/java/sirius/biz/util/ArchiveExtractor.java
  src/main/java/sirius/biz/util/LocalArchiveExtractCallback.java
Labels: 🐛 Bugfix

#2054 SVG Charts for PDFs (OX-9272)
  pom.xml
  src/main/java/sirius/biz/charts/Chart.java
  src/main/java/sirius/biz/charts/Charts.java
  src/main/java/sirius/biz/charts/Dataset.java
  src/main/java/sirius/biz/charts/DoughnutChart.java
  src/main/java/sirius/biz/charts/PieChart.java
  src/main/java/sirius/biz/charts/RadarChart.java
Labels: 🧬 Enhancement, 🔥 Hotfix

#2057 hotfix/dev-107.30 → develop
  pom.xml
  src/main/java/sirius/biz/charts/Chart.java
  src/main/java/sirius/biz/charts/Charts.java
  src/main/java/sirius/biz/charts/Dataset.java
  src/main/java/sirius/biz/charts/DoughnutChart.java
  src/main/java/sirius/biz/charts/PieChart.java
  src/main/java/sirius/biz/charts/RadarChart.java
Labels: 🛠️ Maintenance

#2061 EventRecorder - Adds Blockwise Event Fetching
  src/main/java/sirius/biz/analytics/events/EventRecorder.java
  src/main/java/sirius/biz/analytics/events/EventSpliterator.java
  src/main/java/sirius/biz/analytics/events/PageImpressionEvent.java
  src/main/java/sirius/biz/analytics/events/UserActivityEvent.java
  src/main/java/sirius/biz/analytics/events/UserEvent.java
  src/main/java/sirius/biz/tycho/updates/UpdateClickEvent.java
  src/main/java/sirius/biz/util/SOAPCallEvent.java
Labels: 🧬 Enhancement

#2062 SE-14230: Cherry Picks Event Streaming for Hotfix
  src/main/java/sirius/biz/analytics/events/EventRecorder.java
  src/main/java/sirius/biz/analytics/events/EventSpliterator.java
  src/main/java/sirius/biz/analytics/events/PageImpressionEvent.java
  src/main/java/sirius/biz/analytics/events/UserActivityEvent.java
  src/main/java/sirius/biz/analytics/events/UserEvent.java
  src/main/java/sirius/biz/tycho/updates/UpdateClickEvent.java
  src/main/java/sirius/biz/util/SOAPCallEvent.java
Labels: 🧬 Enhancement, 🔥 Hotfix

#2065 Bumps sirius libs and applies breaking changes
  pom.xml
  src/main/java/sirius/biz/storage/layer2/jdbc/SQLVariant.java
  src/main/java/sirius/biz/storage/layer2/mongo/MongoVariant.java
  src/main/java/sirius/biz/storage/legacy/VersionManager.java
  src/main/java/sirius/biz/storage/legacy/VirtualObjectVersion.java
  src/main/java/sirius/biz/tenants/SAMLController.java
  src/main/java/sirius/biz/tenants/TenantController.java
  src/main/java/sirius/biz/tenants/TenantUserManager.java
  src/main/java/sirius/biz/tenants/Tenants.java
  src/main/java/sirius/biz/tenants/UserAccountData.java
  src/main/java/sirius/biz/tenants/UserAccountSearchProvider.java
  src/main/resources/default/templates/biz/tenants/tenant-extended.html.pasta
Labels: 💣 BREAKING CHANGE, ⬆️ Dependencies

#2066 Jobs Add a new parameter for setting local date times
  src/main/java/sirius/biz/jobs/params/LocalDateTimeParameter.java
  src/main/java/sirius/biz/storage/layer3/DeleteFilesJob.java
  src/main/resources/default/templates/biz/jobs/params/date-time.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#2067 Improves caching of virtual URLs
  src/main/java/sirius/biz/storage/layer2/BlobDispatcher.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#2068 Blob Download and Conversion (SIRI-1022)
  src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
Labels: 🐛 Bugfix
