Repository scireum/sirius-biz, pull requests merged in 2024-05, with the labels that each got.

#1986 Limits the maximum length of a error message to 16k
  src/main/java/sirius/biz/protocol/StoredIncident.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1988 Allow scripting events to fully skip entities
  src/main/java/sirius/biz/importer/BaseImportHandler.java
  src/main/java/sirius/biz/importer/ImportHandler.java
  src/main/java/sirius/biz/importer/Importer.java
  src/main/java/sirius/biz/importer/MongoEntityImportHandler.java
  src/main/java/sirius/biz/importer/SQLEntityImportHandler.java
  src/main/java/sirius/biz/jobs/batch/file/EntityImportJob.java
  src/main/java/sirius/biz/jobs/batch/file/RelationalEntityImportJob.java
  src/main/java/sirius/biz/scripting/ScriptableEvent.java
  src/main/java/sirius/biz/scripting/TypedScriptableEvent.java
Labels: 🧬 Enhancement

#1985 Makes scheduled entries directly executable from overview page
  src/main/java/sirius/biz/jobs/scheduler/JobSchedulerLoop.java
  src/main/java/sirius/biz/jobs/scheduler/ScheduledEntryExecution.java
  src/main/java/sirius/biz/jobs/scheduler/SchedulerController.java
  src/main/resources/biz_de.properties
  src/main/resources/default/templates/biz/jobs/scheduler/entries.html.pasta
Labels: 🧬 Enhancement

#1989 Fixes skipped entities properly
  src/main/java/sirius/biz/jobs/batch/file/RelationalEntityImportJob.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1990 Permits to call methods via noodle scripts
  src/main/java/sirius/biz/importer/BeforeCreateOrUpdateEvent.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1991 add file-extension icon to t:blobImageHardRefField
  src/main/resources/default/taglib/t/blobImageHardRefField.html.pasta
Labels: 🧬 Enhancement

#1994 ExtractArchiveJob: Handles unresolvable paths
  src/main/java/sirius/biz/storage/layer3/ExtractArchiveJob.java
Labels: 🐛 Bugfix

#1992 Introduce new permission to use the open-search and fix some related problems
  src/main/java/sirius/biz/tenants/TenantSearchProvider.java
  src/main/java/sirius/biz/tenants/UserAccountSearchProvider.java
  src/main/java/sirius/biz/tycho/search/OpenSearchController.java
  src/main/java/sirius/biz/tycho/search/OpenSearchResult.java
  src/main/resources/component-070-biz.conf
  src/main/resources/default/extensions/tycho-page-menu/menu.html.pasta
  src/main/resources/default/extensions/wondergem-page-menu/menu.html.pasta
  src/main/resources/default/templates/biz/tycho/kb/welcome.html.pasta
  src/main/resources/default/templates/biz/tycho/kb/welcome_de.html.pasta
  src/main/resources/default/templates/biz/tycho/search/search.html.pasta
Labels: 🧬 Enhancement, 🐛 Bugfix

#1996 Detaches tenant scripting from sandbox
  src/main/java/sirius/biz/scripting/mongo/MongoCustomEventDispatcherRepository.java
  src/main/java/sirius/biz/scripting/mongo/MongoCustomScriptController.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1997 Concatenates all error messages of an incident
  pom.xml
  src/main/java/sirius/biz/protocol/Protocols.java
Labels: 🧬 Enhancement, 🛠️ Maintenance

#1998 SIRI-965: remove double methods and move to sirius-web and use them
  pom.xml
  src/main/resources/default/taglib/t/blobImageHardRefField.html.pasta
  src/main/resources/default/taglib/t/blobImageSoftRefField.html.pasta
  src/test/kotlin/sirius/biz/pagehelper/ElasticPageHelperTest.kt
  src/test/kotlin/sirius/biz/pagehelper/MongoPageHelperTest.kt
Labels: 🧬 Enhancement, 💣 BREAKING CHANGE
