Repository scireum/sirius-biz, pull requests merged in 2024-09, with the labels that each got.

#2031 PDF Rendering: Blobs
  pom.xml
  src/main/java/sirius/biz/web/BlobPdfReplaceHandler.java
Labels: 🧬 Enhancement, ⬆️ Dependencies

#2032 add class to not break layout on small screen or few space
  src/main/resources/default/templates/biz/cluster/background-jobs.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#2034 Lokalise: Translations update
  src/main/resources/biz_bg.properties
  src/main/resources/biz_cs.properties
  src/main/resources/biz_da.properties
  src/main/resources/biz_en.properties
  src/main/resources/biz_es.properties
  src/main/resources/biz_fi.properties
  src/main/resources/biz_fr.properties
  src/main/resources/biz_hr.properties
  src/main/resources/biz_hu.properties
  src/main/resources/biz_it.properties
  src/main/resources/biz_lt.properties
  src/main/resources/biz_lv.properties
  src/main/resources/biz_nl.properties
  src/main/resources/biz_no.properties
  src/main/resources/biz_pl.properties
  src/main/resources/biz_pt.properties
  src/main/resources/biz_ro.properties
  src/main/resources/biz_ru.properties
  src/main/resources/biz_sk.properties
  src/main/resources/biz_sl.properties
  src/main/resources/biz_sr.properties
  src/main/resources/biz_sv.properties
  src/main/resources/biz_tr.properties
  src/main/resources/biz_uk.properties
Labels: 🧬 Enhancement, 👶🏻 Trivial

#2033 Maintenance: Unused Method (OX-10783)
  src/main/java/sirius/biz/storage/layer2/URLBuilder.java
Labels: 🧬 Enhancement, 👶🏻 Trivial, 💣 BREAKING CHANGE

#2036 Fix bug in pagination in /fs with active query.
  src/main/java/sirius/biz/storage/layer2/L3Uplink.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#2035 User Accounts - Extends user account cards and open search results by the option to jump to a tenant if the user has the support role
  src/main/java/sirius/biz/tenants/UserAccountSearchProvider.java
  src/main/resources/biz_de.properties
  src/main/resources/default/taglib/t/smartValue.html.pasta
  src/main/resources/default/templates/biz/tenants/user-accounts-list.html.pasta
Labels: 🧬 Enhancement
