Repository scireum/sirius-biz, pull requests merged in 2025-09, with the labels that each got.

#2159 Lokalise: Translations update
  src/main/resources/biz_bg.properties
  src/main/resources/biz_cs.properties
  src/main/resources/biz_da.properties
  src/main/resources/biz_en.properties
  src/main/resources/biz_es.properties
  src/main/resources/biz_fi.properties
  src/main/resources/biz_fr.properties
  src/main/resources/biz_hr.properties
  src/main/resources/biz_hu.properties
  src/main/resources/biz_it.properties
  src/main/resources/biz_lt.properties
  src/main/resources/biz_lv.properties
  src/main/resources/biz_nl.properties
  src/main/resources/biz_no.properties
  src/main/resources/biz_pl.properties
  src/main/resources/biz_pt.properties
  src/main/resources/biz_ro.properties
  src/main/resources/biz_ru.properties
  src/main/resources/biz_sk.properties
  src/main/resources/biz_sl.properties
  src/main/resources/biz_sr.properties
  src/main/resources/biz_sv.properties
  src/main/resources/biz_tr.properties
  src/main/resources/biz_uk.properties
Labels: 🛠️ Maintenance

#2164 Job-Templates - Extends JobPresets with `Journaled` to allow the logging of changes to the change protocol
  src/main/java/sirius/biz/jobs/presets/JobPreset.java
  src/main/java/sirius/biz/jobs/presets/jdbc/SQLJobPreset.java
  src/main/java/sirius/biz/jobs/presets/mongo/MongoJobPreset.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#2169 Improves handling of the ultimately failed conversion
  src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/BlobDispatcher.java
  src/main/java/sirius/biz/storage/layer2/URLBuilder.java
  src/main/java/sirius/biz/storage/layer2/variants/ConversionEngine.java
Labels: 🧬 Enhancement, 🐛 Bugfix, 🔥 Hotfix

#2170 Fixes the broken image symbol and not necessary retries
  src/main/java/sirius/biz/storage/layer2/URLBuilder.java
  src/main/resources/default/assets/scripts/images.js
Labels: 🐛 Bugfix

#2172 SE-14786 Allow setting the SSL protocol in the FTPS uplink
  src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPSUplinkConnectorConfig.java
  src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplinkConnectorConfig.java
  src/main/resources/component-070-biz.conf
Labels: 🧬 Enhancement
