Repository scireum/sirius-biz, pull requests merged in 2025-01, with the labels that each got.

#2069 Rate Limiting: Miscellaneous Improvements
  src/main/java/sirius/biz/isenguard/Isenguard.java
  src/main/java/sirius/biz/isenguard/IsenguardFirewall.java
  src/main/java/sirius/biz/isenguard/Limiter.java
  src/main/java/sirius/biz/isenguard/NOOPLimiter.java
  src/main/java/sirius/biz/isenguard/RedisLimiter.java
  src/main/java/sirius/biz/isenguard/SmartLimiter.java
  src/test/kotlin/sirius/biz/isenguard/IsenguardTest.kt
Labels: 🧬 Enhancement, 💣 BREAKING CHANGE, 🛠️ Maintenance

#2070 Sirius
  pom.xml
Labels: ⬆️ Dependencies

#2072 Rate Limiting: Exposed Exception Building
  src/main/java/sirius/biz/isenguard/Isenguard.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#2071 Allow fetchCachedValue() for sandbox as fetchValue() was before
  src/main/resources/component-070-biz.conf
Labels: 🐛 Bugfix, 👶🏻 Trivial

#2073 Renders raw HTML from action descriptions
  src/main/resources/default/taglib/t/actions.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#2076 Lokalise: Translations update
  src/main/resources/biz_en.properties
  src/main/resources/biz_fr.properties
  src/main/resources/biz_pl.properties
Labels: 🛠️ Maintenance

#2074 Cluster Caches Overview
  src/main/java/sirius/biz/cluster/ClusterController.java
  src/main/resources/default/templates/biz/cluster/caches.html.pasta
  src/main/resources/default/templates/biz/cluster/cluster.html.pasta
Labels: 🧬 Enhancement

#2077 Adds apache-mina as directly dependency
  pom.xml
Labels: ⬆️ Dependencies

#2078 Show HTML formatted job descriptions in OpenSearch
  src/main/java/sirius/biz/jobs/JobsSearchProvider.java
  src/main/java/sirius/biz/tycho/search/OpenSearchResult.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#2079 HTTPS URL Property Validator
  pom.xml
  src/main/java/sirius/biz/tenants/HttpsUrlValidator.java
  src/main/resources/biz_de.properties
Labels: 🧬 Enhancement

#2080 hide quirky show-password field in edge - we have our own one.
  src/main/resources/default/templates/biz/login.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#2082 Lokalise: Translations update
  src/main/resources/biz_bg.properties
  src/main/resources/biz_cs.properties
  src/main/resources/biz_da.properties
  src/main/resources/biz_en.properties
  src/main/resources/biz_es.properties
  src/main/resources/biz_fi.properties
  src/main/resources/biz_fr.properties
  src/main/resources/biz_hr.properties
  src/main/resources/biz_hu.properties
  src/main/resources/biz_it.properties
  src/main/resources/biz_lt.properties
  src/main/resources/biz_lv.properties
  src/main/resources/biz_nl.properties
  src/main/resources/biz_no.properties
  src/main/resources/biz_pl.properties
  src/main/resources/biz_pt.properties
  src/main/resources/biz_ro.properties
  src/main/resources/biz_ru.properties
  src/main/resources/biz_sk.properties
  src/main/resources/biz_sl.properties
  src/main/resources/biz_sr.properties
  src/main/resources/biz_sv.properties
  src/main/resources/biz_tr.properties
  src/main/resources/biz_uk.properties
Labels: 🧬 Enhancement

#2081 fix update report for hacky values
  src/main/java/sirius/biz/tycho/updates/UpdatesController.java
  src/main/java/sirius/biz/tycho/updates/UpdatesReport.java
  src/main/resources/default/templates/biz/tycho/dashboard-news.html.pasta
Labels: 🐛 Bugfix

#2083 SIRI-1047 List Yes, No or Ja, Nein for allowed boolean values in job-docu, also translated enum values
  src/main/java/sirius/biz/importer/format/EnumPropertyTransformer.java
  src/main/java/sirius/biz/importer/format/FieldDefinition.java
Labels: 🧬 Enhancement
