Repository scireum/sirius-biz, pull requests merged in 2025-06, with the labels that each got.

#2138 Smart get the message type when logging them to the process log files
  src/main/java/sirius/biz/process/ProcessEnvironment.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#2139 t:blobImage - Implements additional attribute `alt` to be able to pass an alt text to the images
  src/main/resources/default/taglib/t/blobImage.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#2142 Utility Methods for Process Links
  src/main/java/sirius/biz/process/ProcessContext.java
  src/main/java/sirius/biz/process/ProcessEnvironment.java
  src/main/java/sirius/biz/process/ProcessLink.java
  src/main/java/sirius/biz/process/Processes.java
Labels: 🧬 Enhancement
