Repository scireum/sirius-biz, pull requests merged in 2025-03, with the labels that each got.

#2100 SIRI-1076 update docker image versions to newer ones
  docker-compose.yml
  src/test/resources/docker-compose.yml
Labels: ⬆️ Dependencies

#2103 Adds an admin job to scan for missing storage objects
  pom.xml
  src/main/java/sirius/biz/jobs/params/IntParameter.java
  src/main/java/sirius/biz/storage/layer1/FSObjectStorageSpace.java
  src/main/java/sirius/biz/storage/layer1/ObjectStorageSpace.java
  src/main/java/sirius/biz/storage/layer1/S3ObjectStorageSpace.java
  src/main/java/sirius/biz/storage/util/MissingBlobObjectCheckJob.java
  src/main/java/sirius/biz/storage/util/MissingMongoBlobObjectCheckJob.java
  src/main/java/sirius/biz/storage/util/MissingSqlBlobObjectCheckJob.java
Labels: 🧬 Enhancement

#2105 Fixes handling and rendering of blobs which ultimately failed conversion
  src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/URLBuilder.java
Labels: 🐛 Bugfix

#2107 Adds a cell format for displaying lines of data (e.g. addresses).
  src/main/java/sirius/biz/analytics/reports/Cells.java
  src/main/java/sirius/biz/analytics/reports/LinesCellFormat.java
Labels: 🧬 Enhancement

#2108 Updates sirius parent and libs
  pom.xml
Labels: ⬆️ Dependencies
