Repository scireum/sirius-biz, pull requests merged in 2025-04, with the labels that each got.

#2110 Lokalise: Translations update
  src/main/resources/biz_bg.properties
  src/main/resources/biz_cs.properties
  src/main/resources/biz_da.properties
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
  src/main/resources/biz_es.properties
  src/main/resources/biz_fi.properties
  src/main/resources/biz_fr.properties
  src/main/resources/biz_hr.properties
  src/main/resources/biz_hu.properties
  src/main/resources/biz_it.properties
  src/main/resources/biz_lt.properties
  src/main/resources/biz_lv.properties
  src/main/resources/biz_nl.properties
  src/main/resources/biz_no.properties
  src/main/resources/biz_pl.properties
  src/main/resources/biz_pt.properties
  src/main/resources/biz_ro.properties
  src/main/resources/biz_ru.properties
  src/main/resources/biz_sk.properties
  src/main/resources/biz_sl.properties
  src/main/resources/biz_sr.properties
  src/main/resources/biz_sv.properties
  src/main/resources/biz_tr.properties
  src/main/resources/biz_uk.properties
Labels: 🛠️ Maintenance

#2112 Data Explorer - Fixes issues overlapping filter elements not breaking into lines correctly
  src/main/resources/default/templates/biz/tycho/analytics/data-explorer.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#2111 Cleanup of HeadRequestFileResolver
  pom.xml
  src/main/java/sirius/biz/storage/layer3/HeadRequestFileResolver.java
Labels: 🧬 Enhancement

#2113 KBA - Use correct object fit mode for preview images in articles
  src/main/resources/default/taglib/k/previewImage.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#2114 Custom Scripting - Adds buttons to allow the deletion of custom scripts
  src/main/java/sirius/biz/scripting/mongo/MongoCustomScriptController.java
  src/main/resources/default/templates/biz/scripting/mongo-script.html.pasta
  src/main/resources/default/templates/biz/scripting/mongo-scripts.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#2115 Jupiter - Disable sending redis client info to jupiter server
  pom.xml
  src/main/resources/component-070-biz.conf
Labels: 👶🏻 Trivial, 🛠️ Maintenance

#2117 Job Scheduler: Job Preselection
  src/main/java/sirius/biz/jobs/Jobs.java
  src/main/java/sirius/biz/jobs/scheduler/SchedulerController.java
  src/main/resources/default/templates/biz/jobs/scheduler/entry.html.pasta
Labels: 🧬 Enhancement

#2116 Avoids repeating the name as label in dict. validation errors
  src/main/java/sirius/biz/importer/format/FieldDefinition.java
  src/main/java/sirius/biz/importer/format/ImportDictionary.java
  src/main/resources/biz_de.properties
Labels: 🧬 Enhancement

#2118 Uses newest mongo db driver and upgrades to Mongo 8
  docker-compose.yml
  pom.xml
  src/test/resources/docker-compose.yml
Labels: 👶🏻 Trivial, ⬆️ Dependencies

#2120 Lokalise: Translations update
  src/main/resources/biz_bg.properties
  src/main/resources/biz_cs.properties
  src/main/resources/biz_da.properties
  src/main/resources/biz_en.properties
  src/main/resources/biz_es.properties
  src/main/resources/biz_fi.properties
  src/main/resources/biz_fr.properties
  src/main/resources/biz_hr.properties
  src/main/resources/biz_hu.properties
  src/main/resources/biz_it.properties
  src/main/resources/biz_lt.properties
  src/main/resources/biz_lv.properties
  src/main/resources/biz_nl.properties
  src/main/resources/biz_no.properties
  src/main/resources/biz_pl.properties
  src/main/resources/biz_pt.properties
  src/main/resources/biz_ro.properties
  src/main/resources/biz_ru.properties
  src/main/resources/biz_sk.properties
  src/main/resources/biz_sl.properties
  src/main/resources/biz_sr.properties
  src/main/resources/biz_sv.properties
  src/main/resources/biz_tr.properties
  src/main/resources/biz_uk.properties
Labels: 🛠️ Maintenance

#2121 KB Assets (SIRI-1098) and Scheduled Job Improvements (SIRI-1097)
  src/main/java/sirius/biz/jobs/scheduler/SchedulerData.java
  src/main/java/sirius/biz/tycho/kb/KnowledgeBaseController.java
  src/main/resources/biz_de.properties
  src/main/resources/default/kb/de/admin/book-JFLRO.html.pasta
  src/main/resources/default/kb/de/admin/core-SKAME.html.pasta
  src/main/resources/default/kb/de/admin/modules-ASMEK.html.pasta
  src/main/resources/default/kb/de/user/book-SLEOK.html.pasta
  src/main/resources/default/kb/de/user/core-AHJEC.html.pasta
  src/main/resources/default/kb/de/user/ftp-import-EAI5V.html.pasta
  src/main/resources/default/kb/de/user/images/jobs-general.png
  src/main/resources/default/kb/de/user/images/jobs-scheduling.png
  src/main/resources/default/kb/de/user/jobs-and-cron-92A2A.html.pasta
  src/main/resources/default/kb/de/user/modules-DJKLE.html.pasta
  src/main/resources/default/kb/de/user/response-codes-7EWJ3.html.pasta
  src/main/resources/default/kb/en/admin/book-JFLRO.html.pasta
  src/main/resources/default/kb/en/admin/core-SKAME.html.pasta
  src/main/resources/default/kb/en/admin/modules-ASMEK.html.pasta
  src/main/resources/default/kb/en/system/book-HDJEK.html.pasta
  src/main/resources/default/kb/en/system/cluster-V7FGJ.html.pasta
  src/main/resources/default/kb/en/system/core-DJELK.html.pasta
  src/main/resources/default/kb/en/system/customization-flags-JDKOE.html.pasta
  src/main/resources/default/kb/en/system/health-5ZM4U.html.pasta
  src/main/resources/default/kb/en/system/kb-VFLEO.html.pasta
  src/main/resources/default/kb/en/system/modules-JRKAM.html.pasta
  src/main/resources/default/kb/en/system/permissions-FJK4D.html.pasta
  src/main/resources/default/kb/en/system/schema-S1Q2L.html.pasta
  src/main/resources/default/kb/en/system/scripting-P399F.html.pasta
  src/main/resources/default/kb/en/system/troubleshooting-SHJEK.html.pasta
  src/main/resources/default/kb/en/user/book-SLEOK.html.pasta
  src/main/resources/default/kb/en/user/core-AHJEC.html.pasta
  src/main/resources/default/kb/en/user/modules-DJKLE.html.pasta
  src/main/resources/default/kb/en/user/noodle-HP9RC.html.pasta
  src/main/resources/default/kb/en/user/response-codes-7EWJ3.html.pasta
  src/main/resources/default/kb/en/user/tagliatelle-T2IQI.html.pasta
  src/main/resources/default/taglib/t/helpLink.html.pasta
  src/main/resources/default/templates/biz/jobs/scheduler/entry.html.pasta
Labels: 🧬 Enhancement

#2122 Lokalise: Translations update
  src/main/resources/biz_bg.properties
  src/main/resources/biz_cs.properties
  src/main/resources/biz_da.properties
  src/main/resources/biz_de.properties
  src/main/resources/biz_en.properties
  src/main/resources/biz_es.properties
  src/main/resources/biz_fi.properties
  src/main/resources/biz_fr.properties
  src/main/resources/biz_hr.properties
  src/main/resources/biz_hu.properties
  src/main/resources/biz_it.properties
  src/main/resources/biz_lt.properties
  src/main/resources/biz_lv.properties
  src/main/resources/biz_nl.properties
  src/main/resources/biz_no.properties
  src/main/resources/biz_pl.properties
  src/main/resources/biz_pt.properties
  src/main/resources/biz_ro.properties
  src/main/resources/biz_ru.properties
  src/main/resources/biz_sk.properties
  src/main/resources/biz_sl.properties
  src/main/resources/biz_sr.properties
  src/main/resources/biz_sv.properties
  src/main/resources/biz_tr.properties
  src/main/resources/biz_uk.properties
Labels: 🛠️ Maintenance

#2123 Sirius
  pom.xml
Labels: 👶🏻 Trivial, ⬆️ Dependencies

#2125 Job Scheduling: Error Handling (SIRI-1097)
  src/main/java/sirius/biz/jobs/scheduler/SchedulerController.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#2124 Upgrades mongodb to 8.0.8
  docker-compose.yml
  src/test/resources/docker-compose.yml
Labels: 👶🏻 Trivial, ⬆️ Dependencies

#2127 Sirius
  pom.xml
Labels: 👶🏻 Trivial, ⬆️ Dependencies

#2128 Lokalise: Translations update
  src/main/resources/biz_es.properties
  src/main/resources/biz_fi.properties
Labels: 🐛 Bugfix, 👶🏻 Trivial, 🛠️ Maintenance

#2129 Update Docker containers to latest versions
  docker-compose.yml
  src/test/resources/docker-compose.yml
Labels: 👶🏻 Trivial, ⬆️ Dependencies, 🛠️ Maintenance
