Repository scireum/sirius-biz, pull requests merged in 2025-07, with the labels that each got.

#2144 Add eu flag
  src/main/resources/default/assets/images/flags/countries/eu.png
Labels: 🧬 Enhancement, 👶🏻 Trivial

#2146 Java24 and libs
  .drone.yml
  pom.xml
  src/main/java/sirius/biz/analytics/events/ClickhousePartsReportJobFactory.java
  src/main/java/sirius/biz/analytics/reports/LinesCellFormat.java
  src/main/java/sirius/biz/cluster/RedisUserMessageCache.java
  src/main/java/sirius/biz/codelists/LookupTable.java
  src/main/java/sirius/biz/jobs/BasicJobFactory.java
  src/main/java/sirius/biz/jobs/JobConfigData.java
  src/main/java/sirius/biz/jobs/scheduler/SchedulerController.java
  src/main/java/sirius/biz/storage/layer2/BlobSoftRef.java
  src/main/java/sirius/biz/storage/layer2/URLBuilder.java
  src/main/java/sirius/biz/storage/layer3/VFSSearchProvider.java
  src/main/java/sirius/biz/storage/legacy/Storage.java
  src/main/java/sirius/biz/storage/legacy/StoredObjectRef.java
  src/main/java/sirius/biz/tenants/HttpsUrlValidator.java
  src/main/java/sirius/biz/tenants/UserAccountSearchProvider.java
  src/main/java/sirius/biz/tycho/smart/EmailSmartValueProvider.java
  src/main/java/sirius/biz/tycho/updates/UpdatesController.java
  src/main/java/sirius/biz/tycho/updates/UpdatesReport.java
  src/main/java/sirius/biz/util/ReportUnusedNLSKeysJob.java
Labels: 💣 BREAKING CHANGE, ⬆️ Dependencies

#2145 Only call conversion failed handlers after all attempts were made
  src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
  src/main/java/sirius/biz/storage/layer2/README.md
Labels: 🐛 Bugfix

#2147 Upgrades elasticsearch to 8.18.3
  docker-compose.yml
  pom.xml
  src/test/resources/docker-compose.yml
Labels: 👶🏻 Trivial, 🛠️ Maintenance
